template: testify
template-data:
  unroll-variadic: true
filename: "{{.InterfaceName}}.go"
packages:
  go.lumeweb.com/portal/config:
    interfaces:
      Manager: {}
  go.lumeweb.com/portal/core:
    config:
      dir: ./core/testing/mocks
      pkgname: "mocks"
    interfaces:
      API: {}
      APIExtension: {}
      APIInit: {}
      AccessService: {}
      AuthService: {}
      ConfigService: {}
      Configurable: {}
      ContentScanner: {}
      ContentScannerService: {}
      Context: {}
      CronService: {}
      Cronable: {}
      Eventer: {}
      HTTPService: {}
      HashFactory: {}
      HashMappingService: {}
      HashProofGenerator: {}
      HashProofProvider: {}
      HashProofVerifier: {}
      HashRegistry: {}
      MailerService: {}
      MailerTemplate: {}
      OTPService: {}
      Operation: {}
      OperationHandler: {}
      PasswordResetService: {}
      PinService: {}
      PluginMetaBuilder: {}
      PortalMetaBuilder: {}
      Protocol: {}
      ProtocolInit: {}
      ProtocolParser: {}
      ProtocolPinHandler: {}
      ProtocolRequestDataHandler: {}
      ProtocolStart: {}
      ProtocolStop: {}
      RenterService: {}
      RequestService: {}
      RoutableAPI: {}
      Service: {}
      StorageHash: {}
      StorageHashParser: {}
      StorageProtocol: {}
      StorageService: {}
      StorageUploadRequest: {}
      TUSService: {}
      TestingHash: {}
      TestingHashProofGenerator: {}
      TestingHashProofProvider: {}
      TestingHashProofVerifier: {}
      TestingHashWithProof: {}
      TestingProtocolPinHandler: {}
      TestingProtocolRequestDataHandler: {}
      TestingTestingHashWithProof: {}
      UploadDataHandler: {}
      UploadService: {}
      UserService: {}
      WorkflowCoordinator: {}
      WorkflowService: {}