// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	core "go.lumeweb.com/portal/core"
)

// MockAccessService is an autogenerated mock type for the AccessService type
type MockAccessService struct {
	mock.Mock
}

type MockAccessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessService) EXPECT() *MockAccessService_Expecter {
	return &MockAccessService_Expecter{mock: &_m.Mock}
}

// AssignRoleToUser provides a mock function with given fields: userId, role
func (_m *MockAccessService) AssignRoleToUser(userId uint, role string) error {
	ret := _m.Called(userId, role)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(userId, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccessService_AssignRoleToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRoleToUser'
type MockAccessService_AssignRoleToUser_Call struct {
	*mock.Call
}

// AssignRoleToUser is a helper method to define mock.On call
//   - userId uint
//   - role string
func (_e *MockAccessService_Expecter) AssignRoleToUser(userId interface{}, role interface{}) *MockAccessService_AssignRoleToUser_Call {
	return &MockAccessService_AssignRoleToUser_Call{Call: _e.mock.On("AssignRoleToUser", userId, role)}
}

func (_c *MockAccessService_AssignRoleToUser_Call) Run(run func(userId uint, role string)) *MockAccessService_AssignRoleToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockAccessService_AssignRoleToUser_Call) Return(_a0 error) *MockAccessService_AssignRoleToUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccessService_AssignRoleToUser_Call) RunAndReturn(run func(uint, string) error) *MockAccessService_AssignRoleToUser_Call {
	_c.Call.Return(run)
	return _c
}

// CheckAccess provides a mock function with given fields: userId, fqdn, path, method
func (_m *MockAccessService) CheckAccess(userId uint, fqdn string, path string, method string) (bool, error) {
	ret := _m.Called(userId, fqdn, path, method)

	if len(ret) == 0 {
		panic("no return value specified for CheckAccess")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string, string, string) (bool, error)); ok {
		return rf(userId, fqdn, path, method)
	}
	if rf, ok := ret.Get(0).(func(uint, string, string, string) bool); ok {
		r0 = rf(userId, fqdn, path, method)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint, string, string, string) error); ok {
		r1 = rf(userId, fqdn, path, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessService_CheckAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAccess'
type MockAccessService_CheckAccess_Call struct {
	*mock.Call
}

// CheckAccess is a helper method to define mock.On call
//   - userId uint
//   - fqdn string
//   - path string
//   - method string
func (_e *MockAccessService_Expecter) CheckAccess(userId interface{}, fqdn interface{}, path interface{}, method interface{}) *MockAccessService_CheckAccess_Call {
	return &MockAccessService_CheckAccess_Call{Call: _e.mock.On("CheckAccess", userId, fqdn, path, method)}
}

func (_c *MockAccessService_CheckAccess_Call) Run(run func(userId uint, fqdn string, path string, method string)) *MockAccessService_CheckAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAccessService_CheckAccess_Call) Return(_a0 bool, _a1 error) *MockAccessService_CheckAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessService_CheckAccess_Call) RunAndReturn(run func(uint, string, string, string) (bool, error)) *MockAccessService_CheckAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ExportModel provides a mock function with no fields
func (_m *MockAccessService) ExportModel() *core.AccessModel {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExportModel")
	}

	var r0 *core.AccessModel
	if rf, ok := ret.Get(0).(func() *core.AccessModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.AccessModel)
		}
	}

	return r0
}

// MockAccessService_ExportModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportModel'
type MockAccessService_ExportModel_Call struct {
	*mock.Call
}

// ExportModel is a helper method to define mock.On call
func (_e *MockAccessService_Expecter) ExportModel() *MockAccessService_ExportModel_Call {
	return &MockAccessService_ExportModel_Call{Call: _e.mock.On("ExportModel")}
}

func (_c *MockAccessService_ExportModel_Call) Run(run func()) *MockAccessService_ExportModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccessService_ExportModel_Call) Return(_a0 *core.AccessModel) *MockAccessService_ExportModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccessService_ExportModel_Call) RunAndReturn(run func() *core.AccessModel) *MockAccessService_ExportModel_Call {
	_c.Call.Return(run)
	return _c
}

// ExportUserPolicy provides a mock function with given fields: userId
func (_m *MockAccessService) ExportUserPolicy(userId uint) ([]*core.AccessPolicy, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for ExportUserPolicy")
	}

	var r0 []*core.AccessPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*core.AccessPolicy, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint) []*core.AccessPolicy); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.AccessPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessService_ExportUserPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportUserPolicy'
type MockAccessService_ExportUserPolicy_Call struct {
	*mock.Call
}

// ExportUserPolicy is a helper method to define mock.On call
//   - userId uint
func (_e *MockAccessService_Expecter) ExportUserPolicy(userId interface{}) *MockAccessService_ExportUserPolicy_Call {
	return &MockAccessService_ExportUserPolicy_Call{Call: _e.mock.On("ExportUserPolicy", userId)}
}

func (_c *MockAccessService_ExportUserPolicy_Call) Run(run func(userId uint)) *MockAccessService_ExportUserPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockAccessService_ExportUserPolicy_Call) Return(_a0 []*core.AccessPolicy, _a1 error) *MockAccessService_ExportUserPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessService_ExportUserPolicy_Call) RunAndReturn(run func(uint) ([]*core.AccessPolicy, error)) *MockAccessService_ExportUserPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockAccessService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAccessService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockAccessService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockAccessService_Expecter) ID() *MockAccessService_ID_Call {
	return &MockAccessService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockAccessService_ID_Call) Run(run func()) *MockAccessService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccessService_ID_Call) Return(_a0 string) *MockAccessService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccessService_ID_Call) RunAndReturn(run func() string) *MockAccessService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRoute provides a mock function with given fields: subdomain, path, method, role
func (_m *MockAccessService) RegisterRoute(subdomain string, path string, method string, role string) error {
	ret := _m.Called(subdomain, path, method, role)

	if len(ret) == 0 {
		panic("no return value specified for RegisterRoute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(subdomain, path, method, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccessService_RegisterRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoute'
type MockAccessService_RegisterRoute_Call struct {
	*mock.Call
}

// RegisterRoute is a helper method to define mock.On call
//   - subdomain string
//   - path string
//   - method string
//   - role string
func (_e *MockAccessService_Expecter) RegisterRoute(subdomain interface{}, path interface{}, method interface{}, role interface{}) *MockAccessService_RegisterRoute_Call {
	return &MockAccessService_RegisterRoute_Call{Call: _e.mock.On("RegisterRoute", subdomain, path, method, role)}
}

func (_c *MockAccessService_RegisterRoute_Call) Run(run func(subdomain string, path string, method string, role string)) *MockAccessService_RegisterRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAccessService_RegisterRoute_Call) Return(_a0 error) *MockAccessService_RegisterRoute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccessService_RegisterRoute_Call) RunAndReturn(run func(string, string, string, string) error) *MockAccessService_RegisterRoute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessService creates a new instance of MockAccessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessService {
	mock := &MockAccessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
