// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/core"
)

// NewMockAccessService creates a new instance of MockAccessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessService {
	mock := &MockAccessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessService is an autogenerated mock type for the AccessService type
type MockAccessService struct {
	mock.Mock
}

type MockAccessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessService) EXPECT() *MockAccessService_Expecter {
	return &MockAccessService_Expecter{mock: &_m.Mock}
}

// AssignRoleToUser provides a mock function for the type MockAccessService
func (_mock *MockAccessService) AssignRoleToUser(userId uint, role string) error {
	ret := _mock.Called(userId, role)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = returnFunc(userId, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccessService_AssignRoleToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRoleToUser'
type MockAccessService_AssignRoleToUser_Call struct {
	*mock.Call
}

// AssignRoleToUser is a helper method to define mock.On call
//   - userId uint
//   - role string
func (_e *MockAccessService_Expecter) AssignRoleToUser(userId interface{}, role interface{}) *MockAccessService_AssignRoleToUser_Call {
	return &MockAccessService_AssignRoleToUser_Call{Call: _e.mock.On("AssignRoleToUser", userId, role)}
}

func (_c *MockAccessService_AssignRoleToUser_Call) Run(run func(userId uint, role string)) *MockAccessService_AssignRoleToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccessService_AssignRoleToUser_Call) Return(err error) *MockAccessService_AssignRoleToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccessService_AssignRoleToUser_Call) RunAndReturn(run func(userId uint, role string) error) *MockAccessService_AssignRoleToUser_Call {
	_c.Call.Return(run)
	return _c
}

// CheckAccess provides a mock function for the type MockAccessService
func (_mock *MockAccessService) CheckAccess(userId uint, fqdn string, path string, method string) (bool, error) {
	ret := _mock.Called(userId, fqdn, path, method)

	if len(ret) == 0 {
		panic("no return value specified for CheckAccess")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, string, string, string) (bool, error)); ok {
		return returnFunc(userId, fqdn, path, method)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, string, string, string) bool); ok {
		r0 = returnFunc(userId, fqdn, path, method)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint, string, string, string) error); ok {
		r1 = returnFunc(userId, fqdn, path, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessService_CheckAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAccess'
type MockAccessService_CheckAccess_Call struct {
	*mock.Call
}

// CheckAccess is a helper method to define mock.On call
//   - userId uint
//   - fqdn string
//   - path string
//   - method string
func (_e *MockAccessService_Expecter) CheckAccess(userId interface{}, fqdn interface{}, path interface{}, method interface{}) *MockAccessService_CheckAccess_Call {
	return &MockAccessService_CheckAccess_Call{Call: _e.mock.On("CheckAccess", userId, fqdn, path, method)}
}

func (_c *MockAccessService_CheckAccess_Call) Run(run func(userId uint, fqdn string, path string, method string)) *MockAccessService_CheckAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccessService_CheckAccess_Call) Return(b bool, err error) *MockAccessService_CheckAccess_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAccessService_CheckAccess_Call) RunAndReturn(run func(userId uint, fqdn string, path string, method string) (bool, error)) *MockAccessService_CheckAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ExportModel provides a mock function for the type MockAccessService
func (_mock *MockAccessService) ExportModel() *core.AccessModel {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExportModel")
	}

	var r0 *core.AccessModel
	if returnFunc, ok := ret.Get(0).(func() *core.AccessModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.AccessModel)
		}
	}
	return r0
}

// MockAccessService_ExportModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportModel'
type MockAccessService_ExportModel_Call struct {
	*mock.Call
}

// ExportModel is a helper method to define mock.On call
func (_e *MockAccessService_Expecter) ExportModel() *MockAccessService_ExportModel_Call {
	return &MockAccessService_ExportModel_Call{Call: _e.mock.On("ExportModel")}
}

func (_c *MockAccessService_ExportModel_Call) Run(run func()) *MockAccessService_ExportModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccessService_ExportModel_Call) Return(accessModel *core.AccessModel) *MockAccessService_ExportModel_Call {
	_c.Call.Return(accessModel)
	return _c
}

func (_c *MockAccessService_ExportModel_Call) RunAndReturn(run func() *core.AccessModel) *MockAccessService_ExportModel_Call {
	_c.Call.Return(run)
	return _c
}

// ExportUserPolicy provides a mock function for the type MockAccessService
func (_mock *MockAccessService) ExportUserPolicy(userId uint) ([]*core.AccessPolicy, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for ExportUserPolicy")
	}

	var r0 []*core.AccessPolicy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]*core.AccessPolicy, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []*core.AccessPolicy); ok {
		r0 = returnFunc(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.AccessPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccessService_ExportUserPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportUserPolicy'
type MockAccessService_ExportUserPolicy_Call struct {
	*mock.Call
}

// ExportUserPolicy is a helper method to define mock.On call
//   - userId uint
func (_e *MockAccessService_Expecter) ExportUserPolicy(userId interface{}) *MockAccessService_ExportUserPolicy_Call {
	return &MockAccessService_ExportUserPolicy_Call{Call: _e.mock.On("ExportUserPolicy", userId)}
}

func (_c *MockAccessService_ExportUserPolicy_Call) Run(run func(userId uint)) *MockAccessService_ExportUserPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccessService_ExportUserPolicy_Call) Return(accessPolicys []*core.AccessPolicy, err error) *MockAccessService_ExportUserPolicy_Call {
	_c.Call.Return(accessPolicys, err)
	return _c
}

func (_c *MockAccessService_ExportUserPolicy_Call) RunAndReturn(run func(userId uint) ([]*core.AccessPolicy, error)) *MockAccessService_ExportUserPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockAccessService
func (_mock *MockAccessService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAccessService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockAccessService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockAccessService_Expecter) ID() *MockAccessService_ID_Call {
	return &MockAccessService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockAccessService_ID_Call) Run(run func()) *MockAccessService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccessService_ID_Call) Return(s string) *MockAccessService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAccessService_ID_Call) RunAndReturn(run func() string) *MockAccessService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRoute provides a mock function for the type MockAccessService
func (_mock *MockAccessService) RegisterRoute(subdomain string, path string, method string, role string) error {
	ret := _mock.Called(subdomain, path, method, role)

	if len(ret) == 0 {
		panic("no return value specified for RegisterRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = returnFunc(subdomain, path, method, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccessService_RegisterRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoute'
type MockAccessService_RegisterRoute_Call struct {
	*mock.Call
}

// RegisterRoute is a helper method to define mock.On call
//   - subdomain string
//   - path string
//   - method string
//   - role string
func (_e *MockAccessService_Expecter) RegisterRoute(subdomain interface{}, path interface{}, method interface{}, role interface{}) *MockAccessService_RegisterRoute_Call {
	return &MockAccessService_RegisterRoute_Call{Call: _e.mock.On("RegisterRoute", subdomain, path, method, role)}
}

func (_c *MockAccessService_RegisterRoute_Call) Run(run func(subdomain string, path string, method string, role string)) *MockAccessService_RegisterRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccessService_RegisterRoute_Call) Return(err error) *MockAccessService_RegisterRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccessService_RegisterRoute_Call) RunAndReturn(run func(subdomain string, path string, method string, role string) error) *MockAccessService_RegisterRoute_Call {
	_c.Call.Return(run)
	return _c
}
