// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-router"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockAPI creates a new instance of MockAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPI {
	mock := &MockAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPI is an autogenerated mock type for the API type
type MockAPI struct {
	mock.Mock
}

type MockAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPI) EXPECT() *MockAPI_Expecter {
	return &MockAPI_Expecter{mock: &_m.Mock}
}

// AuthTokenName provides a mock function for the type MockAPI
func (_mock *MockAPI) AuthTokenName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthTokenName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAPI_AuthTokenName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthTokenName'
type MockAPI_AuthTokenName_Call struct {
	*mock.Call
}

// AuthTokenName is a helper method to define mock.On call
func (_e *MockAPI_Expecter) AuthTokenName() *MockAPI_AuthTokenName_Call {
	return &MockAPI_AuthTokenName_Call{Call: _e.mock.On("AuthTokenName")}
}

func (_c *MockAPI_AuthTokenName_Call) Run(run func()) *MockAPI_AuthTokenName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_AuthTokenName_Call) Return(s string) *MockAPI_AuthTokenName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAPI_AuthTokenName_Call) RunAndReturn(run func() string) *MockAPI_AuthTokenName_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockAPI
func (_mock *MockAPI) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockAPI_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockAPI_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockAPI_Expecter) Config() *MockAPI_Config_Call {
	return &MockAPI_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockAPI_Config_Call) Run(run func()) *MockAPI_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_Config_Call) Return(manager config.Manager) *MockAPI_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockAPI_Config_Call) RunAndReturn(run func() config.Manager) *MockAPI_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Configure provides a mock function for the type MockAPI
func (_mock *MockAPI) Configure(router1 router.Router, accessSvc core.AccessService) error {
	ret := _mock.Called(router1, accessSvc)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(router.Router, core.AccessService) error); ok {
		r0 = returnFunc(router1, accessSvc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPI_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockAPI_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - router1 router.Router
//   - accessSvc core.AccessService
func (_e *MockAPI_Expecter) Configure(router1 any, accessSvc any) *MockAPI_Configure_Call {
	return &MockAPI_Configure_Call{Call: _e.mock.On("Configure", router1, accessSvc)}
}

func (_c *MockAPI_Configure_Call) Run(run func(router1 router.Router, accessSvc core.AccessService)) *MockAPI_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 router.Router
		if args[0] != nil {
			arg0 = args[0].(router.Router)
		}
		var arg1 core.AccessService
		if args[1] != nil {
			arg1 = args[1].(core.AccessService)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPI_Configure_Call) Return(err error) *MockAPI_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPI_Configure_Call) RunAndReturn(run func(router1 router.Router, accessSvc core.AccessService) error) *MockAPI_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockAPI
func (_mock *MockAPI) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockAPI_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockAPI_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockAPI_Expecter) Context() *MockAPI_Context_Call {
	return &MockAPI_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockAPI_Context_Call) Run(run func()) *MockAPI_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_Context_Call) Return(context core.Context) *MockAPI_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockAPI_Context_Call) RunAndReturn(run func() core.Context) *MockAPI_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockAPI
func (_mock *MockAPI) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockAPI_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockAPI_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockAPI_Expecter) DB() *MockAPI_DB_Call {
	return &MockAPI_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockAPI_DB_Call) Run(run func()) *MockAPI_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_DB_Call) Return(dB *gorm.DB) *MockAPI_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockAPI_DB_Call) RunAndReturn(run func() *gorm.DB) *MockAPI_DB_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockAPI
func (_mock *MockAPI) GetConfig() config.APIConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.APIConfig
	if returnFunc, ok := ret.Get(0).(func() config.APIConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.APIConfig)
		}
	}
	return r0
}

// MockAPI_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockAPI_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockAPI_Expecter) GetConfig() *MockAPI_GetConfig_Call {
	return &MockAPI_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockAPI_GetConfig_Call) Run(run func()) *MockAPI_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_GetConfig_Call) Return(aPIConfig config.APIConfig) *MockAPI_GetConfig_Call {
	_c.Call.Return(aPIConfig)
	return _c
}

func (_c *MockAPI_GetConfig_Call) RunAndReturn(run func() config.APIConfig) *MockAPI_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockAPI
func (_mock *MockAPI) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAPI_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockAPI_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockAPI_Expecter) ID() *MockAPI_ID_Call {
	return &MockAPI_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockAPI_ID_Call) Run(run func()) *MockAPI_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_ID_Call) Return(s string) *MockAPI_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAPI_ID_Call) RunAndReturn(run func() string) *MockAPI_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockAPI
func (_mock *MockAPI) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockAPI_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockAPI_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockAPI_Expecter) Logger() *MockAPI_Logger_Call {
	return &MockAPI_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockAPI_Logger_Call) Run(run func()) *MockAPI_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_Logger_Call) Return(logger *core.Logger) *MockAPI_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockAPI_Logger_Call) RunAndReturn(run func() *core.Logger) *MockAPI_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockAPI
func (_mock *MockAPI) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAPI_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockAPI_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockAPI_Expecter) Name() *MockAPI_Name_Call {
	return &MockAPI_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockAPI_Name_Call) Run(run func()) *MockAPI_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_Name_Call) Return(s string) *MockAPI_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAPI_Name_Call) RunAndReturn(run func() string) *MockAPI_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OpenAPIInfo provides a mock function for the type MockAPI
func (_mock *MockAPI) OpenAPIInfo() router.APIInfoDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenAPIInfo")
	}

	var r0 router.APIInfoDefinition
	if returnFunc, ok := ret.Get(0).(func() router.APIInfoDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(router.APIInfoDefinition)
		}
	}
	return r0
}

// MockAPI_OpenAPIInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenAPIInfo'
type MockAPI_OpenAPIInfo_Call struct {
	*mock.Call
}

// OpenAPIInfo is a helper method to define mock.On call
func (_e *MockAPI_Expecter) OpenAPIInfo() *MockAPI_OpenAPIInfo_Call {
	return &MockAPI_OpenAPIInfo_Call{Call: _e.mock.On("OpenAPIInfo")}
}

func (_c *MockAPI_OpenAPIInfo_Call) Run(run func()) *MockAPI_OpenAPIInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_OpenAPIInfo_Call) Return(aPIInfoDefinition router.APIInfoDefinition) *MockAPI_OpenAPIInfo_Call {
	_c.Call.Return(aPIInfoDefinition)
	return _c
}

func (_c *MockAPI_OpenAPIInfo_Call) RunAndReturn(run func() router.APIInfoDefinition) *MockAPI_OpenAPIInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockAPI
func (_mock *MockAPI) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockAPI_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockAPI_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockAPI_Expecter) SetConfig(cfg any) *MockAPI_SetConfig_Call {
	return &MockAPI_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockAPI_SetConfig_Call) Run(run func(cfg config.Manager)) *MockAPI_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAPI_SetConfig_Call) Return() *MockAPI_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPI_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockAPI_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockAPI
func (_mock *MockAPI) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockAPI_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockAPI_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockAPI_Expecter) SetContext(ctx any) *MockAPI_SetContext_Call {
	return &MockAPI_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockAPI_SetContext_Call) Run(run func(ctx core.Context)) *MockAPI_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAPI_SetContext_Call) Return() *MockAPI_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPI_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockAPI_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockAPI
func (_mock *MockAPI) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockAPI_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockAPI_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockAPI_Expecter) SetDB(db any) *MockAPI_SetDB_Call {
	return &MockAPI_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockAPI_SetDB_Call) Run(run func(db *gorm.DB)) *MockAPI_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAPI_SetDB_Call) Return() *MockAPI_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPI_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockAPI_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockAPI
func (_mock *MockAPI) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockAPI_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockAPI_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockAPI_Expecter) SetLogger(logger any) *MockAPI_SetLogger_Call {
	return &MockAPI_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockAPI_SetLogger_Call) Run(run func(logger *core.Logger)) *MockAPI_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAPI_SetLogger_Call) Return() *MockAPI_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPI_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockAPI_SetLogger_Call {
	_c.Run(run)
	return _c
}

// Subdomain provides a mock function for the type MockAPI
func (_mock *MockAPI) Subdomain() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subdomain")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAPI_Subdomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subdomain'
type MockAPI_Subdomain_Call struct {
	*mock.Call
}

// Subdomain is a helper method to define mock.On call
func (_e *MockAPI_Expecter) Subdomain() *MockAPI_Subdomain_Call {
	return &MockAPI_Subdomain_Call{Call: _e.mock.On("Subdomain")}
}

func (_c *MockAPI_Subdomain_Call) Run(run func()) *MockAPI_Subdomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPI_Subdomain_Call) Return(s string) *MockAPI_Subdomain_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAPI_Subdomain_Call) RunAndReturn(run func() string) *MockAPI_Subdomain_Call {
	_c.Call.Return(run)
	return _c
}
