// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-router"
	"go.lumeweb.com/portal/core"
)

// NewMockAPIExtension creates a new instance of MockAPIExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIExtension {
	mock := &MockAPIExtension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIExtension is an autogenerated mock type for the APIExtension type
type MockAPIExtension struct {
	mock.Mock
}

type MockAPIExtension_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIExtension) EXPECT() *MockAPIExtension_Expecter {
	return &MockAPIExtension_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function for the type MockAPIExtension
func (_mock *MockAPIExtension) Configure(router1 router.Router, accessSvc core.AccessService) error {
	ret := _mock.Called(router1, accessSvc)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(router.Router, core.AccessService) error); ok {
		r0 = returnFunc(router1, accessSvc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIExtension_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockAPIExtension_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - router1 router.Router
//   - accessSvc core.AccessService
func (_e *MockAPIExtension_Expecter) Configure(router1 interface{}, accessSvc interface{}) *MockAPIExtension_Configure_Call {
	return &MockAPIExtension_Configure_Call{Call: _e.mock.On("Configure", router1, accessSvc)}
}

func (_c *MockAPIExtension_Configure_Call) Run(run func(router1 router.Router, accessSvc core.AccessService)) *MockAPIExtension_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 router.Router
		if args[0] != nil {
			arg0 = args[0].(router.Router)
		}
		var arg1 core.AccessService
		if args[1] != nil {
			arg1 = args[1].(core.AccessService)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIExtension_Configure_Call) Return(err error) *MockAPIExtension_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIExtension_Configure_Call) RunAndReturn(run func(router1 router.Router, accessSvc core.AccessService) error) *MockAPIExtension_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// TargetAPI provides a mock function for the type MockAPIExtension
func (_mock *MockAPIExtension) TargetAPI() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TargetAPI")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAPIExtension_TargetAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetAPI'
type MockAPIExtension_TargetAPI_Call struct {
	*mock.Call
}

// TargetAPI is a helper method to define mock.On call
func (_e *MockAPIExtension_Expecter) TargetAPI() *MockAPIExtension_TargetAPI_Call {
	return &MockAPIExtension_TargetAPI_Call{Call: _e.mock.On("TargetAPI")}
}

func (_c *MockAPIExtension_TargetAPI_Call) Run(run func()) *MockAPIExtension_TargetAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPIExtension_TargetAPI_Call) Return(s string) *MockAPIExtension_TargetAPI_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAPIExtension_TargetAPI_Call) RunAndReturn(run func() string) *MockAPIExtension_TargetAPI_Call {
	_c.Call.Return(run)
	return _c
}
