// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/core"
)

// NewMockAPIInit creates a new instance of MockAPIInit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIInit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIInit {
	mock := &MockAPIInit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIInit is an autogenerated mock type for the APIInit type
type MockAPIInit struct {
	mock.Mock
}

type MockAPIInit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIInit) EXPECT() *MockAPIInit_Expecter {
	return &MockAPIInit_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type MockAPIInit
func (_mock *MockAPIInit) Init() ([]core.ContextBuilderOption, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 []core.ContextBuilderOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]core.ContextBuilderOption, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []core.ContextBuilderOption); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.ContextBuilderOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIInit_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockAPIInit_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *MockAPIInit_Expecter) Init() *MockAPIInit_Init_Call {
	return &MockAPIInit_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *MockAPIInit_Init_Call) Run(run func()) *MockAPIInit_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPIInit_Init_Call) Return(contextBuilderOptions []core.ContextBuilderOption, err error) *MockAPIInit_Init_Call {
	_c.Call.Return(contextBuilderOptions, err)
	return _c
}

func (_c *MockAPIInit_Init_Call) RunAndReturn(run func() ([]core.ContextBuilderOption, error)) *MockAPIInit_Init_Call {
	_c.Call.Return(run)
	return _c
}
