// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
)

// NewMockConfigService creates a new instance of MockConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigService {
	mock := &MockConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigService is an autogenerated mock type for the ConfigService type
type MockConfigService struct {
	mock.Mock
}

type MockConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigService) EXPECT() *MockConfigService_Expecter {
	return &MockConfigService_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type MockConfigService
func (_mock *MockConfigService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfigService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockConfigService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockConfigService_Expecter) ID() *MockConfigService_ID_Call {
	return &MockConfigService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockConfigService_ID_Call) Run(run func()) *MockConfigService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigService_ID_Call) Return(s string) *MockConfigService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfigService_ID_Call) RunAndReturn(run func() string) *MockConfigService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterPropertyHandler provides a mock function for the type MockConfigService
func (_mock *MockConfigService) RegisterPropertyHandler(scope config.Scope, handler core.ConfigPropertyUpdateHandler) {
	_mock.Called(scope, handler)
	return
}

// MockConfigService_RegisterPropertyHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPropertyHandler'
type MockConfigService_RegisterPropertyHandler_Call struct {
	*mock.Call
}

// RegisterPropertyHandler is a helper method to define mock.On call
//   - scope config.Scope
//   - handler core.ConfigPropertyUpdateHandler
func (_e *MockConfigService_Expecter) RegisterPropertyHandler(scope interface{}, handler interface{}) *MockConfigService_RegisterPropertyHandler_Call {
	return &MockConfigService_RegisterPropertyHandler_Call{Call: _e.mock.On("RegisterPropertyHandler", scope, handler)}
}

func (_c *MockConfigService_RegisterPropertyHandler_Call) Run(run func(scope config.Scope, handler core.ConfigPropertyUpdateHandler)) *MockConfigService_RegisterPropertyHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Scope
		if args[0] != nil {
			arg0 = args[0].(config.Scope)
		}
		var arg1 core.ConfigPropertyUpdateHandler
		if args[1] != nil {
			arg1 = args[1].(core.ConfigPropertyUpdateHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigService_RegisterPropertyHandler_Call) Return() *MockConfigService_RegisterPropertyHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigService_RegisterPropertyHandler_Call) RunAndReturn(run func(scope config.Scope, handler core.ConfigPropertyUpdateHandler)) *MockConfigService_RegisterPropertyHandler_Call {
	_c.Run(run)
	return _c
}
