// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/core"
)

// NewMockContentScanner creates a new instance of MockContentScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentScanner {
	mock := &MockContentScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentScanner is an autogenerated mock type for the ContentScanner type
type MockContentScanner struct {
	mock.Mock
}

type MockContentScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentScanner) EXPECT() *MockContentScanner_Expecter {
	return &MockContentScanner_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type MockContentScanner
func (_mock *MockContentScanner) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContentScanner_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockContentScanner_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockContentScanner_Expecter) ID() *MockContentScanner_ID_Call {
	return &MockContentScanner_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockContentScanner_ID_Call) Run(run func()) *MockContentScanner_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContentScanner_ID_Call) Return(s string) *MockContentScanner_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContentScanner_ID_Call) RunAndReturn(run func() string) *MockContentScanner_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockContentScanner
func (_mock *MockContentScanner) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContentScanner_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockContentScanner_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockContentScanner_Expecter) Name() *MockContentScanner_Name_Call {
	return &MockContentScanner_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockContentScanner_Name_Call) Run(run func()) *MockContentScanner_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContentScanner_Name_Call) Return(s string) *MockContentScanner_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContentScanner_Name_Call) RunAndReturn(run func() string) *MockContentScanner_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Priority provides a mock function for the type MockContentScanner
func (_mock *MockContentScanner) Priority() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Priority")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockContentScanner_Priority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Priority'
type MockContentScanner_Priority_Call struct {
	*mock.Call
}

// Priority is a helper method to define mock.On call
func (_e *MockContentScanner_Expecter) Priority() *MockContentScanner_Priority_Call {
	return &MockContentScanner_Priority_Call{Call: _e.mock.On("Priority")}
}

func (_c *MockContentScanner_Priority_Call) Run(run func()) *MockContentScanner_Priority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContentScanner_Priority_Call) Return(n int) *MockContentScanner_Priority_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockContentScanner_Priority_Call) RunAndReturn(run func() int) *MockContentScanner_Priority_Call {
	_c.Call.Return(run)
	return _c
}

// ScanContent provides a mock function for the type MockContentScanner
func (_mock *MockContentScanner) ScanContent(ctx context.Context, hash core.StorageHash) (*core.ScanResult, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for ScanContent")
	}

	var r0 *core.ScanResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageHash) (*core.ScanResult, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageHash) *core.ScanResult); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ScanResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.StorageHash) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentScanner_ScanContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanContent'
type MockContentScanner_ScanContent_Call struct {
	*mock.Call
}

// ScanContent is a helper method to define mock.On call
//   - ctx context.Context
//   - hash core.StorageHash
func (_e *MockContentScanner_Expecter) ScanContent(ctx any, hash any) *MockContentScanner_ScanContent_Call {
	return &MockContentScanner_ScanContent_Call{Call: _e.mock.On("ScanContent", ctx, hash)}
}

func (_c *MockContentScanner_ScanContent_Call) Run(run func(ctx context.Context, hash core.StorageHash)) *MockContentScanner_ScanContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageHash
		if args[1] != nil {
			arg1 = args[1].(core.StorageHash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentScanner_ScanContent_Call) Return(scanResult *core.ScanResult, err error) *MockContentScanner_ScanContent_Call {
	_c.Call.Return(scanResult, err)
	return _c
}

func (_c *MockContentScanner_ScanContent_Call) RunAndReturn(run func(ctx context.Context, hash core.StorageHash) (*core.ScanResult, error)) *MockContentScanner_ScanContent_Call {
	_c.Call.Return(run)
	return _c
}
