// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/gookit/event"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// NewMockContext creates a new instance of MockContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContext {
	mock := &MockContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContext is an autogenerated mock type for the Context type
type MockContext struct {
	mock.Mock
}

type MockContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContext) EXPECT() *MockContext_Expecter {
	return &MockContext_Expecter{mock: &_m.Mock}
}

// APILogger provides a mock function for the type MockContext
func (_mock *MockContext) APILogger(api core.API) *core.Logger {
	ret := _mock.Called(api)

	if len(ret) == 0 {
		panic("no return value specified for APILogger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func(core.API) *core.Logger); ok {
		r0 = returnFunc(api)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockContext_APILogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'APILogger'
type MockContext_APILogger_Call struct {
	*mock.Call
}

// APILogger is a helper method to define mock.On call
//   - api core.API
func (_e *MockContext_Expecter) APILogger(api interface{}) *MockContext_APILogger_Call {
	return &MockContext_APILogger_Call{Call: _e.mock.On("APILogger", api)}
}

func (_c *MockContext_APILogger_Call) Run(run func(api core.API)) *MockContext_APILogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.API
		if args[0] != nil {
			arg0 = args[0].(core.API)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_APILogger_Call) Return(logger *core.Logger) *MockContext_APILogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockContext_APILogger_Call) RunAndReturn(run func(api core.API) *core.Logger) *MockContext_APILogger_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function for the type MockContext
func (_mock *MockContext) Cancel() {
	_mock.Called()
	return
}

// MockContext_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockContext_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
func (_e *MockContext_Expecter) Cancel() *MockContext_Cancel_Call {
	return &MockContext_Cancel_Call{Call: _e.mock.On("Cancel")}
}

func (_c *MockContext_Cancel_Call) Run(run func()) *MockContext_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Cancel_Call) Return() *MockContext_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Cancel_Call) RunAndReturn(run func()) *MockContext_Cancel_Call {
	_c.Run(run)
	return _c
}

// Config provides a mock function for the type MockContext
func (_mock *MockContext) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockContext_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockContext_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockContext_Expecter) Config() *MockContext_Config_Call {
	return &MockContext_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockContext_Config_Call) Run(run func()) *MockContext_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Config_Call) Return(manager config.Manager) *MockContext_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockContext_Config_Call) RunAndReturn(run func() config.Manager) *MockContext_Config_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockContext
func (_mock *MockContext) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockContext_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockContext_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockContext_Expecter) DB() *MockContext_DB_Call {
	return &MockContext_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockContext_DB_Call) Run(run func()) *MockContext_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_DB_Call) Return(dB *gorm.DB) *MockContext_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockContext_DB_Call) RunAndReturn(run func() *gorm.DB) *MockContext_DB_Call {
	_c.Call.Return(run)
	return _c
}

// Deadline provides a mock function for the type MockContext
func (_mock *MockContext) Deadline() (time.Time, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Deadline")
	}

	var r0 time.Time
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (time.Time, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockContext_Deadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deadline'
type MockContext_Deadline_Call struct {
	*mock.Call
}

// Deadline is a helper method to define mock.On call
func (_e *MockContext_Expecter) Deadline() *MockContext_Deadline_Call {
	return &MockContext_Deadline_Call{Call: _e.mock.On("Deadline")}
}

func (_c *MockContext_Deadline_Call) Run(run func()) *MockContext_Deadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Deadline_Call) Return(deadline time.Time, ok bool) *MockContext_Deadline_Call {
	_c.Call.Return(deadline, ok)
	return _c
}

func (_c *MockContext_Deadline_Call) RunAndReturn(run func() (time.Time, bool)) *MockContext_Deadline_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockContext
func (_mock *MockContext) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockContext_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockContext_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockContext_Expecter) Done() *MockContext_Done_Call {
	return &MockContext_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockContext_Done_Call) Run(run func()) *MockContext_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Done_Call) Return(valCh <-chan struct{}) *MockContext_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockContext_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockContext_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockContext
func (_mock *MockContext) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockContext_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockContext_Expecter) Err() *MockContext_Err_Call {
	return &MockContext_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockContext_Err_Call) Run(run func()) *MockContext_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Err_Call) Return(err error) *MockContext_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Err_Call) RunAndReturn(run func() error) *MockContext_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Event provides a mock function for the type MockContext
func (_mock *MockContext) Event() *event.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Event")
	}

	var r0 *event.Manager
	if returnFunc, ok := ret.Get(0).(func() *event.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.Manager)
		}
	}
	return r0
}

// MockContext_Event_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Event'
type MockContext_Event_Call struct {
	*mock.Call
}

// Event is a helper method to define mock.On call
func (_e *MockContext_Expecter) Event() *MockContext_Event_Call {
	return &MockContext_Event_Call{Call: _e.mock.On("Event")}
}

func (_c *MockContext_Event_Call) Run(run func()) *MockContext_Event_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Event_Call) Return(manager *event.Manager) *MockContext_Event_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockContext_Event_Call) RunAndReturn(run func() *event.Manager) *MockContext_Event_Call {
	_c.Call.Return(run)
	return _c
}

// ExitCode provides a mock function for the type MockContext
func (_mock *MockContext) ExitCode() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExitCode")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockContext_ExitCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExitCode'
type MockContext_ExitCode_Call struct {
	*mock.Call
}

// ExitCode is a helper method to define mock.On call
func (_e *MockContext_Expecter) ExitCode() *MockContext_ExitCode_Call {
	return &MockContext_ExitCode_Call{Call: _e.mock.On("ExitCode")}
}

func (_c *MockContext_ExitCode_Call) Run(run func()) *MockContext_ExitCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ExitCode_Call) Return(n int) *MockContext_ExitCode_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockContext_ExitCode_Call) RunAndReturn(run func() int) *MockContext_ExitCode_Call {
	_c.Call.Return(run)
	return _c
}

// ExitFuncs provides a mock function for the type MockContext
func (_mock *MockContext) ExitFuncs() []func(core.Context) error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExitFuncs")
	}

	var r0 []func(core.Context) error
	if returnFunc, ok := ret.Get(0).(func() []func(core.Context) error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]func(core.Context) error)
		}
	}
	return r0
}

// MockContext_ExitFuncs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExitFuncs'
type MockContext_ExitFuncs_Call struct {
	*mock.Call
}

// ExitFuncs is a helper method to define mock.On call
func (_e *MockContext_Expecter) ExitFuncs() *MockContext_ExitFuncs_Call {
	return &MockContext_ExitFuncs_Call{Call: _e.mock.On("ExitFuncs")}
}

func (_c *MockContext_ExitFuncs_Call) Run(run func()) *MockContext_ExitFuncs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ExitFuncs_Call) Return(fns []func(core.Context) error) *MockContext_ExitFuncs_Call {
	_c.Call.Return(fns)
	return _c
}

func (_c *MockContext_ExitFuncs_Call) RunAndReturn(run func() []func(core.Context) error) *MockContext_ExitFuncs_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function for the type MockContext
func (_mock *MockContext) GetContext() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockContext_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockContext_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockContext_Expecter) GetContext() *MockContext_GetContext_Call {
	return &MockContext_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockContext_GetContext_Call) Run(run func()) *MockContext_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_GetContext_Call) Return(context1 context.Context) *MockContext_GetContext_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockContext_GetContext_Call) RunAndReturn(run func() context.Context) *MockContext_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockContext
func (_mock *MockContext) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockContext_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockContext_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockContext_Expecter) Logger() *MockContext_Logger_Call {
	return &MockContext_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockContext_Logger_Call) Run(run func()) *MockContext_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Logger_Call) Return(logger *core.Logger) *MockContext_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockContext_Logger_Call) RunAndReturn(run func() *core.Logger) *MockContext_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// NamedLogger provides a mock function for the type MockContext
func (_mock *MockContext) NamedLogger(name string) *core.Logger {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for NamedLogger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func(string) *core.Logger); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockContext_NamedLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamedLogger'
type MockContext_NamedLogger_Call struct {
	*mock.Call
}

// NamedLogger is a helper method to define mock.On call
//   - name string
func (_e *MockContext_Expecter) NamedLogger(name interface{}) *MockContext_NamedLogger_Call {
	return &MockContext_NamedLogger_Call{Call: _e.mock.On("NamedLogger", name)}
}

func (_c *MockContext_NamedLogger_Call) Run(run func(name string)) *MockContext_NamedLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_NamedLogger_Call) Return(logger *core.Logger) *MockContext_NamedLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockContext_NamedLogger_Call) RunAndReturn(run func(name string) *core.Logger) *MockContext_NamedLogger_Call {
	_c.Call.Return(run)
	return _c
}

// OnExit provides a mock function for the type MockContext
func (_mock *MockContext) OnExit(f core.LifecycleFunc) {
	_mock.Called(f)
	return
}

// MockContext_OnExit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnExit'
type MockContext_OnExit_Call struct {
	*mock.Call
}

// OnExit is a helper method to define mock.On call
//   - f core.LifecycleFunc
func (_e *MockContext_Expecter) OnExit(f interface{}) *MockContext_OnExit_Call {
	return &MockContext_OnExit_Call{Call: _e.mock.On("OnExit", f)}
}

func (_c *MockContext_OnExit_Call) Run(run func(f core.LifecycleFunc)) *MockContext_OnExit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.LifecycleFunc
		if args[0] != nil {
			arg0 = args[0].(core.LifecycleFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_OnExit_Call) Return() *MockContext_OnExit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_OnExit_Call) RunAndReturn(run func(f core.LifecycleFunc)) *MockContext_OnExit_Call {
	_c.Run(run)
	return _c
}

// OnStartup provides a mock function for the type MockContext
func (_mock *MockContext) OnStartup(f core.LifecycleFunc) {
	_mock.Called(f)
	return
}

// MockContext_OnStartup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStartup'
type MockContext_OnStartup_Call struct {
	*mock.Call
}

// OnStartup is a helper method to define mock.On call
//   - f core.LifecycleFunc
func (_e *MockContext_Expecter) OnStartup(f interface{}) *MockContext_OnStartup_Call {
	return &MockContext_OnStartup_Call{Call: _e.mock.On("OnStartup", f)}
}

func (_c *MockContext_OnStartup_Call) Run(run func(f core.LifecycleFunc)) *MockContext_OnStartup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.LifecycleFunc
		if args[0] != nil {
			arg0 = args[0].(core.LifecycleFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_OnStartup_Call) Return() *MockContext_OnStartup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_OnStartup_Call) RunAndReturn(run func(f core.LifecycleFunc)) *MockContext_OnStartup_Call {
	_c.Run(run)
	return _c
}

// ProtocolLogger provides a mock function for the type MockContext
func (_mock *MockContext) ProtocolLogger(protocol core.Protocol) *core.Logger {
	ret := _mock.Called(protocol)

	if len(ret) == 0 {
		panic("no return value specified for ProtocolLogger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func(core.Protocol) *core.Logger); ok {
		r0 = returnFunc(protocol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockContext_ProtocolLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProtocolLogger'
type MockContext_ProtocolLogger_Call struct {
	*mock.Call
}

// ProtocolLogger is a helper method to define mock.On call
//   - protocol core.Protocol
func (_e *MockContext_Expecter) ProtocolLogger(protocol interface{}) *MockContext_ProtocolLogger_Call {
	return &MockContext_ProtocolLogger_Call{Call: _e.mock.On("ProtocolLogger", protocol)}
}

func (_c *MockContext_ProtocolLogger_Call) Run(run func(protocol core.Protocol)) *MockContext_ProtocolLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Protocol
		if args[0] != nil {
			arg0 = args[0].(core.Protocol)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_ProtocolLogger_Call) Return(logger *core.Logger) *MockContext_ProtocolLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockContext_ProtocolLogger_Call) RunAndReturn(run func(protocol core.Protocol) *core.Logger) *MockContext_ProtocolLogger_Call {
	_c.Call.Return(run)
	return _c
}

// Service provides a mock function for the type MockContext
func (_mock *MockContext) Service(id string) any {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Service")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockContext_Service_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Service'
type MockContext_Service_Call struct {
	*mock.Call
}

// Service is a helper method to define mock.On call
//   - id string
func (_e *MockContext_Expecter) Service(id interface{}) *MockContext_Service_Call {
	return &MockContext_Service_Call{Call: _e.mock.On("Service", id)}
}

func (_c *MockContext_Service_Call) Run(run func(id string)) *MockContext_Service_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Service_Call) Return(v any) *MockContext_Service_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockContext_Service_Call) RunAndReturn(run func(id string) any) *MockContext_Service_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceLogger provides a mock function for the type MockContext
func (_mock *MockContext) ServiceLogger(service core.Service) *core.Logger {
	ret := _mock.Called(service)

	if len(ret) == 0 {
		panic("no return value specified for ServiceLogger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func(core.Service) *core.Logger); ok {
		r0 = returnFunc(service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockContext_ServiceLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceLogger'
type MockContext_ServiceLogger_Call struct {
	*mock.Call
}

// ServiceLogger is a helper method to define mock.On call
//   - service core.Service
func (_e *MockContext_Expecter) ServiceLogger(service interface{}) *MockContext_ServiceLogger_Call {
	return &MockContext_ServiceLogger_Call{Call: _e.mock.On("ServiceLogger", service)}
}

func (_c *MockContext_ServiceLogger_Call) Run(run func(service core.Service)) *MockContext_ServiceLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Service
		if args[0] != nil {
			arg0 = args[0].(core.Service)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_ServiceLogger_Call) Return(logger *core.Logger) *MockContext_ServiceLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockContext_ServiceLogger_Call) RunAndReturn(run func(service core.Service) *core.Logger) *MockContext_ServiceLogger_Call {
	_c.Call.Return(run)
	return _c
}

// SetExitCode provides a mock function for the type MockContext
func (_mock *MockContext) SetExitCode(code int) {
	_mock.Called(code)
	return
}

// MockContext_SetExitCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExitCode'
type MockContext_SetExitCode_Call struct {
	*mock.Call
}

// SetExitCode is a helper method to define mock.On call
//   - code int
func (_e *MockContext_Expecter) SetExitCode(code interface{}) *MockContext_SetExitCode_Call {
	return &MockContext_SetExitCode_Call{Call: _e.mock.On("SetExitCode", code)}
}

func (_c *MockContext_SetExitCode_Call) Run(run func(code int)) *MockContext_SetExitCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_SetExitCode_Call) Return() *MockContext_SetExitCode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_SetExitCode_Call) RunAndReturn(run func(code int)) *MockContext_SetExitCode_Call {
	_c.Run(run)
	return _c
}

// StartupFuncs provides a mock function for the type MockContext
func (_mock *MockContext) StartupFuncs() []func(core.Context) error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartupFuncs")
	}

	var r0 []func(core.Context) error
	if returnFunc, ok := ret.Get(0).(func() []func(core.Context) error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]func(core.Context) error)
		}
	}
	return r0
}

// MockContext_StartupFuncs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartupFuncs'
type MockContext_StartupFuncs_Call struct {
	*mock.Call
}

// StartupFuncs is a helper method to define mock.On call
func (_e *MockContext_Expecter) StartupFuncs() *MockContext_StartupFuncs_Call {
	return &MockContext_StartupFuncs_Call{Call: _e.mock.On("StartupFuncs")}
}

func (_c *MockContext_StartupFuncs_Call) Run(run func()) *MockContext_StartupFuncs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_StartupFuncs_Call) Return(fns []func(core.Context) error) *MockContext_StartupFuncs_Call {
	_c.Call.Return(fns)
	return _c
}

func (_c *MockContext_StartupFuncs_Call) RunAndReturn(run func() []func(core.Context) error) *MockContext_StartupFuncs_Call {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function for the type MockContext
func (_mock *MockContext) Value(key any) any {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(any) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockContext_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockContext_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
//   - key any
func (_e *MockContext_Expecter) Value(key interface{}) *MockContext_Value_Call {
	return &MockContext_Value_Call{Call: _e.mock.On("Value", key)}
}

func (_c *MockContext_Value_Call) Run(run func(key any)) *MockContext_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Value_Call) Return(v any) *MockContext_Value_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockContext_Value_Call) RunAndReturn(run func(key any) any) *MockContext_Value_Call {
	_c.Call.Return(run)
	return _c
}

// WithLogger provides a mock function for the type MockContext
func (_mock *MockContext) WithLogger(opts ...zap.Field) *core.Logger {
	// zap.Field
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithLogger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func(...zap.Field) *core.Logger); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockContext_WithLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLogger'
type MockContext_WithLogger_Call struct {
	*mock.Call
}

// WithLogger is a helper method to define mock.On call
//   - opts ...zap.Field
func (_e *MockContext_Expecter) WithLogger(opts ...interface{}) *MockContext_WithLogger_Call {
	return &MockContext_WithLogger_Call{Call: _e.mock.On("WithLogger",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockContext_WithLogger_Call) Run(run func(opts ...zap.Field)) *MockContext_WithLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []zap.Field
		variadicArgs := make([]zap.Field, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(zap.Field)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockContext_WithLogger_Call) Return(logger *core.Logger) *MockContext_WithLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockContext_WithLogger_Call) RunAndReturn(run func(opts ...zap.Field) *core.Logger) *MockContext_WithLogger_Call {
	_c.Call.Return(run)
	return _c
}

// WithLoggerLazy provides a mock function for the type MockContext
func (_mock *MockContext) WithLoggerLazy(opts ...zap.Field) *core.Logger {
	// zap.Field
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithLoggerLazy")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func(...zap.Field) *core.Logger); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockContext_WithLoggerLazy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLoggerLazy'
type MockContext_WithLoggerLazy_Call struct {
	*mock.Call
}

// WithLoggerLazy is a helper method to define mock.On call
//   - opts ...zap.Field
func (_e *MockContext_Expecter) WithLoggerLazy(opts ...interface{}) *MockContext_WithLoggerLazy_Call {
	return &MockContext_WithLoggerLazy_Call{Call: _e.mock.On("WithLoggerLazy",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockContext_WithLoggerLazy_Call) Run(run func(opts ...zap.Field)) *MockContext_WithLoggerLazy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []zap.Field
		variadicArgs := make([]zap.Field, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(zap.Field)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockContext_WithLoggerLazy_Call) Return(logger *core.Logger) *MockContext_WithLoggerLazy_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockContext_WithLoggerLazy_Call) RunAndReturn(run func(opts ...zap.Field) *core.Logger) *MockContext_WithLoggerLazy_Call {
	_c.Call.Return(run)
	return _c
}

// WithLoggerOptions provides a mock function for the type MockContext
func (_mock *MockContext) WithLoggerOptions(opts ...zap.Option) *core.Logger {
	// zap.Option
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithLoggerOptions")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func(...zap.Option) *core.Logger); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockContext_WithLoggerOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithLoggerOptions'
type MockContext_WithLoggerOptions_Call struct {
	*mock.Call
}

// WithLoggerOptions is a helper method to define mock.On call
//   - opts ...zap.Option
func (_e *MockContext_Expecter) WithLoggerOptions(opts ...interface{}) *MockContext_WithLoggerOptions_Call {
	return &MockContext_WithLoggerOptions_Call{Call: _e.mock.On("WithLoggerOptions",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockContext_WithLoggerOptions_Call) Run(run func(opts ...zap.Option)) *MockContext_WithLoggerOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []zap.Option
		variadicArgs := make([]zap.Option, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(zap.Option)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockContext_WithLoggerOptions_Call) Return(logger *core.Logger) *MockContext_WithLoggerOptions_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockContext_WithLoggerOptions_Call) RunAndReturn(run func(opts ...zap.Option) *core.Logger) *MockContext_WithLoggerOptions_Call {
	_c.Call.Return(run)
	return _c
}
