// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/go-co-op/gocron/v2"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/core"
)

// NewMockCronJob creates a new instance of MockCronJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCronJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCronJob {
	mock := &MockCronJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCronJob is an autogenerated mock type for the CronJob type
type MockCronJob struct {
	mock.Mock
}

type MockCronJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCronJob) EXPECT() *MockCronJob_Expecter {
	return &MockCronJob_Expecter{mock: &_m.Mock}
}

// Args provides a mock function for the type MockCronJob
func (_mock *MockCronJob) Args() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Args")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockCronJob_Args_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Args'
type MockCronJob_Args_Call struct {
	*mock.Call
}

// Args is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) Args() *MockCronJob_Args_Call {
	return &MockCronJob_Args_Call{Call: _e.mock.On("Args")}
}

func (_c *MockCronJob_Args_Call) Run(run func()) *MockCronJob_Args_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_Args_Call) Return(v any) *MockCronJob_Args_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCronJob_Args_Call) RunAndReturn(run func() any) *MockCronJob_Args_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function for the type MockCronJob
func (_mock *MockCronJob) DisplayName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCronJob_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockCronJob_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) DisplayName() *MockCronJob_DisplayName_Call {
	return &MockCronJob_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *MockCronJob_DisplayName_Call) Run(run func()) *MockCronJob_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_DisplayName_Call) Return(s string) *MockCronJob_DisplayName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCronJob_DisplayName_Call) RunAndReturn(run func() string) *MockCronJob_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockCronJob
func (_mock *MockCronJob) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockCronJob_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockCronJob_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) Done() *MockCronJob_Done_Call {
	return &MockCronJob_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockCronJob_Done_Call) Run(run func()) *MockCronJob_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_Done_Call) Return(valCh <-chan struct{}) *MockCronJob_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockCronJob_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockCronJob_Done_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockCronJob
func (_mock *MockCronJob) ID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockCronJob_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCronJob_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) ID() *MockCronJob_ID_Call {
	return &MockCronJob_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCronJob_ID_Call) Run(run func()) *MockCronJob_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_ID_Call) Return(uUID uuid.UUID) *MockCronJob_ID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockCronJob_ID_Call) RunAndReturn(run func() uuid.UUID) *MockCronJob_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Job provides a mock function for the type MockCronJob
func (_mock *MockCronJob) Job() gocron.Job {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Job")
	}

	var r0 gocron.Job
	if returnFunc, ok := ret.Get(0).(func() gocron.Job); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocron.Job)
		}
	}
	return r0
}

// MockCronJob_Job_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Job'
type MockCronJob_Job_Call struct {
	*mock.Call
}

// Job is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) Job() *MockCronJob_Job_Call {
	return &MockCronJob_Job_Call{Call: _e.mock.On("Job")}
}

func (_c *MockCronJob_Job_Call) Run(run func()) *MockCronJob_Job_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_Job_Call) Return(job gocron.Job) *MockCronJob_Job_Call {
	_c.Call.Return(job)
	return _c
}

func (_c *MockCronJob_Job_Call) RunAndReturn(run func() gocron.Job) *MockCronJob_Job_Call {
	_c.Call.Return(run)
	return _c
}

// Origin provides a mock function for the type MockCronJob
func (_mock *MockCronJob) Origin() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Origin")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCronJob_Origin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Origin'
type MockCronJob_Origin_Call struct {
	*mock.Call
}

// Origin is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) Origin() *MockCronJob_Origin_Call {
	return &MockCronJob_Origin_Call{Call: _e.mock.On("Origin")}
}

func (_c *MockCronJob_Origin_Call) Run(run func()) *MockCronJob_Origin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_Origin_Call) Return(s string) *MockCronJob_Origin_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCronJob_Origin_Call) RunAndReturn(run func() string) *MockCronJob_Origin_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockCronJob
func (_mock *MockCronJob) Run(ctx core.Context, eventCtx context.Context) error {
	ret := _mock.Called(ctx, eventCtx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(core.Context, context.Context) error); ok {
		r0 = returnFunc(ctx, eventCtx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCronJob_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCronJob_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx core.Context
//   - eventCtx context.Context
func (_e *MockCronJob_Expecter) Run(ctx interface{}, eventCtx interface{}) *MockCronJob_Run_Call {
	return &MockCronJob_Run_Call{Call: _e.mock.On("Run", ctx, eventCtx)}
}

func (_c *MockCronJob_Run_Call) Run(run func(ctx core.Context, eventCtx context.Context)) *MockCronJob_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		var arg1 context.Context
		if args[1] != nil {
			arg1 = args[1].(context.Context)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCronJob_Run_Call) Return(err error) *MockCronJob_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCronJob_Run_Call) RunAndReturn(run func(ctx core.Context, eventCtx context.Context) error) *MockCronJob_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Schedule provides a mock function for the type MockCronJob
func (_mock *MockCronJob) Schedule() *core.CronScheduleDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 *core.CronScheduleDefinition
	if returnFunc, ok := ret.Get(0).(func() *core.CronScheduleDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.CronScheduleDefinition)
		}
	}
	return r0
}

// MockCronJob_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type MockCronJob_Schedule_Call struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) Schedule() *MockCronJob_Schedule_Call {
	return &MockCronJob_Schedule_Call{Call: _e.mock.On("Schedule")}
}

func (_c *MockCronJob_Schedule_Call) Run(run func()) *MockCronJob_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_Schedule_Call) Return(cronScheduleDefinition *core.CronScheduleDefinition) *MockCronJob_Schedule_Call {
	_c.Call.Return(cronScheduleDefinition)
	return _c
}

func (_c *MockCronJob_Schedule_Call) RunAndReturn(run func() *core.CronScheduleDefinition) *MockCronJob_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// SetArgs provides a mock function for the type MockCronJob
func (_mock *MockCronJob) SetArgs(args any) {
	_mock.Called(args)
	return
}

// MockCronJob_SetArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetArgs'
type MockCronJob_SetArgs_Call struct {
	*mock.Call
}

// SetArgs is a helper method to define mock.On call
//   - args any
func (_e *MockCronJob_Expecter) SetArgs(args interface{}) *MockCronJob_SetArgs_Call {
	return &MockCronJob_SetArgs_Call{Call: _e.mock.On("SetArgs", args)}
}

func (_c *MockCronJob_SetArgs_Call) Run(run func(args any)) *MockCronJob_SetArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronJob_SetArgs_Call) Return() *MockCronJob_SetArgs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCronJob_SetArgs_Call) RunAndReturn(run func(args any)) *MockCronJob_SetArgs_Call {
	_c.Run(run)
	return _c
}

// SetDone provides a mock function for the type MockCronJob
func (_mock *MockCronJob) SetDone(done <-chan struct{}) {
	_mock.Called(done)
	return
}

// MockCronJob_SetDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDone'
type MockCronJob_SetDone_Call struct {
	*mock.Call
}

// SetDone is a helper method to define mock.On call
//   - done <-chan struct{}
func (_e *MockCronJob_Expecter) SetDone(done interface{}) *MockCronJob_SetDone_Call {
	return &MockCronJob_SetDone_Call{Call: _e.mock.On("SetDone", done)}
}

func (_c *MockCronJob_SetDone_Call) Run(run func(done <-chan struct{})) *MockCronJob_SetDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 <-chan struct{}
		if args[0] != nil {
			arg0 = args[0].(<-chan struct{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronJob_SetDone_Call) Return() *MockCronJob_SetDone_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCronJob_SetDone_Call) RunAndReturn(run func(done <-chan struct{})) *MockCronJob_SetDone_Call {
	_c.Run(run)
	return _c
}

// SetJob provides a mock function for the type MockCronJob
func (_mock *MockCronJob) SetJob(job gocron.Job) {
	_mock.Called(job)
	return
}

// MockCronJob_SetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJob'
type MockCronJob_SetJob_Call struct {
	*mock.Call
}

// SetJob is a helper method to define mock.On call
//   - job gocron.Job
func (_e *MockCronJob_Expecter) SetJob(job interface{}) *MockCronJob_SetJob_Call {
	return &MockCronJob_SetJob_Call{Call: _e.mock.On("SetJob", job)}
}

func (_c *MockCronJob_SetJob_Call) Run(run func(job gocron.Job)) *MockCronJob_SetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocron.Job
		if args[0] != nil {
			arg0 = args[0].(gocron.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronJob_SetJob_Call) Return() *MockCronJob_SetJob_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCronJob_SetJob_Call) RunAndReturn(run func(job gocron.Job)) *MockCronJob_SetJob_Call {
	_c.Run(run)
	return _c
}

// SetScheduledDefinition provides a mock function for the type MockCronJob
func (_mock *MockCronJob) SetScheduledDefinition(schedDef *core.CronScheduleDefinition) {
	_mock.Called(schedDef)
	return
}

// MockCronJob_SetScheduledDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetScheduledDefinition'
type MockCronJob_SetScheduledDefinition_Call struct {
	*mock.Call
}

// SetScheduledDefinition is a helper method to define mock.On call
//   - schedDef *core.CronScheduleDefinition
func (_e *MockCronJob_Expecter) SetScheduledDefinition(schedDef interface{}) *MockCronJob_SetScheduledDefinition_Call {
	return &MockCronJob_SetScheduledDefinition_Call{Call: _e.mock.On("SetScheduledDefinition", schedDef)}
}

func (_c *MockCronJob_SetScheduledDefinition_Call) Run(run func(schedDef *core.CronScheduleDefinition)) *MockCronJob_SetScheduledDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.CronScheduleDefinition
		if args[0] != nil {
			arg0 = args[0].(*core.CronScheduleDefinition)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronJob_SetScheduledDefinition_Call) Return() *MockCronJob_SetScheduledDefinition_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCronJob_SetScheduledDefinition_Call) RunAndReturn(run func(schedDef *core.CronScheduleDefinition)) *MockCronJob_SetScheduledDefinition_Call {
	_c.Run(run)
	return _c
}

// SourceID provides a mock function for the type MockCronJob
func (_mock *MockCronJob) SourceID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SourceID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCronJob_SourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceID'
type MockCronJob_SourceID_Call struct {
	*mock.Call
}

// SourceID is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) SourceID() *MockCronJob_SourceID_Call {
	return &MockCronJob_SourceID_Call{Call: _e.mock.On("SourceID")}
}

func (_c *MockCronJob_SourceID_Call) Run(run func()) *MockCronJob_SourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_SourceID_Call) Return(s string) *MockCronJob_SourceID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCronJob_SourceID_Call) RunAndReturn(run func() string) *MockCronJob_SourceID_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockCronJob
func (_mock *MockCronJob) Type() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCronJob_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockCronJob_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockCronJob_Expecter) Type() *MockCronJob_Type_Call {
	return &MockCronJob_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockCronJob_Type_Call) Run(run func()) *MockCronJob_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronJob_Type_Call) Return(s string) *MockCronJob_Type_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCronJob_Type_Call) RunAndReturn(run func() string) *MockCronJob_Type_Call {
	_c.Call.Return(run)
	return _c
}
