// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/go-co-op/gocron/v2"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/core"
)

// NewMockCronScheduleRegistry creates a new instance of MockCronScheduleRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCronScheduleRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCronScheduleRegistry {
	mock := &MockCronScheduleRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCronScheduleRegistry is an autogenerated mock type for the CronScheduleRegistry type
type MockCronScheduleRegistry struct {
	mock.Mock
}

type MockCronScheduleRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCronScheduleRegistry) EXPECT() *MockCronScheduleRegistry_Expecter {
	return &MockCronScheduleRegistry_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCronScheduleRegistry
func (_mock *MockCronScheduleRegistry) Create(def core.CronScheduleDefinition) (gocron.JobDefinition, error) {
	ret := _mock.Called(def)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 gocron.JobDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(core.CronScheduleDefinition) (gocron.JobDefinition, error)); ok {
		return returnFunc(def)
	}
	if returnFunc, ok := ret.Get(0).(func(core.CronScheduleDefinition) gocron.JobDefinition); ok {
		r0 = returnFunc(def)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocron.JobDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(core.CronScheduleDefinition) error); ok {
		r1 = returnFunc(def)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCronScheduleRegistry_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCronScheduleRegistry_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - def core.CronScheduleDefinition
func (_e *MockCronScheduleRegistry_Expecter) Create(def any) *MockCronScheduleRegistry_Create_Call {
	return &MockCronScheduleRegistry_Create_Call{Call: _e.mock.On("Create", def)}
}

func (_c *MockCronScheduleRegistry_Create_Call) Run(run func(def core.CronScheduleDefinition)) *MockCronScheduleRegistry_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.CronScheduleDefinition
		if args[0] != nil {
			arg0 = args[0].(core.CronScheduleDefinition)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronScheduleRegistry_Create_Call) Return(jobDefinition gocron.JobDefinition, err error) *MockCronScheduleRegistry_Create_Call {
	_c.Call.Return(jobDefinition, err)
	return _c
}

func (_c *MockCronScheduleRegistry_Create_Call) RunAndReturn(run func(def core.CronScheduleDefinition) (gocron.JobDefinition, error)) *MockCronScheduleRegistry_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegisteredTypes provides a mock function for the type MockCronScheduleRegistry
func (_mock *MockCronScheduleRegistry) GetRegisteredTypes() []core.CronScheduleType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRegisteredTypes")
	}

	var r0 []core.CronScheduleType
	if returnFunc, ok := ret.Get(0).(func() []core.CronScheduleType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.CronScheduleType)
		}
	}
	return r0
}

// MockCronScheduleRegistry_GetRegisteredTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegisteredTypes'
type MockCronScheduleRegistry_GetRegisteredTypes_Call struct {
	*mock.Call
}

// GetRegisteredTypes is a helper method to define mock.On call
func (_e *MockCronScheduleRegistry_Expecter) GetRegisteredTypes() *MockCronScheduleRegistry_GetRegisteredTypes_Call {
	return &MockCronScheduleRegistry_GetRegisteredTypes_Call{Call: _e.mock.On("GetRegisteredTypes")}
}

func (_c *MockCronScheduleRegistry_GetRegisteredTypes_Call) Run(run func()) *MockCronScheduleRegistry_GetRegisteredTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronScheduleRegistry_GetRegisteredTypes_Call) Return(cronScheduleTypes []core.CronScheduleType) *MockCronScheduleRegistry_GetRegisteredTypes_Call {
	_c.Call.Return(cronScheduleTypes)
	return _c
}

func (_c *MockCronScheduleRegistry_GetRegisteredTypes_Call) RunAndReturn(run func() []core.CronScheduleType) *MockCronScheduleRegistry_GetRegisteredTypes_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockCronScheduleRegistry
func (_mock *MockCronScheduleRegistry) Register(schedType core.CronScheduleType, factory core.ScheduleFactoryFunc) {
	_mock.Called(schedType, factory)
	return
}

// MockCronScheduleRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockCronScheduleRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - schedType core.CronScheduleType
//   - factory core.ScheduleFactoryFunc
func (_e *MockCronScheduleRegistry_Expecter) Register(schedType any, factory any) *MockCronScheduleRegistry_Register_Call {
	return &MockCronScheduleRegistry_Register_Call{Call: _e.mock.On("Register", schedType, factory)}
}

func (_c *MockCronScheduleRegistry_Register_Call) Run(run func(schedType core.CronScheduleType, factory core.ScheduleFactoryFunc)) *MockCronScheduleRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.CronScheduleType
		if args[0] != nil {
			arg0 = args[0].(core.CronScheduleType)
		}
		var arg1 core.ScheduleFactoryFunc
		if args[1] != nil {
			arg1 = args[1].(core.ScheduleFactoryFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCronScheduleRegistry_Register_Call) Return() *MockCronScheduleRegistry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCronScheduleRegistry_Register_Call) RunAndReturn(run func(schedType core.CronScheduleType, factory core.ScheduleFactoryFunc)) *MockCronScheduleRegistry_Register_Call {
	_c.Run(run)
	return _c
}

// Validate provides a mock function for the type MockCronScheduleRegistry
func (_mock *MockCronScheduleRegistry) Validate(def core.CronScheduleDefinition) error {
	ret := _mock.Called(def)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(core.CronScheduleDefinition) error); ok {
		r0 = returnFunc(def)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCronScheduleRegistry_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockCronScheduleRegistry_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - def core.CronScheduleDefinition
func (_e *MockCronScheduleRegistry_Expecter) Validate(def any) *MockCronScheduleRegistry_Validate_Call {
	return &MockCronScheduleRegistry_Validate_Call{Call: _e.mock.On("Validate", def)}
}

func (_c *MockCronScheduleRegistry_Validate_Call) Run(run func(def core.CronScheduleDefinition)) *MockCronScheduleRegistry_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.CronScheduleDefinition
		if args[0] != nil {
			arg0 = args[0].(core.CronScheduleDefinition)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronScheduleRegistry_Validate_Call) Return(err error) *MockCronScheduleRegistry_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCronScheduleRegistry_Validate_Call) RunAndReturn(run func(def core.CronScheduleDefinition) error) *MockCronScheduleRegistry_Validate_Call {
	_c.Call.Return(run)
	return _c
}
