// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/core"
)

// NewMockCronService creates a new instance of MockCronService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCronService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCronService {
	mock := &MockCronService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCronService is an autogenerated mock type for the CronService type
type MockCronService struct {
	mock.Mock
}

type MockCronService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCronService) EXPECT() *MockCronService_Expecter {
	return &MockCronService_Expecter{mock: &_m.Mock}
}

// Coordinator provides a mock function for the type MockCronService
func (_mock *MockCronService) Coordinator() core.CronCoordinator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Coordinator")
	}

	var r0 core.CronCoordinator
	if returnFunc, ok := ret.Get(0).(func() core.CronCoordinator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.CronCoordinator)
		}
	}
	return r0
}

// MockCronService_Coordinator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Coordinator'
type MockCronService_Coordinator_Call struct {
	*mock.Call
}

// Coordinator is a helper method to define mock.On call
func (_e *MockCronService_Expecter) Coordinator() *MockCronService_Coordinator_Call {
	return &MockCronService_Coordinator_Call{Call: _e.mock.On("Coordinator")}
}

func (_c *MockCronService_Coordinator_Call) Run(run func()) *MockCronService_Coordinator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronService_Coordinator_Call) Return(cronCoordinator core.CronCoordinator) *MockCronService_Coordinator_Call {
	_c.Call.Return(cronCoordinator)
	return _c
}

func (_c *MockCronService_Coordinator_Call) RunAndReturn(run func() core.CronCoordinator) *MockCronService_Coordinator_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveJob provides a mock function for the type MockCronService
func (_mock *MockCronService) GetActiveJob(jobID uuid.UUID) (core.CronJob, bool, error) {
	ret := _mock.Called(jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveJob")
	}

	var r0 core.CronJob
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (core.CronJob, bool, error)); ok {
		return returnFunc(jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) core.CronJob); ok {
		r0 = returnFunc(jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.CronJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) bool); ok {
		r1 = returnFunc(jobID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID) error); ok {
		r2 = returnFunc(jobID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCronService_GetActiveJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveJob'
type MockCronService_GetActiveJob_Call struct {
	*mock.Call
}

// GetActiveJob is a helper method to define mock.On call
//   - jobID uuid.UUID
func (_e *MockCronService_Expecter) GetActiveJob(jobID interface{}) *MockCronService_GetActiveJob_Call {
	return &MockCronService_GetActiveJob_Call{Call: _e.mock.On("GetActiveJob", jobID)}
}

func (_c *MockCronService_GetActiveJob_Call) Run(run func(jobID uuid.UUID)) *MockCronService_GetActiveJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronService_GetActiveJob_Call) Return(cronJob core.CronJob, b bool, err error) *MockCronService_GetActiveJob_Call {
	_c.Call.Return(cronJob, b, err)
	return _c
}

func (_c *MockCronService_GetActiveJob_Call) RunAndReturn(run func(jobID uuid.UUID) (core.CronJob, bool, error)) *MockCronService_GetActiveJob_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockCronService
func (_mock *MockCronService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCronService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCronService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCronService_Expecter) ID() *MockCronService_ID_Call {
	return &MockCronService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCronService_ID_Call) Run(run func()) *MockCronService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronService_ID_Call) Return(s string) *MockCronService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCronService_ID_Call) RunAndReturn(run func() string) *MockCronService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// JobFactory provides a mock function for the type MockCronService
func (_mock *MockCronService) JobFactory() core.CronJobFactory {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JobFactory")
	}

	var r0 core.CronJobFactory
	if returnFunc, ok := ret.Get(0).(func() core.CronJobFactory); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.CronJobFactory)
		}
	}
	return r0
}

// MockCronService_JobFactory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobFactory'
type MockCronService_JobFactory_Call struct {
	*mock.Call
}

// JobFactory is a helper method to define mock.On call
func (_e *MockCronService_Expecter) JobFactory() *MockCronService_JobFactory_Call {
	return &MockCronService_JobFactory_Call{Call: _e.mock.On("JobFactory")}
}

func (_c *MockCronService_JobFactory_Call) Run(run func()) *MockCronService_JobFactory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronService_JobFactory_Call) Return(cronJobFactory core.CronJobFactory) *MockCronService_JobFactory_Call {
	_c.Call.Return(cronJobFactory)
	return _c
}

func (_c *MockCronService_JobFactory_Call) RunAndReturn(run func() core.CronJobFactory) *MockCronService_JobFactory_Call {
	_c.Call.Return(run)
	return _c
}

// Monitor provides a mock function for the type MockCronService
func (_mock *MockCronService) Monitor() core.CronMonitor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Monitor")
	}

	var r0 core.CronMonitor
	if returnFunc, ok := ret.Get(0).(func() core.CronMonitor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.CronMonitor)
		}
	}
	return r0
}

// MockCronService_Monitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Monitor'
type MockCronService_Monitor_Call struct {
	*mock.Call
}

// Monitor is a helper method to define mock.On call
func (_e *MockCronService_Expecter) Monitor() *MockCronService_Monitor_Call {
	return &MockCronService_Monitor_Call{Call: _e.mock.On("Monitor")}
}

func (_c *MockCronService_Monitor_Call) Run(run func()) *MockCronService_Monitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronService_Monitor_Call) Return(cronMonitor core.CronMonitor) *MockCronService_Monitor_Call {
	_c.Call.Return(cronMonitor)
	return _c
}

func (_c *MockCronService_Monitor_Call) RunAndReturn(run func() core.CronMonitor) *MockCronService_Monitor_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterEntity provides a mock function for the type MockCronService
func (_mock *MockCronService) RegisterEntity(entity core.Cronable) {
	_mock.Called(entity)
	return
}

// MockCronService_RegisterEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterEntity'
type MockCronService_RegisterEntity_Call struct {
	*mock.Call
}

// RegisterEntity is a helper method to define mock.On call
//   - entity core.Cronable
func (_e *MockCronService_Expecter) RegisterEntity(entity interface{}) *MockCronService_RegisterEntity_Call {
	return &MockCronService_RegisterEntity_Call{Call: _e.mock.On("RegisterEntity", entity)}
}

func (_c *MockCronService_RegisterEntity_Call) Run(run func(entity core.Cronable)) *MockCronService_RegisterEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Cronable
		if args[0] != nil {
			arg0 = args[0].(core.Cronable)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronService_RegisterEntity_Call) Return() *MockCronService_RegisterEntity_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCronService_RegisterEntity_Call) RunAndReturn(run func(entity core.Cronable)) *MockCronService_RegisterEntity_Call {
	_c.Run(run)
	return _c
}

// RegisterJob provides a mock function for the type MockCronService
func (_mock *MockCronService) RegisterJob(job core.CronJob) error {
	ret := _mock.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for RegisterJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(core.CronJob) error); ok {
		r0 = returnFunc(job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCronService_RegisterJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterJob'
type MockCronService_RegisterJob_Call struct {
	*mock.Call
}

// RegisterJob is a helper method to define mock.On call
//   - job core.CronJob
func (_e *MockCronService_Expecter) RegisterJob(job interface{}) *MockCronService_RegisterJob_Call {
	return &MockCronService_RegisterJob_Call{Call: _e.mock.On("RegisterJob", job)}
}

func (_c *MockCronService_RegisterJob_Call) Run(run func(job core.CronJob)) *MockCronService_RegisterJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.CronJob
		if args[0] != nil {
			arg0 = args[0].(core.CronJob)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronService_RegisterJob_Call) Return(err error) *MockCronService_RegisterJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCronService_RegisterJob_Call) RunAndReturn(run func(job core.CronJob) error) *MockCronService_RegisterJob_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterJobType provides a mock function for the type MockCronService
func (_mock *MockCronService) RegisterJobType(jobType string, factory core.CronJobFactoryFunc, defaultSchedule *core.CronScheduleDefinition) error {
	ret := _mock.Called(jobType, factory, defaultSchedule)

	if len(ret) == 0 {
		panic("no return value specified for RegisterJobType")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, core.CronJobFactoryFunc, *core.CronScheduleDefinition) error); ok {
		r0 = returnFunc(jobType, factory, defaultSchedule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCronService_RegisterJobType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterJobType'
type MockCronService_RegisterJobType_Call struct {
	*mock.Call
}

// RegisterJobType is a helper method to define mock.On call
//   - jobType string
//   - factory core.CronJobFactoryFunc
//   - defaultSchedule *core.CronScheduleDefinition
func (_e *MockCronService_Expecter) RegisterJobType(jobType interface{}, factory interface{}, defaultSchedule interface{}) *MockCronService_RegisterJobType_Call {
	return &MockCronService_RegisterJobType_Call{Call: _e.mock.On("RegisterJobType", jobType, factory, defaultSchedule)}
}

func (_c *MockCronService_RegisterJobType_Call) Run(run func(jobType string, factory core.CronJobFactoryFunc, defaultSchedule *core.CronScheduleDefinition)) *MockCronService_RegisterJobType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 core.CronJobFactoryFunc
		if args[1] != nil {
			arg1 = args[1].(core.CronJobFactoryFunc)
		}
		var arg2 *core.CronScheduleDefinition
		if args[2] != nil {
			arg2 = args[2].(*core.CronScheduleDefinition)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCronService_RegisterJobType_Call) Return(err error) *MockCronService_RegisterJobType_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCronService_RegisterJobType_Call) RunAndReturn(run func(jobType string, factory core.CronJobFactoryFunc, defaultSchedule *core.CronScheduleDefinition) error) *MockCronService_RegisterJobType_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterPluginJobs provides a mock function for the type MockCronService
func (_mock *MockCronService) RegisterPluginJobs(plugin core.PluginInfo) error {
	ret := _mock.Called(plugin)

	if len(ret) == 0 {
		panic("no return value specified for RegisterPluginJobs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(core.PluginInfo) error); ok {
		r0 = returnFunc(plugin)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCronService_RegisterPluginJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPluginJobs'
type MockCronService_RegisterPluginJobs_Call struct {
	*mock.Call
}

// RegisterPluginJobs is a helper method to define mock.On call
//   - plugin core.PluginInfo
func (_e *MockCronService_Expecter) RegisterPluginJobs(plugin interface{}) *MockCronService_RegisterPluginJobs_Call {
	return &MockCronService_RegisterPluginJobs_Call{Call: _e.mock.On("RegisterPluginJobs", plugin)}
}

func (_c *MockCronService_RegisterPluginJobs_Call) Run(run func(plugin core.PluginInfo)) *MockCronService_RegisterPluginJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.PluginInfo
		if args[0] != nil {
			arg0 = args[0].(core.PluginInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronService_RegisterPluginJobs_Call) Return(err error) *MockCronService_RegisterPluginJobs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCronService_RegisterPluginJobs_Call) RunAndReturn(run func(plugin core.PluginInfo) error) *MockCronService_RegisterPluginJobs_Call {
	_c.Call.Return(run)
	return _c
}

// RunJob provides a mock function for the type MockCronService
func (_mock *MockCronService) RunJob(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RunJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCronService_RunJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunJob'
type MockCronService_RunJob_Call struct {
	*mock.Call
}

// RunJob is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockCronService_Expecter) RunJob(id interface{}) *MockCronService_RunJob_Call {
	return &MockCronService_RunJob_Call{Call: _e.mock.On("RunJob", id)}
}

func (_c *MockCronService_RunJob_Call) Run(run func(id uuid.UUID)) *MockCronService_RunJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCronService_RunJob_Call) Return(err error) *MockCronService_RunJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCronService_RunJob_Call) RunAndReturn(run func(id uuid.UUID) error) *MockCronService_RunJob_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleRegistry provides a mock function for the type MockCronService
func (_mock *MockCronService) ScheduleRegistry() core.CronScheduleRegistry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScheduleRegistry")
	}

	var r0 core.CronScheduleRegistry
	if returnFunc, ok := ret.Get(0).(func() core.CronScheduleRegistry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.CronScheduleRegistry)
		}
	}
	return r0
}

// MockCronService_ScheduleRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleRegistry'
type MockCronService_ScheduleRegistry_Call struct {
	*mock.Call
}

// ScheduleRegistry is a helper method to define mock.On call
func (_e *MockCronService_Expecter) ScheduleRegistry() *MockCronService_ScheduleRegistry_Call {
	return &MockCronService_ScheduleRegistry_Call{Call: _e.mock.On("ScheduleRegistry")}
}

func (_c *MockCronService_ScheduleRegistry_Call) Run(run func()) *MockCronService_ScheduleRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronService_ScheduleRegistry_Call) Return(cronScheduleRegistry core.CronScheduleRegistry) *MockCronService_ScheduleRegistry_Call {
	_c.Call.Return(cronScheduleRegistry)
	return _c
}

func (_c *MockCronService_ScheduleRegistry_Call) RunAndReturn(run func() core.CronScheduleRegistry) *MockCronService_ScheduleRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockCronService
func (_mock *MockCronService) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCronService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCronService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockCronService_Expecter) Start() *MockCronService_Start_Call {
	return &MockCronService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockCronService_Start_Call) Run(run func()) *MockCronService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronService_Start_Call) Return(err error) *MockCronService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCronService_Start_Call) RunAndReturn(run func() error) *MockCronService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StateMachine provides a mock function for the type MockCronService
func (_mock *MockCronService) StateMachine() core.CronJobStateMachine {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StateMachine")
	}

	var r0 core.CronJobStateMachine
	if returnFunc, ok := ret.Get(0).(func() core.CronJobStateMachine); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.CronJobStateMachine)
		}
	}
	return r0
}

// MockCronService_StateMachine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StateMachine'
type MockCronService_StateMachine_Call struct {
	*mock.Call
}

// StateMachine is a helper method to define mock.On call
func (_e *MockCronService_Expecter) StateMachine() *MockCronService_StateMachine_Call {
	return &MockCronService_StateMachine_Call{Call: _e.mock.On("StateMachine")}
}

func (_c *MockCronService_StateMachine_Call) Run(run func()) *MockCronService_StateMachine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronService_StateMachine_Call) Return(cronJobStateMachine core.CronJobStateMachine) *MockCronService_StateMachine_Call {
	_c.Call.Return(cronJobStateMachine)
	return _c
}

func (_c *MockCronService_StateMachine_Call) RunAndReturn(run func() core.CronJobStateMachine) *MockCronService_StateMachine_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockCronService
func (_mock *MockCronService) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCronService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockCronService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockCronService_Expecter) Stop() *MockCronService_Stop_Call {
	return &MockCronService_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockCronService_Stop_Call) Run(run func()) *MockCronService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCronService_Stop_Call) Return(err error) *MockCronService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCronService_Stop_Call) RunAndReturn(run func() error) *MockCronService_Stop_Call {
	_c.Call.Return(run)
	return _c
}
