// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHashProofProvider creates a new instance of MockHashProofProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashProofProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashProofProvider {
	mock := &MockHashProofProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHashProofProvider is an autogenerated mock type for the HashProofProvider type
type MockHashProofProvider struct {
	mock.Mock
}

type MockHashProofProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashProofProvider) EXPECT() *MockHashProofProvider_Expecter {
	return &MockHashProofProvider_Expecter{mock: &_m.Mock}
}

// SetProof provides a mock function for the type MockHashProofProvider
func (_mock *MockHashProofProvider) SetProof(proof []byte) error {
	ret := _mock.Called(proof)

	if len(ret) == 0 {
		panic("no return value specified for SetProof")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(proof)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHashProofProvider_SetProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProof'
type MockHashProofProvider_SetProof_Call struct {
	*mock.Call
}

// SetProof is a helper method to define mock.On call
//   - proof []byte
func (_e *MockHashProofProvider_Expecter) SetProof(proof any) *MockHashProofProvider_SetProof_Call {
	return &MockHashProofProvider_SetProof_Call{Call: _e.mock.On("SetProof", proof)}
}

func (_c *MockHashProofProvider_SetProof_Call) Run(run func(proof []byte)) *MockHashProofProvider_SetProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHashProofProvider_SetProof_Call) Return(err error) *MockHashProofProvider_SetProof_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHashProofProvider_SetProof_Call) RunAndReturn(run func(proof []byte) error) *MockHashProofProvider_SetProof_Call {
	_c.Call.Return(run)
	return _c
}
