// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	core "go.lumeweb.com/portal/core"
)

// MockMailerService is an autogenerated mock type for the MailerService type
type MockMailerService struct {
	mock.Mock
}

type MockMailerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailerService) EXPECT() *MockMailerService_Expecter {
	return &MockMailerService_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with no fields
func (_m *MockMailerService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMailerService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockMailerService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockMailerService_Expecter) ID() *MockMailerService_ID_Call {
	return &MockMailerService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockMailerService_ID_Call) Run(run func()) *MockMailerService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMailerService_ID_Call) Return(_a0 string) *MockMailerService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailerService_ID_Call) RunAndReturn(run func() string) *MockMailerService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// TemplateRegister provides a mock function with given fields: name, template
func (_m *MockMailerService) TemplateRegister(name string, template core.MailerTemplate) error {
	ret := _m.Called(name, template)

	if len(ret) == 0 {
		panic("no return value specified for TemplateRegister")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, core.MailerTemplate) error); ok {
		r0 = rf(name, template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailerService_TemplateRegister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TemplateRegister'
type MockMailerService_TemplateRegister_Call struct {
	*mock.Call
}

// TemplateRegister is a helper method to define mock.On call
//   - name string
//   - template core.MailerTemplate
func (_e *MockMailerService_Expecter) TemplateRegister(name interface{}, template interface{}) *MockMailerService_TemplateRegister_Call {
	return &MockMailerService_TemplateRegister_Call{Call: _e.mock.On("TemplateRegister", name, template)}
}

func (_c *MockMailerService_TemplateRegister_Call) Run(run func(name string, template core.MailerTemplate)) *MockMailerService_TemplateRegister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(core.MailerTemplate))
	})
	return _c
}

func (_c *MockMailerService_TemplateRegister_Call) Return(_a0 error) *MockMailerService_TemplateRegister_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailerService_TemplateRegister_Call) RunAndReturn(run func(string, core.MailerTemplate) error) *MockMailerService_TemplateRegister_Call {
	_c.Call.Return(run)
	return _c
}

// TemplateSend provides a mock function with given fields: template, subjectVars, bodyVars, to
func (_m *MockMailerService) TemplateSend(template string, subjectVars core.MailerTemplateData, bodyVars core.MailerTemplateData, to string) error {
	ret := _m.Called(template, subjectVars, bodyVars, to)

	if len(ret) == 0 {
		panic("no return value specified for TemplateSend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, core.MailerTemplateData, core.MailerTemplateData, string) error); ok {
		r0 = rf(template, subjectVars, bodyVars, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailerService_TemplateSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TemplateSend'
type MockMailerService_TemplateSend_Call struct {
	*mock.Call
}

// TemplateSend is a helper method to define mock.On call
//   - template string
//   - subjectVars core.MailerTemplateData
//   - bodyVars core.MailerTemplateData
//   - to string
func (_e *MockMailerService_Expecter) TemplateSend(template interface{}, subjectVars interface{}, bodyVars interface{}, to interface{}) *MockMailerService_TemplateSend_Call {
	return &MockMailerService_TemplateSend_Call{Call: _e.mock.On("TemplateSend", template, subjectVars, bodyVars, to)}
}

func (_c *MockMailerService_TemplateSend_Call) Run(run func(template string, subjectVars core.MailerTemplateData, bodyVars core.MailerTemplateData, to string)) *MockMailerService_TemplateSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(core.MailerTemplateData), args[2].(core.MailerTemplateData), args[3].(string))
	})
	return _c
}

func (_c *MockMailerService_TemplateSend_Call) Return(_a0 error) *MockMailerService_TemplateSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailerService_TemplateSend_Call) RunAndReturn(run func(string, core.MailerTemplateData, core.MailerTemplateData, string) error) *MockMailerService_TemplateSend_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailerService creates a new instance of MockMailerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailerService {
	mock := &MockMailerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
