// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockOTPService is an autogenerated mock type for the OTPService type
type MockOTPService struct {
	mock.Mock
}

type MockOTPService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPService) EXPECT() *MockOTPService_Expecter {
	return &MockOTPService_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with no fields
func (_m *MockOTPService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOTPService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockOTPService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockOTPService_Expecter) ID() *MockOTPService_ID_Call {
	return &MockOTPService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockOTPService_ID_Call) Run(run func()) *MockOTPService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOTPService_ID_Call) Return(_a0 string) *MockOTPService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPService_ID_Call) RunAndReturn(run func() string) *MockOTPService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// OTPDisable provides a mock function with given fields: userId
func (_m *MockOTPService) OTPDisable(userId uint) error {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for OTPDisable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPService_OTPDisable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTPDisable'
type MockOTPService_OTPDisable_Call struct {
	*mock.Call
}

// OTPDisable is a helper method to define mock.On call
//   - userId uint
func (_e *MockOTPService_Expecter) OTPDisable(userId interface{}) *MockOTPService_OTPDisable_Call {
	return &MockOTPService_OTPDisable_Call{Call: _e.mock.On("OTPDisable", userId)}
}

func (_c *MockOTPService_OTPDisable_Call) Run(run func(userId uint)) *MockOTPService_OTPDisable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOTPService_OTPDisable_Call) Return(_a0 error) *MockOTPService_OTPDisable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPService_OTPDisable_Call) RunAndReturn(run func(uint) error) *MockOTPService_OTPDisable_Call {
	_c.Call.Return(run)
	return _c
}

// OTPEnable provides a mock function with given fields: userId, code
func (_m *MockOTPService) OTPEnable(userId uint, code string) error {
	ret := _m.Called(userId, code)

	if len(ret) == 0 {
		panic("no return value specified for OTPEnable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(userId, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPService_OTPEnable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTPEnable'
type MockOTPService_OTPEnable_Call struct {
	*mock.Call
}

// OTPEnable is a helper method to define mock.On call
//   - userId uint
//   - code string
func (_e *MockOTPService_Expecter) OTPEnable(userId interface{}, code interface{}) *MockOTPService_OTPEnable_Call {
	return &MockOTPService_OTPEnable_Call{Call: _e.mock.On("OTPEnable", userId, code)}
}

func (_c *MockOTPService_OTPEnable_Call) Run(run func(userId uint, code string)) *MockOTPService_OTPEnable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockOTPService_OTPEnable_Call) Return(_a0 error) *MockOTPService_OTPEnable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPService_OTPEnable_Call) RunAndReturn(run func(uint, string) error) *MockOTPService_OTPEnable_Call {
	_c.Call.Return(run)
	return _c
}

// OTPGenerate provides a mock function with given fields: userId
func (_m *MockOTPService) OTPGenerate(userId uint) (string, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for OTPGenerate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (string, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOTPService_OTPGenerate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTPGenerate'
type MockOTPService_OTPGenerate_Call struct {
	*mock.Call
}

// OTPGenerate is a helper method to define mock.On call
//   - userId uint
func (_e *MockOTPService_Expecter) OTPGenerate(userId interface{}) *MockOTPService_OTPGenerate_Call {
	return &MockOTPService_OTPGenerate_Call{Call: _e.mock.On("OTPGenerate", userId)}
}

func (_c *MockOTPService_OTPGenerate_Call) Run(run func(userId uint)) *MockOTPService_OTPGenerate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOTPService_OTPGenerate_Call) Return(_a0 string, _a1 error) *MockOTPService_OTPGenerate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOTPService_OTPGenerate_Call) RunAndReturn(run func(uint) (string, error)) *MockOTPService_OTPGenerate_Call {
	_c.Call.Return(run)
	return _c
}

// OTPVerify provides a mock function with given fields: userId, code
func (_m *MockOTPService) OTPVerify(userId uint, code string) (bool, error) {
	ret := _m.Called(userId, code)

	if len(ret) == 0 {
		panic("no return value specified for OTPVerify")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) (bool, error)); ok {
		return rf(userId, code)
	}
	if rf, ok := ret.Get(0).(func(uint, string) bool); ok {
		r0 = rf(userId, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(userId, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOTPService_OTPVerify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OTPVerify'
type MockOTPService_OTPVerify_Call struct {
	*mock.Call
}

// OTPVerify is a helper method to define mock.On call
//   - userId uint
//   - code string
func (_e *MockOTPService_Expecter) OTPVerify(userId interface{}, code interface{}) *MockOTPService_OTPVerify_Call {
	return &MockOTPService_OTPVerify_Call{Call: _e.mock.On("OTPVerify", userId, code)}
}

func (_c *MockOTPService_OTPVerify_Call) Run(run func(userId uint, code string)) *MockOTPService_OTPVerify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockOTPService_OTPVerify_Call) Return(_a0 bool, _a1 error) *MockOTPService_OTPVerify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOTPService_OTPVerify_Call) RunAndReturn(run func(uint, string) (bool, error)) *MockOTPService_OTPVerify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOTPService creates a new instance of MockOTPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPService {
	mock := &MockOTPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
