// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockProtocolExportAccessController creates a new instance of MockProtocolExportAccessController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProtocolExportAccessController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProtocolExportAccessController {
	mock := &MockProtocolExportAccessController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProtocolExportAccessController is an autogenerated mock type for the ProtocolExportAccessController type
type MockProtocolExportAccessController struct {
	mock.Mock
}

type MockProtocolExportAccessController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProtocolExportAccessController) EXPECT() *MockProtocolExportAccessController_Expecter {
	return &MockProtocolExportAccessController_Expecter{mock: &_m.Mock}
}

// CanExportCID provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) CanExportCID(ctx context.Context, cidStr string) (bool, error) {
	ret := _mock.Called(ctx, cidStr)

	if len(ret) == 0 {
		panic("no return value specified for CanExportCID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, cidStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, cidStr)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cidStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProtocolExportAccessController_CanExportCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanExportCID'
type MockProtocolExportAccessController_CanExportCID_Call struct {
	*mock.Call
}

// CanExportCID is a helper method to define mock.On call
//   - ctx context.Context
//   - cidStr string
func (_e *MockProtocolExportAccessController_Expecter) CanExportCID(ctx interface{}, cidStr interface{}) *MockProtocolExportAccessController_CanExportCID_Call {
	return &MockProtocolExportAccessController_CanExportCID_Call{Call: _e.mock.On("CanExportCID", ctx, cidStr)}
}

func (_c *MockProtocolExportAccessController_CanExportCID_Call) Run(run func(ctx context.Context, cidStr string)) *MockProtocolExportAccessController_CanExportCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProtocolExportAccessController_CanExportCID_Call) Return(b bool, err error) *MockProtocolExportAccessController_CanExportCID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProtocolExportAccessController_CanExportCID_Call) RunAndReturn(run func(ctx context.Context, cidStr string) (bool, error)) *MockProtocolExportAccessController_CanExportCID_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockProtocolExportAccessController_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockProtocolExportAccessController_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) Config() *MockProtocolExportAccessController_Config_Call {
	return &MockProtocolExportAccessController_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockProtocolExportAccessController_Config_Call) Run(run func()) *MockProtocolExportAccessController_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_Config_Call) Return(manager config.Manager) *MockProtocolExportAccessController_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockProtocolExportAccessController_Config_Call) RunAndReturn(run func() config.Manager) *MockProtocolExportAccessController_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockProtocolExportAccessController_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockProtocolExportAccessController_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) Context() *MockProtocolExportAccessController_Context_Call {
	return &MockProtocolExportAccessController_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockProtocolExportAccessController_Context_Call) Run(run func()) *MockProtocolExportAccessController_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_Context_Call) Return(context1 core.Context) *MockProtocolExportAccessController_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockProtocolExportAccessController_Context_Call) RunAndReturn(run func() core.Context) *MockProtocolExportAccessController_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockProtocolExportAccessController_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockProtocolExportAccessController_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) DB() *MockProtocolExportAccessController_DB_Call {
	return &MockProtocolExportAccessController_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockProtocolExportAccessController_DB_Call) Run(run func()) *MockProtocolExportAccessController_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_DB_Call) Return(dB *gorm.DB) *MockProtocolExportAccessController_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockProtocolExportAccessController_DB_Call) RunAndReturn(run func() *gorm.DB) *MockProtocolExportAccessController_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) DisplayName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtocolExportAccessController_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockProtocolExportAccessController_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) DisplayName() *MockProtocolExportAccessController_DisplayName_Call {
	return &MockProtocolExportAccessController_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *MockProtocolExportAccessController_DisplayName_Call) Run(run func()) *MockProtocolExportAccessController_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_DisplayName_Call) Return(s string) *MockProtocolExportAccessController_DisplayName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtocolExportAccessController_DisplayName_Call) RunAndReturn(run func() string) *MockProtocolExportAccessController_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) GetConfig() config.ProtocolConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.ProtocolConfig
	if returnFunc, ok := ret.Get(0).(func() config.ProtocolConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ProtocolConfig)
		}
	}
	return r0
}

// MockProtocolExportAccessController_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockProtocolExportAccessController_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) GetConfig() *MockProtocolExportAccessController_GetConfig_Call {
	return &MockProtocolExportAccessController_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockProtocolExportAccessController_GetConfig_Call) Run(run func()) *MockProtocolExportAccessController_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_GetConfig_Call) Return(protocolConfig config.ProtocolConfig) *MockProtocolExportAccessController_GetConfig_Call {
	_c.Call.Return(protocolConfig)
	return _c
}

func (_c *MockProtocolExportAccessController_GetConfig_Call) RunAndReturn(run func() config.ProtocolConfig) *MockProtocolExportAccessController_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtocolExportAccessController_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockProtocolExportAccessController_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) ID() *MockProtocolExportAccessController_ID_Call {
	return &MockProtocolExportAccessController_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockProtocolExportAccessController_ID_Call) Run(run func()) *MockProtocolExportAccessController_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_ID_Call) Return(s string) *MockProtocolExportAccessController_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtocolExportAccessController_ID_Call) RunAndReturn(run func() string) *MockProtocolExportAccessController_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockProtocolExportAccessController_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockProtocolExportAccessController_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) Logger() *MockProtocolExportAccessController_Logger_Call {
	return &MockProtocolExportAccessController_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockProtocolExportAccessController_Logger_Call) Run(run func()) *MockProtocolExportAccessController_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_Logger_Call) Return(logger *core.Logger) *MockProtocolExportAccessController_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockProtocolExportAccessController_Logger_Call) RunAndReturn(run func() *core.Logger) *MockProtocolExportAccessController_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtocolExportAccessController_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProtocolExportAccessController_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) Name() *MockProtocolExportAccessController_Name_Call {
	return &MockProtocolExportAccessController_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProtocolExportAccessController_Name_Call) Run(run func()) *MockProtocolExportAccessController_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_Name_Call) Return(s string) *MockProtocolExportAccessController_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtocolExportAccessController_Name_Call) RunAndReturn(run func() string) *MockProtocolExportAccessController_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) Operations() []core.Operation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 []core.Operation
	if returnFunc, ok := ret.Get(0).(func() []core.Operation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Operation)
		}
	}
	return r0
}

// MockProtocolExportAccessController_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type MockProtocolExportAccessController_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) Operations() *MockProtocolExportAccessController_Operations_Call {
	return &MockProtocolExportAccessController_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *MockProtocolExportAccessController_Operations_Call) Run(run func()) *MockProtocolExportAccessController_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_Operations_Call) Return(operations []core.Operation) *MockProtocolExportAccessController_Operations_Call {
	_c.Call.Return(operations)
	return _c
}

func (_c *MockProtocolExportAccessController_Operations_Call) RunAndReturn(run func() []core.Operation) *MockProtocolExportAccessController_Operations_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockProtocolExportAccessController_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockProtocolExportAccessController_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockProtocolExportAccessController_Expecter) SetConfig(cfg interface{}) *MockProtocolExportAccessController_SetConfig_Call {
	return &MockProtocolExportAccessController_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockProtocolExportAccessController_SetConfig_Call) Run(run func(cfg config.Manager)) *MockProtocolExportAccessController_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtocolExportAccessController_SetConfig_Call) Return() *MockProtocolExportAccessController_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProtocolExportAccessController_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockProtocolExportAccessController_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockProtocolExportAccessController_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockProtocolExportAccessController_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockProtocolExportAccessController_Expecter) SetContext(ctx interface{}) *MockProtocolExportAccessController_SetContext_Call {
	return &MockProtocolExportAccessController_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockProtocolExportAccessController_SetContext_Call) Run(run func(ctx core.Context)) *MockProtocolExportAccessController_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtocolExportAccessController_SetContext_Call) Return() *MockProtocolExportAccessController_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProtocolExportAccessController_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockProtocolExportAccessController_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockProtocolExportAccessController_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockProtocolExportAccessController_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockProtocolExportAccessController_Expecter) SetDB(db interface{}) *MockProtocolExportAccessController_SetDB_Call {
	return &MockProtocolExportAccessController_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockProtocolExportAccessController_SetDB_Call) Run(run func(db *gorm.DB)) *MockProtocolExportAccessController_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtocolExportAccessController_SetDB_Call) Return() *MockProtocolExportAccessController_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProtocolExportAccessController_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockProtocolExportAccessController_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockProtocolExportAccessController_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockProtocolExportAccessController_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockProtocolExportAccessController_Expecter) SetLogger(logger interface{}) *MockProtocolExportAccessController_SetLogger_Call {
	return &MockProtocolExportAccessController_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockProtocolExportAccessController_SetLogger_Call) Run(run func(logger *core.Logger)) *MockProtocolExportAccessController_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtocolExportAccessController_SetLogger_Call) Return() *MockProtocolExportAccessController_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProtocolExportAccessController_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockProtocolExportAccessController_SetLogger_Call {
	_c.Run(run)
	return _c
}

// Workflows provides a mock function for the type MockProtocolExportAccessController
func (_mock *MockProtocolExportAccessController) Workflows() []core.WorkflowDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workflows")
	}

	var r0 []core.WorkflowDefinition
	if returnFunc, ok := ret.Get(0).(func() []core.WorkflowDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.WorkflowDefinition)
		}
	}
	return r0
}

// MockProtocolExportAccessController_Workflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workflows'
type MockProtocolExportAccessController_Workflows_Call struct {
	*mock.Call
}

// Workflows is a helper method to define mock.On call
func (_e *MockProtocolExportAccessController_Expecter) Workflows() *MockProtocolExportAccessController_Workflows_Call {
	return &MockProtocolExportAccessController_Workflows_Call{Call: _e.mock.On("Workflows")}
}

func (_c *MockProtocolExportAccessController_Workflows_Call) Run(run func()) *MockProtocolExportAccessController_Workflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolExportAccessController_Workflows_Call) Return(workflowDefinitions []core.WorkflowDefinition) *MockProtocolExportAccessController_Workflows_Call {
	_c.Call.Return(workflowDefinitions)
	return _c
}

func (_c *MockProtocolExportAccessController_Workflows_Call) RunAndReturn(run func() []core.WorkflowDefinition) *MockProtocolExportAccessController_Workflows_Call {
	_c.Call.Return(run)
	return _c
}
