// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
)

// NewMockProtocolParser creates a new instance of MockProtocolParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProtocolParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProtocolParser {
	mock := &MockProtocolParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProtocolParser is an autogenerated mock type for the ProtocolParser type
type MockProtocolParser struct {
	mock.Mock
}

type MockProtocolParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProtocolParser) EXPECT() *MockProtocolParser_Expecter {
	return &MockProtocolParser_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockProtocolParser
func (_mock *MockProtocolParser) Config() config.ProtocolConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.ProtocolConfig
	if returnFunc, ok := ret.Get(0).(func() config.ProtocolConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ProtocolConfig)
		}
	}
	return r0
}

// MockProtocolParser_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockProtocolParser_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockProtocolParser_Expecter) Config() *MockProtocolParser_Config_Call {
	return &MockProtocolParser_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockProtocolParser_Config_Call) Run(run func()) *MockProtocolParser_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolParser_Config_Call) Return(protocolConfig config.ProtocolConfig) *MockProtocolParser_Config_Call {
	_c.Call.Return(protocolConfig)
	return _c
}

func (_c *MockProtocolParser_Config_Call) RunAndReturn(run func() config.ProtocolConfig) *MockProtocolParser_Config_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function for the type MockProtocolParser
func (_mock *MockProtocolParser) DisplayName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtocolParser_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockProtocolParser_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *MockProtocolParser_Expecter) DisplayName() *MockProtocolParser_DisplayName_Call {
	return &MockProtocolParser_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *MockProtocolParser_DisplayName_Call) Run(run func()) *MockProtocolParser_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolParser_DisplayName_Call) Return(s string) *MockProtocolParser_DisplayName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtocolParser_DisplayName_Call) RunAndReturn(run func() string) *MockProtocolParser_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProtocolParser
func (_mock *MockProtocolParser) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtocolParser_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProtocolParser_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProtocolParser_Expecter) Name() *MockProtocolParser_Name_Call {
	return &MockProtocolParser_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProtocolParser_Name_Call) Run(run func()) *MockProtocolParser_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolParser_Name_Call) Return(s string) *MockProtocolParser_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtocolParser_Name_Call) RunAndReturn(run func() string) *MockProtocolParser_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function for the type MockProtocolParser
func (_mock *MockProtocolParser) Operations() []core.Operation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 []core.Operation
	if returnFunc, ok := ret.Get(0).(func() []core.Operation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Operation)
		}
	}
	return r0
}

// MockProtocolParser_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type MockProtocolParser_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *MockProtocolParser_Expecter) Operations() *MockProtocolParser_Operations_Call {
	return &MockProtocolParser_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *MockProtocolParser_Operations_Call) Run(run func()) *MockProtocolParser_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolParser_Operations_Call) Return(operations []core.Operation) *MockProtocolParser_Operations_Call {
	_c.Call.Return(operations)
	return _c
}

func (_c *MockProtocolParser_Operations_Call) RunAndReturn(run func() []core.Operation) *MockProtocolParser_Operations_Call {
	_c.Call.Return(run)
	return _c
}

// ParserName provides a mock function for the type MockProtocolParser
func (_mock *MockProtocolParser) ParserName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ParserName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtocolParser_ParserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParserName'
type MockProtocolParser_ParserName_Call struct {
	*mock.Call
}

// ParserName is a helper method to define mock.On call
func (_e *MockProtocolParser_Expecter) ParserName() *MockProtocolParser_ParserName_Call {
	return &MockProtocolParser_ParserName_Call{Call: _e.mock.On("ParserName")}
}

func (_c *MockProtocolParser_ParserName_Call) Run(run func()) *MockProtocolParser_ParserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolParser_ParserName_Call) Return(s string) *MockProtocolParser_ParserName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtocolParser_ParserName_Call) RunAndReturn(run func() string) *MockProtocolParser_ParserName_Call {
	_c.Call.Return(run)
	return _c
}

// TryParse provides a mock function for the type MockProtocolParser
func (_mock *MockProtocolParser) TryParse(s string) (core.StorageHash, bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for TryParse")
	}

	var r0 core.StorageHash
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (core.StorageHash, bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) core.StorageHash); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.StorageHash)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(s)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProtocolParser_TryParse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryParse'
type MockProtocolParser_TryParse_Call struct {
	*mock.Call
}

// TryParse is a helper method to define mock.On call
//   - s string
func (_e *MockProtocolParser_Expecter) TryParse(s interface{}) *MockProtocolParser_TryParse_Call {
	return &MockProtocolParser_TryParse_Call{Call: _e.mock.On("TryParse", s)}
}

func (_c *MockProtocolParser_TryParse_Call) Run(run func(s string)) *MockProtocolParser_TryParse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtocolParser_TryParse_Call) Return(storageHash core.StorageHash, b bool, err error) *MockProtocolParser_TryParse_Call {
	_c.Call.Return(storageHash, b, err)
	return _c
}

func (_c *MockProtocolParser_TryParse_Call) RunAndReturn(run func(s string) (core.StorageHash, bool, error)) *MockProtocolParser_TryParse_Call {
	_c.Call.Return(run)
	return _c
}

// Workflows provides a mock function for the type MockProtocolParser
func (_mock *MockProtocolParser) Workflows() []core.WorkflowDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workflows")
	}

	var r0 []core.WorkflowDefinition
	if returnFunc, ok := ret.Get(0).(func() []core.WorkflowDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.WorkflowDefinition)
		}
	}
	return r0
}

// MockProtocolParser_Workflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workflows'
type MockProtocolParser_Workflows_Call struct {
	*mock.Call
}

// Workflows is a helper method to define mock.On call
func (_e *MockProtocolParser_Expecter) Workflows() *MockProtocolParser_Workflows_Call {
	return &MockProtocolParser_Workflows_Call{Call: _e.mock.On("Workflows")}
}

func (_c *MockProtocolParser_Workflows_Call) Run(run func()) *MockProtocolParser_Workflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtocolParser_Workflows_Call) Return(workflowDefinitions []core.WorkflowDefinition) *MockProtocolParser_Workflows_Call {
	_c.Call.Return(workflowDefinitions)
	return _c
}

func (_c *MockProtocolParser_Workflows_Call) RunAndReturn(run func() []core.WorkflowDefinition) *MockProtocolParser_Workflows_Call {
	_c.Call.Return(run)
	return _c
}
