// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/portal/db/models"
	"go.sia.tech/renterd/v2/api"
	"gorm.io/gorm"
)

// NewMockRenterService creates a new instance of MockRenterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenterService {
	mock := &MockRenterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRenterService is an autogenerated mock type for the RenterService type
type MockRenterService struct {
	mock.Mock
}

type MockRenterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenterService) EXPECT() *MockRenterService_Expecter {
	return &MockRenterService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockRenterService
func (_mock *MockRenterService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockRenterService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockRenterService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockRenterService_Expecter) Config() *MockRenterService_Config_Call {
	return &MockRenterService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockRenterService_Config_Call) Run(run func()) *MockRenterService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRenterService_Config_Call) Return(manager config.Manager) *MockRenterService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockRenterService_Config_Call) RunAndReturn(run func() config.Manager) *MockRenterService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockRenterService
func (_mock *MockRenterService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockRenterService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockRenterService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockRenterService_Expecter) Context() *MockRenterService_Context_Call {
	return &MockRenterService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockRenterService_Context_Call) Run(run func()) *MockRenterService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRenterService_Context_Call) Return(context core.Context) *MockRenterService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockRenterService_Context_Call) RunAndReturn(run func() core.Context) *MockRenterService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBucketIfNotExists provides a mock function for the type MockRenterService
func (_mock *MockRenterService) CreateBucketIfNotExists(bucket string) error {
	ret := _mock.Called(bucket)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucketIfNotExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(bucket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRenterService_CreateBucketIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucketIfNotExists'
type MockRenterService_CreateBucketIfNotExists_Call struct {
	*mock.Call
}

// CreateBucketIfNotExists is a helper method to define mock.On call
//   - bucket string
func (_e *MockRenterService_Expecter) CreateBucketIfNotExists(bucket interface{}) *MockRenterService_CreateBucketIfNotExists_Call {
	return &MockRenterService_CreateBucketIfNotExists_Call{Call: _e.mock.On("CreateBucketIfNotExists", bucket)}
}

func (_c *MockRenterService_CreateBucketIfNotExists_Call) Run(run func(bucket string)) *MockRenterService_CreateBucketIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenterService_CreateBucketIfNotExists_Call) Return(err error) *MockRenterService_CreateBucketIfNotExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRenterService_CreateBucketIfNotExists_Call) RunAndReturn(run func(bucket string) error) *MockRenterService_CreateBucketIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockRenterService
func (_mock *MockRenterService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockRenterService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockRenterService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockRenterService_Expecter) DB() *MockRenterService_DB_Call {
	return &MockRenterService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockRenterService_DB_Call) Run(run func()) *MockRenterService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRenterService_DB_Call) Return(dB *gorm.DB) *MockRenterService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockRenterService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockRenterService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type MockRenterService
func (_mock *MockRenterService) DeleteObject(ctx context.Context, bucket string, fileName string) error {
	ret := _mock.Called(ctx, bucket, fileName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, fileName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRenterService_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockRenterService_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - fileName string
func (_e *MockRenterService_Expecter) DeleteObject(ctx interface{}, bucket interface{}, fileName interface{}) *MockRenterService_DeleteObject_Call {
	return &MockRenterService_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, bucket, fileName)}
}

func (_c *MockRenterService_DeleteObject_Call) Run(run func(ctx context.Context, bucket string, fileName string)) *MockRenterService_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRenterService_DeleteObject_Call) Return(err error) *MockRenterService_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRenterService_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, fileName string) error) *MockRenterService_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObjectMetadata provides a mock function for the type MockRenterService
func (_mock *MockRenterService) DeleteObjectMetadata(ctx context.Context, bucket string, fileName string) error {
	ret := _mock.Called(ctx, bucket, fileName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjectMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, fileName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRenterService_DeleteObjectMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjectMetadata'
type MockRenterService_DeleteObjectMetadata_Call struct {
	*mock.Call
}

// DeleteObjectMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - fileName string
func (_e *MockRenterService_Expecter) DeleteObjectMetadata(ctx interface{}, bucket interface{}, fileName interface{}) *MockRenterService_DeleteObjectMetadata_Call {
	return &MockRenterService_DeleteObjectMetadata_Call{Call: _e.mock.On("DeleteObjectMetadata", ctx, bucket, fileName)}
}

func (_c *MockRenterService_DeleteObjectMetadata_Call) Run(run func(ctx context.Context, bucket string, fileName string)) *MockRenterService_DeleteObjectMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRenterService_DeleteObjectMetadata_Call) Return(err error) *MockRenterService_DeleteObjectMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRenterService_DeleteObjectMetadata_Call) RunAndReturn(run func(ctx context.Context, bucket string, fileName string) error) *MockRenterService_DeleteObjectMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type MockRenterService
func (_mock *MockRenterService) GetObject(ctx context.Context, bucket string, fileName string, options api.DownloadObjectOptions) (*api.GetObjectResponse, error) {
	ret := _mock.Called(ctx, bucket, fileName, options)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *api.GetObjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, api.DownloadObjectOptions) (*api.GetObjectResponse, error)); ok {
		return returnFunc(ctx, bucket, fileName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, api.DownloadObjectOptions) *api.GetObjectResponse); ok {
		r0 = returnFunc(ctx, bucket, fileName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.GetObjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, api.DownloadObjectOptions) error); ok {
		r1 = returnFunc(ctx, bucket, fileName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenterService_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockRenterService_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - fileName string
//   - options api.DownloadObjectOptions
func (_e *MockRenterService_Expecter) GetObject(ctx interface{}, bucket interface{}, fileName interface{}, options interface{}) *MockRenterService_GetObject_Call {
	return &MockRenterService_GetObject_Call{Call: _e.mock.On("GetObject", ctx, bucket, fileName, options)}
}

func (_c *MockRenterService_GetObject_Call) Run(run func(ctx context.Context, bucket string, fileName string, options api.DownloadObjectOptions)) *MockRenterService_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 api.DownloadObjectOptions
		if args[3] != nil {
			arg3 = args[3].(api.DownloadObjectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRenterService_GetObject_Call) Return(getObjectResponse *api.GetObjectResponse, err error) *MockRenterService_GetObject_Call {
	_c.Call.Return(getObjectResponse, err)
	return _c
}

func (_c *MockRenterService_GetObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, fileName string, options api.DownloadObjectOptions) (*api.GetObjectResponse, error)) *MockRenterService_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectMetadata provides a mock function for the type MockRenterService
func (_mock *MockRenterService) GetObjectMetadata(ctx context.Context, bucket string, fileName string) (*api.Object, error) {
	ret := _mock.Called(ctx, bucket, fileName)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectMetadata")
	}

	var r0 *api.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*api.Object, error)); ok {
		return returnFunc(ctx, bucket, fileName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *api.Object); ok {
		r0 = returnFunc(ctx, bucket, fileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, fileName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenterService_GetObjectMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectMetadata'
type MockRenterService_GetObjectMetadata_Call struct {
	*mock.Call
}

// GetObjectMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - fileName string
func (_e *MockRenterService_Expecter) GetObjectMetadata(ctx interface{}, bucket interface{}, fileName interface{}) *MockRenterService_GetObjectMetadata_Call {
	return &MockRenterService_GetObjectMetadata_Call{Call: _e.mock.On("GetObjectMetadata", ctx, bucket, fileName)}
}

func (_c *MockRenterService_GetObjectMetadata_Call) Run(run func(ctx context.Context, bucket string, fileName string)) *MockRenterService_GetObjectMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRenterService_GetObjectMetadata_Call) Return(object *api.Object, err error) *MockRenterService_GetObjectMetadata_Call {
	_c.Call.Return(object, err)
	return _c
}

func (_c *MockRenterService_GetObjectMetadata_Call) RunAndReturn(run func(ctx context.Context, bucket string, fileName string) (*api.Object, error)) *MockRenterService_GetObjectMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GougingSettings provides a mock function for the type MockRenterService
func (_mock *MockRenterService) GougingSettings(ctx context.Context) (api.GougingSettings, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GougingSettings")
	}

	var r0 api.GougingSettings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (api.GougingSettings, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) api.GougingSettings); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(api.GougingSettings)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenterService_GougingSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GougingSettings'
type MockRenterService_GougingSettings_Call struct {
	*mock.Call
}

// GougingSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRenterService_Expecter) GougingSettings(ctx interface{}) *MockRenterService_GougingSettings_Call {
	return &MockRenterService_GougingSettings_Call{Call: _e.mock.On("GougingSettings", ctx)}
}

func (_c *MockRenterService_GougingSettings_Call) Run(run func(ctx context.Context)) *MockRenterService_GougingSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenterService_GougingSettings_Call) Return(gougingSettings api.GougingSettings, err error) *MockRenterService_GougingSettings_Call {
	_c.Call.Return(gougingSettings, err)
	return _c
}

func (_c *MockRenterService_GougingSettings_Call) RunAndReturn(run func(ctx context.Context) (api.GougingSettings, error)) *MockRenterService_GougingSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockRenterService
func (_mock *MockRenterService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRenterService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockRenterService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockRenterService_Expecter) ID() *MockRenterService_ID_Call {
	return &MockRenterService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockRenterService_ID_Call) Run(run func()) *MockRenterService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRenterService_ID_Call) Return(s string) *MockRenterService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRenterService_ID_Call) RunAndReturn(run func() string) *MockRenterService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockRenterService
func (_mock *MockRenterService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockRenterService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockRenterService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockRenterService_Expecter) Logger() *MockRenterService_Logger_Call {
	return &MockRenterService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockRenterService_Logger_Call) Run(run func()) *MockRenterService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRenterService_Logger_Call) Return(logger *core.Logger) *MockRenterService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockRenterService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockRenterService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockRenterService
func (_mock *MockRenterService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockRenterService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockRenterService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockRenterService_Expecter) SetConfig(cfg interface{}) *MockRenterService_SetConfig_Call {
	return &MockRenterService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockRenterService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockRenterService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenterService_SetConfig_Call) Return() *MockRenterService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRenterService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockRenterService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockRenterService
func (_mock *MockRenterService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockRenterService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockRenterService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockRenterService_Expecter) SetContext(ctx interface{}) *MockRenterService_SetContext_Call {
	return &MockRenterService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockRenterService_SetContext_Call) Run(run func(ctx core.Context)) *MockRenterService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenterService_SetContext_Call) Return() *MockRenterService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRenterService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockRenterService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockRenterService
func (_mock *MockRenterService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockRenterService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockRenterService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockRenterService_Expecter) SetDB(db interface{}) *MockRenterService_SetDB_Call {
	return &MockRenterService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockRenterService_SetDB_Call) Run(run func(db *gorm.DB)) *MockRenterService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenterService_SetDB_Call) Return() *MockRenterService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRenterService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockRenterService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockRenterService
func (_mock *MockRenterService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockRenterService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockRenterService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockRenterService_Expecter) SetLogger(logger interface{}) *MockRenterService_SetLogger_Call {
	return &MockRenterService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockRenterService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockRenterService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenterService_SetLogger_Call) Return() *MockRenterService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRenterService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockRenterService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SlabSize provides a mock function for the type MockRenterService
func (_mock *MockRenterService) SlabSize(ctx context.Context) (uint64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SlabSize")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenterService_SlabSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlabSize'
type MockRenterService_SlabSize_Call struct {
	*mock.Call
}

// SlabSize is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRenterService_Expecter) SlabSize(ctx interface{}) *MockRenterService_SlabSize_Call {
	return &MockRenterService_SlabSize_Call{Call: _e.mock.On("SlabSize", ctx)}
}

func (_c *MockRenterService_SlabSize_Call) Run(run func(ctx context.Context)) *MockRenterService_SlabSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenterService_SlabSize_Call) Return(v uint64, err error) *MockRenterService_SlabSize_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRenterService_SlabSize_Call) RunAndReturn(run func(ctx context.Context) (uint64, error)) *MockRenterService_SlabSize_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGougingSettings provides a mock function for the type MockRenterService
func (_mock *MockRenterService) UpdateGougingSettings(ctx context.Context, settings api.GougingSettings) error {
	ret := _mock.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGougingSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.GougingSettings) error); ok {
		r0 = returnFunc(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRenterService_UpdateGougingSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGougingSettings'
type MockRenterService_UpdateGougingSettings_Call struct {
	*mock.Call
}

// UpdateGougingSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - settings api.GougingSettings
func (_e *MockRenterService_Expecter) UpdateGougingSettings(ctx interface{}, settings interface{}) *MockRenterService_UpdateGougingSettings_Call {
	return &MockRenterService_UpdateGougingSettings_Call{Call: _e.mock.On("UpdateGougingSettings", ctx, settings)}
}

func (_c *MockRenterService_UpdateGougingSettings_Call) Run(run func(ctx context.Context, settings api.GougingSettings)) *MockRenterService_UpdateGougingSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 api.GougingSettings
		if args[1] != nil {
			arg1 = args[1].(api.GougingSettings)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenterService_UpdateGougingSettings_Call) Return(err error) *MockRenterService_UpdateGougingSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRenterService_UpdateGougingSettings_Call) RunAndReturn(run func(ctx context.Context, settings api.GougingSettings) error) *MockRenterService_UpdateGougingSettings_Call {
	_c.Call.Return(run)
	return _c
}

// UploadExists provides a mock function for the type MockRenterService
func (_mock *MockRenterService) UploadExists(ctx context.Context, bucket string, fileName string) (bool, *models.SiaUpload, error) {
	ret := _mock.Called(ctx, bucket, fileName)

	if len(ret) == 0 {
		panic("no return value specified for UploadExists")
	}

	var r0 bool
	var r1 *models.SiaUpload
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, *models.SiaUpload, error)); ok {
		return returnFunc(ctx, bucket, fileName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, bucket, fileName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *models.SiaUpload); ok {
		r1 = returnFunc(ctx, bucket, fileName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.SiaUpload)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, bucket, fileName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRenterService_UploadExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadExists'
type MockRenterService_UploadExists_Call struct {
	*mock.Call
}

// UploadExists is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - fileName string
func (_e *MockRenterService_Expecter) UploadExists(ctx interface{}, bucket interface{}, fileName interface{}) *MockRenterService_UploadExists_Call {
	return &MockRenterService_UploadExists_Call{Call: _e.mock.On("UploadExists", ctx, bucket, fileName)}
}

func (_c *MockRenterService_UploadExists_Call) Run(run func(ctx context.Context, bucket string, fileName string)) *MockRenterService_UploadExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRenterService_UploadExists_Call) Return(b bool, siaUpload *models.SiaUpload, err error) *MockRenterService_UploadExists_Call {
	_c.Call.Return(b, siaUpload, err)
	return _c
}

func (_c *MockRenterService_UploadExists_Call) RunAndReturn(run func(ctx context.Context, bucket string, fileName string) (bool, *models.SiaUpload, error)) *MockRenterService_UploadExists_Call {
	_c.Call.Return(run)
	return _c
}

// UploadObject provides a mock function for the type MockRenterService
func (_mock *MockRenterService) UploadObject(ctx context.Context, file io.Reader, bucket string, fileName string) error {
	ret := _mock.Called(ctx, file, bucket, fileName)

	if len(ret) == 0 {
		panic("no return value specified for UploadObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) error); ok {
		r0 = returnFunc(ctx, file, bucket, fileName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRenterService_UploadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadObject'
type MockRenterService_UploadObject_Call struct {
	*mock.Call
}

// UploadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - bucket string
//   - fileName string
func (_e *MockRenterService_Expecter) UploadObject(ctx interface{}, file interface{}, bucket interface{}, fileName interface{}) *MockRenterService_UploadObject_Call {
	return &MockRenterService_UploadObject_Call{Call: _e.mock.On("UploadObject", ctx, file, bucket, fileName)}
}

func (_c *MockRenterService_UploadObject_Call) Run(run func(ctx context.Context, file io.Reader, bucket string, fileName string)) *MockRenterService_UploadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRenterService_UploadObject_Call) Return(err error) *MockRenterService_UploadObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRenterService_UploadObject_Call) RunAndReturn(run func(ctx context.Context, file io.Reader, bucket string, fileName string) error) *MockRenterService_UploadObject_Call {
	_c.Call.Return(run)
	return _c
}

// UploadObjectMultipart provides a mock function for the type MockRenterService
func (_mock *MockRenterService) UploadObjectMultipart(ctx context.Context, params *core.MultipartUploadParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UploadObjectMultipart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.MultipartUploadParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRenterService_UploadObjectMultipart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadObjectMultipart'
type MockRenterService_UploadObjectMultipart_Call struct {
	*mock.Call
}

// UploadObjectMultipart is a helper method to define mock.On call
//   - ctx context.Context
//   - params *core.MultipartUploadParams
func (_e *MockRenterService_Expecter) UploadObjectMultipart(ctx interface{}, params interface{}) *MockRenterService_UploadObjectMultipart_Call {
	return &MockRenterService_UploadObjectMultipart_Call{Call: _e.mock.On("UploadObjectMultipart", ctx, params)}
}

func (_c *MockRenterService_UploadObjectMultipart_Call) Run(run func(ctx context.Context, params *core.MultipartUploadParams)) *MockRenterService_UploadObjectMultipart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.MultipartUploadParams
		if args[1] != nil {
			arg1 = args[1].(*core.MultipartUploadParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenterService_UploadObjectMultipart_Call) Return(err error) *MockRenterService_UploadObjectMultipart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRenterService_UploadObjectMultipart_Call) RunAndReturn(run func(ctx context.Context, params *core.MultipartUploadParams) error) *MockRenterService_UploadObjectMultipart_Call {
	_c.Call.Return(run)
	return _c
}
