// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	core "go.lumeweb.com/portal/core"
	data_models "go.lumeweb.com/portal/db/models/data_models"

	mock "github.com/stretchr/testify/mock"

	models "go.lumeweb.com/portal/db/models"
)

// MockRequestService is an autogenerated mock type for the RequestService type
type MockRequestService struct {
	mock.Mock
}

type MockRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestService) EXPECT() *MockRequestService_Expecter {
	return &MockRequestService_Expecter{mock: &_m.Mock}
}

// CompleteRequest provides a mock function with given fields: ctx, id
func (_m *MockRequestService) CompleteRequest(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestService_CompleteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteRequest'
type MockRequestService_CompleteRequest_Call struct {
	*mock.Call
}

// CompleteRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRequestService_Expecter) CompleteRequest(ctx interface{}, id interface{}) *MockRequestService_CompleteRequest_Call {
	return &MockRequestService_CompleteRequest_Call{Call: _e.mock.On("CompleteRequest", ctx, id)}
}

func (_c *MockRequestService_CompleteRequest_Call) Run(run func(ctx context.Context, id uint)) *MockRequestService_CompleteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRequestService_CompleteRequest_Call) Return(_a0 error) *MockRequestService_CompleteRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestService_CompleteRequest_Call) RunAndReturn(run func(context.Context, uint) error) *MockRequestService_CompleteRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRequest provides a mock function with given fields: ctx, req, data
func (_m *MockRequestService) CreateRequest(ctx context.Context, req *models.Request, data interface{}) (*models.Request, error) {
	ret := _m.Called(ctx, req, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 *models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request, interface{}) (*models.Request, error)); ok {
		return rf(ctx, req, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request, interface{}) *models.Request); ok {
		r0 = rf(ctx, req, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Request, interface{}) error); ok {
		r1 = rf(ctx, req, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type MockRequestService_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.Request
//   - data interface{}
func (_e *MockRequestService_Expecter) CreateRequest(ctx interface{}, req interface{}, data interface{}) *MockRequestService_CreateRequest_Call {
	return &MockRequestService_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, req, data)}
}

func (_c *MockRequestService_CreateRequest_Call) Run(run func(ctx context.Context, req *models.Request, data interface{})) *MockRequestService_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Request), args[2].(interface{}))
	})
	return _c
}

func (_c *MockRequestService_CreateRequest_Call) Return(_a0 *models.Request, _a1 error) *MockRequestService_CreateRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_CreateRequest_Call) RunAndReturn(run func(context.Context, *models.Request, interface{}) (*models.Request, error)) *MockRequestService_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRequestModel provides a mock function with given fields: operation
func (_m *MockRequestService) CreateRequestModel(operation string) (data_models.RequestDataModel, error) {
	ret := _m.Called(operation)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequestModel")
	}

	var r0 data_models.RequestDataModel
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (data_models.RequestDataModel, error)); ok {
		return rf(operation)
	}
	if rf, ok := ret.Get(0).(func(string) data_models.RequestDataModel); ok {
		r0 = rf(operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data_models.RequestDataModel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(operation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_CreateRequestModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequestModel'
type MockRequestService_CreateRequestModel_Call struct {
	*mock.Call
}

// CreateRequestModel is a helper method to define mock.On call
//   - operation string
func (_e *MockRequestService_Expecter) CreateRequestModel(operation interface{}) *MockRequestService_CreateRequestModel_Call {
	return &MockRequestService_CreateRequestModel_Call{Call: _e.mock.On("CreateRequestModel", operation)}
}

func (_c *MockRequestService_CreateRequestModel_Call) Run(run func(operation string)) *MockRequestService_CreateRequestModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRequestService_CreateRequestModel_Call) Return(_a0 data_models.RequestDataModel, _a1 error) *MockRequestService_CreateRequestModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_CreateRequestModel_Call) RunAndReturn(run func(string) (data_models.RequestDataModel, error)) *MockRequestService_CreateRequestModel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRequest provides a mock function with given fields: ctx, id
func (_m *MockRequestService) DeleteRequest(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestService_DeleteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRequest'
type MockRequestService_DeleteRequest_Call struct {
	*mock.Call
}

// DeleteRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRequestService_Expecter) DeleteRequest(ctx interface{}, id interface{}) *MockRequestService_DeleteRequest_Call {
	return &MockRequestService_DeleteRequest_Call{Call: _e.mock.On("DeleteRequest", ctx, id)}
}

func (_c *MockRequestService_DeleteRequest_Call) Run(run func(ctx context.Context, id uint)) *MockRequestService_DeleteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRequestService_DeleteRequest_Call) Return(_a0 error) *MockRequestService_DeleteRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestService_DeleteRequest_Call) RunAndReturn(run func(context.Context, uint) error) *MockRequestService_DeleteRequest_Call {
	_c.Call.Return(run)
	return _c
}

// FailRequest provides a mock function with given fields: ctx, id, reason
func (_m *MockRequestService) FailRequest(ctx context.Context, id uint, reason string) error {
	ret := _m.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for FailRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, id, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestService_FailRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailRequest'
type MockRequestService_FailRequest_Call struct {
	*mock.Call
}

// FailRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - reason string
func (_e *MockRequestService_Expecter) FailRequest(ctx interface{}, id interface{}, reason interface{}) *MockRequestService_FailRequest_Call {
	return &MockRequestService_FailRequest_Call{Call: _e.mock.On("FailRequest", ctx, id, reason)}
}

func (_c *MockRequestService_FailRequest_Call) Run(run func(ctx context.Context, id uint, reason string)) *MockRequestService_FailRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockRequestService_FailRequest_Call) Return(_a0 error) *MockRequestService_FailRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestService_FailRequest_Call) RunAndReturn(run func(context.Context, uint, string) error) *MockRequestService_FailRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function with given fields: ctx, id
func (_m *MockRequestService) GetRequest(ctx context.Context, id uint) (*models.Request, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 *models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Request, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Request); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type MockRequestService_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRequestService_Expecter) GetRequest(ctx interface{}, id interface{}) *MockRequestService_GetRequest_Call {
	return &MockRequestService_GetRequest_Call{Call: _e.mock.On("GetRequest", ctx, id)}
}

func (_c *MockRequestService_GetRequest_Call) Run(run func(ctx context.Context, id uint)) *MockRequestService_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRequestService_GetRequest_Call) Return(_a0 *models.Request, _a1 error) *MockRequestService_GetRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetRequest_Call) RunAndReturn(run func(context.Context, uint) (*models.Request, error)) *MockRequestService_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestByHash provides a mock function with given fields: ctx, hash, filter
func (_m *MockRequestService) GetRequestByHash(ctx context.Context, hash core.StorageHash, filter core.RequestFilter) (*models.Request, error) {
	ret := _m.Called(ctx, hash, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestByHash")
	}

	var r0 *models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.StorageHash, core.RequestFilter) (*models.Request, error)); ok {
		return rf(ctx, hash, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.StorageHash, core.RequestFilter) *models.Request); ok {
		r0 = rf(ctx, hash, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.StorageHash, core.RequestFilter) error); ok {
		r1 = rf(ctx, hash, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetRequestByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestByHash'
type MockRequestService_GetRequestByHash_Call struct {
	*mock.Call
}

// GetRequestByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash core.StorageHash
//   - filter core.RequestFilter
func (_e *MockRequestService_Expecter) GetRequestByHash(ctx interface{}, hash interface{}, filter interface{}) *MockRequestService_GetRequestByHash_Call {
	return &MockRequestService_GetRequestByHash_Call{Call: _e.mock.On("GetRequestByHash", ctx, hash, filter)}
}

func (_c *MockRequestService_GetRequestByHash_Call) Run(run func(ctx context.Context, hash core.StorageHash, filter core.RequestFilter)) *MockRequestService_GetRequestByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.StorageHash), args[2].(core.RequestFilter))
	})
	return _c
}

func (_c *MockRequestService_GetRequestByHash_Call) Return(_a0 *models.Request, _a1 error) *MockRequestService_GetRequestByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetRequestByHash_Call) RunAndReturn(run func(context.Context, core.StorageHash, core.RequestFilter) (*models.Request, error)) *MockRequestService_GetRequestByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestByUploadHash provides a mock function with given fields: ctx, hash, filter
func (_m *MockRequestService) GetRequestByUploadHash(ctx context.Context, hash core.StorageHash, filter core.RequestFilter) (*models.Request, error) {
	ret := _m.Called(ctx, hash, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestByUploadHash")
	}

	var r0 *models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.StorageHash, core.RequestFilter) (*models.Request, error)); ok {
		return rf(ctx, hash, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.StorageHash, core.RequestFilter) *models.Request); ok {
		r0 = rf(ctx, hash, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.StorageHash, core.RequestFilter) error); ok {
		r1 = rf(ctx, hash, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetRequestByUploadHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestByUploadHash'
type MockRequestService_GetRequestByUploadHash_Call struct {
	*mock.Call
}

// GetRequestByUploadHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash core.StorageHash
//   - filter core.RequestFilter
func (_e *MockRequestService_Expecter) GetRequestByUploadHash(ctx interface{}, hash interface{}, filter interface{}) *MockRequestService_GetRequestByUploadHash_Call {
	return &MockRequestService_GetRequestByUploadHash_Call{Call: _e.mock.On("GetRequestByUploadHash", ctx, hash, filter)}
}

func (_c *MockRequestService_GetRequestByUploadHash_Call) Run(run func(ctx context.Context, hash core.StorageHash, filter core.RequestFilter)) *MockRequestService_GetRequestByUploadHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.StorageHash), args[2].(core.RequestFilter))
	})
	return _c
}

func (_c *MockRequestService_GetRequestByUploadHash_Call) Return(_a0 *models.Request, _a1 error) *MockRequestService_GetRequestByUploadHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetRequestByUploadHash_Call) RunAndReturn(run func(context.Context, core.StorageHash, core.RequestFilter) (*models.Request, error)) *MockRequestService_GetRequestByUploadHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestData provides a mock function with given fields: ctx, req
func (_m *MockRequestService) GetRequestData(ctx context.Context, req *models.Request) (interface{}, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestData")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request) (interface{}, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request) interface{}); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetRequestData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestData'
type MockRequestService_GetRequestData_Call struct {
	*mock.Call
}

// GetRequestData is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.Request
func (_e *MockRequestService_Expecter) GetRequestData(ctx interface{}, req interface{}) *MockRequestService_GetRequestData_Call {
	return &MockRequestService_GetRequestData_Call{Call: _e.mock.On("GetRequestData", ctx, req)}
}

func (_c *MockRequestService_GetRequestData_Call) Run(run func(ctx context.Context, req *models.Request)) *MockRequestService_GetRequestData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Request))
	})
	return _c
}

func (_c *MockRequestService_GetRequestData_Call) Return(_a0 interface{}, _a1 error) *MockRequestService_GetRequestData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetRequestData_Call) RunAndReturn(run func(context.Context, *models.Request) (interface{}, error)) *MockRequestService_GetRequestData_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestModel provides a mock function with given fields: operation
func (_m *MockRequestService) GetRequestModel(operation string) (data_models.RequestDataModel, bool) {
	ret := _m.Called(operation)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestModel")
	}

	var r0 data_models.RequestDataModel
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (data_models.RequestDataModel, bool)); ok {
		return rf(operation)
	}
	if rf, ok := ret.Get(0).(func(string) data_models.RequestDataModel); ok {
		r0 = rf(operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data_models.RequestDataModel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(operation)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockRequestService_GetRequestModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestModel'
type MockRequestService_GetRequestModel_Call struct {
	*mock.Call
}

// GetRequestModel is a helper method to define mock.On call
//   - operation string
func (_e *MockRequestService_Expecter) GetRequestModel(operation interface{}) *MockRequestService_GetRequestModel_Call {
	return &MockRequestService_GetRequestModel_Call{Call: _e.mock.On("GetRequestModel", operation)}
}

func (_c *MockRequestService_GetRequestModel_Call) Run(run func(operation string)) *MockRequestService_GetRequestModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRequestService_GetRequestModel_Call) Return(_a0 data_models.RequestDataModel, _a1 bool) *MockRequestService_GetRequestModel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetRequestModel_Call) RunAndReturn(run func(string) (data_models.RequestDataModel, bool)) *MockRequestService_GetRequestModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestStatus provides a mock function with given fields: ctx, id
func (_m *MockRequestService) GetRequestStatus(ctx context.Context, id uint) (*core.RequestStatus, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestStatus")
	}

	var r0 *core.RequestStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*core.RequestStatus, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *core.RequestStatus); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.RequestStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetRequestStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestStatus'
type MockRequestService_GetRequestStatus_Call struct {
	*mock.Call
}

// GetRequestStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRequestService_Expecter) GetRequestStatus(ctx interface{}, id interface{}) *MockRequestService_GetRequestStatus_Call {
	return &MockRequestService_GetRequestStatus_Call{Call: _e.mock.On("GetRequestStatus", ctx, id)}
}

func (_c *MockRequestService_GetRequestStatus_Call) Run(run func(ctx context.Context, id uint)) *MockRequestService_GetRequestStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRequestService_GetRequestStatus_Call) Return(_a0 *core.RequestStatus, _a1 error) *MockRequestService_GetRequestStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetRequestStatus_Call) RunAndReturn(run func(context.Context, uint) (*core.RequestStatus, error)) *MockRequestService_GetRequestStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockRequestService) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRequestService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockRequestService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockRequestService_Expecter) ID() *MockRequestService_ID_Call {
	return &MockRequestService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockRequestService_ID_Call) Run(run func()) *MockRequestService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestService_ID_Call) Return(_a0 string) *MockRequestService_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestService_ID_Call) RunAndReturn(run func() string) *MockRequestService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListRequestsByStatus provides a mock function with given fields: ctx, status, filter
func (_m *MockRequestService) ListRequestsByStatus(ctx context.Context, status string, filter core.RequestFilter) ([]*models.Request, error) {
	ret := _m.Called(ctx, status, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListRequestsByStatus")
	}

	var r0 []*models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, core.RequestFilter) ([]*models.Request, error)); ok {
		return rf(ctx, status, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, core.RequestFilter) []*models.Request); ok {
		r0 = rf(ctx, status, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, core.RequestFilter) error); ok {
		r1 = rf(ctx, status, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_ListRequestsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRequestsByStatus'
type MockRequestService_ListRequestsByStatus_Call struct {
	*mock.Call
}

// ListRequestsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - filter core.RequestFilter
func (_e *MockRequestService_Expecter) ListRequestsByStatus(ctx interface{}, status interface{}, filter interface{}) *MockRequestService_ListRequestsByStatus_Call {
	return &MockRequestService_ListRequestsByStatus_Call{Call: _e.mock.On("ListRequestsByStatus", ctx, status, filter)}
}

func (_c *MockRequestService_ListRequestsByStatus_Call) Run(run func(ctx context.Context, status string, filter core.RequestFilter)) *MockRequestService_ListRequestsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(core.RequestFilter))
	})
	return _c
}

func (_c *MockRequestService_ListRequestsByStatus_Call) Return(_a0 []*models.Request, _a1 error) *MockRequestService_ListRequestsByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_ListRequestsByStatus_Call) RunAndReturn(run func(context.Context, string, core.RequestFilter) ([]*models.Request, error)) *MockRequestService_ListRequestsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListRequestsByUser provides a mock function with given fields: ctx, userID, filter
func (_m *MockRequestService) ListRequestsByUser(ctx context.Context, userID uint, filter core.RequestFilter) ([]*models.Request, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListRequestsByUser")
	}

	var r0 []*models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, core.RequestFilter) ([]*models.Request, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, core.RequestFilter) []*models.Request); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, core.RequestFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_ListRequestsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRequestsByUser'
type MockRequestService_ListRequestsByUser_Call struct {
	*mock.Call
}

// ListRequestsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filter core.RequestFilter
func (_e *MockRequestService_Expecter) ListRequestsByUser(ctx interface{}, userID interface{}, filter interface{}) *MockRequestService_ListRequestsByUser_Call {
	return &MockRequestService_ListRequestsByUser_Call{Call: _e.mock.On("ListRequestsByUser", ctx, userID, filter)}
}

func (_c *MockRequestService_ListRequestsByUser_Call) Run(run func(ctx context.Context, userID uint, filter core.RequestFilter)) *MockRequestService_ListRequestsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(core.RequestFilter))
	})
	return _c
}

func (_c *MockRequestService_ListRequestsByUser_Call) Return(_a0 []*models.Request, _a1 error) *MockRequestService_ListRequestsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_ListRequestsByUser_Call) RunAndReturn(run func(context.Context, uint, core.RequestFilter) ([]*models.Request, error)) *MockRequestService_ListRequestsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRequest provides a mock function with given fields: ctx, query, filter
func (_m *MockRequestService) QueryRequest(ctx context.Context, query interface{}, filter core.RequestFilter) (*models.Request, error) {
	ret := _m.Called(ctx, query, filter)

	if len(ret) == 0 {
		panic("no return value specified for QueryRequest")
	}

	var r0 *models.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, core.RequestFilter) (*models.Request, error)); ok {
		return rf(ctx, query, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, core.RequestFilter) *models.Request); ok {
		r0 = rf(ctx, query, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, core.RequestFilter) error); ok {
		r1 = rf(ctx, query, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_QueryRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRequest'
type MockRequestService_QueryRequest_Call struct {
	*mock.Call
}

// QueryRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - query interface{}
//   - filter core.RequestFilter
func (_e *MockRequestService_Expecter) QueryRequest(ctx interface{}, query interface{}, filter interface{}) *MockRequestService_QueryRequest_Call {
	return &MockRequestService_QueryRequest_Call{Call: _e.mock.On("QueryRequest", ctx, query, filter)}
}

func (_c *MockRequestService_QueryRequest_Call) Run(run func(ctx context.Context, query interface{}, filter core.RequestFilter)) *MockRequestService_QueryRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(core.RequestFilter))
	})
	return _c
}

func (_c *MockRequestService_QueryRequest_Call) Return(_a0 *models.Request, _a1 error) *MockRequestService_QueryRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_QueryRequest_Call) RunAndReturn(run func(context.Context, interface{}, core.RequestFilter) (*models.Request, error)) *MockRequestService_QueryRequest_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRequestModel provides a mock function with given fields: operation, model
func (_m *MockRequestService) RegisterRequestModel(operation string, model data_models.RequestDataModel) {
	_m.Called(operation, model)
}

// MockRequestService_RegisterRequestModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRequestModel'
type MockRequestService_RegisterRequestModel_Call struct {
	*mock.Call
}

// RegisterRequestModel is a helper method to define mock.On call
//   - operation string
//   - model data_models.RequestDataModel
func (_e *MockRequestService_Expecter) RegisterRequestModel(operation interface{}, model interface{}) *MockRequestService_RegisterRequestModel_Call {
	return &MockRequestService_RegisterRequestModel_Call{Call: _e.mock.On("RegisterRequestModel", operation, model)}
}

func (_c *MockRequestService_RegisterRequestModel_Call) Run(run func(operation string, model data_models.RequestDataModel)) *MockRequestService_RegisterRequestModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(data_models.RequestDataModel))
	})
	return _c
}

func (_c *MockRequestService_RegisterRequestModel_Call) Return() *MockRequestService_RegisterRequestModel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRequestService_RegisterRequestModel_Call) RunAndReturn(run func(string, data_models.RequestDataModel)) *MockRequestService_RegisterRequestModel_Call {
	_c.Run(run)
	return _c
}

// RequestExists provides a mock function with given fields: ctx, id
func (_m *MockRequestService) RequestExists(ctx context.Context, id uint) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RequestExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_RequestExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestExists'
type MockRequestService_RequestExists_Call struct {
	*mock.Call
}

// RequestExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRequestService_Expecter) RequestExists(ctx interface{}, id interface{}) *MockRequestService_RequestExists_Call {
	return &MockRequestService_RequestExists_Call{Call: _e.mock.On("RequestExists", ctx, id)}
}

func (_c *MockRequestService_RequestExists_Call) Run(run func(ctx context.Context, id uint)) *MockRequestService_RequestExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRequestService_RequestExists_Call) Return(_a0 bool, _a1 error) *MockRequestService_RequestExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_RequestExists_Call) RunAndReturn(run func(context.Context, uint) (bool, error)) *MockRequestService_RequestExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequest provides a mock function with given fields: ctx, req
func (_m *MockRequestService) UpdateRequest(ctx context.Context, req *models.Request) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestService_UpdateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequest'
type MockRequestService_UpdateRequest_Call struct {
	*mock.Call
}

// UpdateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.Request
func (_e *MockRequestService_Expecter) UpdateRequest(ctx interface{}, req interface{}) *MockRequestService_UpdateRequest_Call {
	return &MockRequestService_UpdateRequest_Call{Call: _e.mock.On("UpdateRequest", ctx, req)}
}

func (_c *MockRequestService_UpdateRequest_Call) Run(run func(ctx context.Context, req *models.Request)) *MockRequestService_UpdateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Request))
	})
	return _c
}

func (_c *MockRequestService_UpdateRequest_Call) Return(_a0 error) *MockRequestService_UpdateRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestService_UpdateRequest_Call) RunAndReturn(run func(context.Context, *models.Request) error) *MockRequestService_UpdateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequestData provides a mock function with given fields: ctx, req, data
func (_m *MockRequestService) UpdateRequestData(ctx context.Context, req *models.Request, data interface{}) error {
	ret := _m.Called(ctx, req, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequestData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Request, interface{}) error); ok {
		r0 = rf(ctx, req, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestService_UpdateRequestData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequestData'
type MockRequestService_UpdateRequestData_Call struct {
	*mock.Call
}

// UpdateRequestData is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.Request
//   - data interface{}
func (_e *MockRequestService_Expecter) UpdateRequestData(ctx interface{}, req interface{}, data interface{}) *MockRequestService_UpdateRequestData_Call {
	return &MockRequestService_UpdateRequestData_Call{Call: _e.mock.On("UpdateRequestData", ctx, req, data)}
}

func (_c *MockRequestService_UpdateRequestData_Call) Run(run func(ctx context.Context, req *models.Request, data interface{})) *MockRequestService_UpdateRequestData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Request), args[2].(interface{}))
	})
	return _c
}

func (_c *MockRequestService_UpdateRequestData_Call) Return(_a0 error) *MockRequestService_UpdateRequestData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestService_UpdateRequestData_Call) RunAndReturn(run func(context.Context, *models.Request, interface{}) error) *MockRequestService_UpdateRequestData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequestStatus provides a mock function with given fields: ctx, id, status
func (_m *MockRequestService) UpdateRequestStatus(ctx context.Context, id uint, status models.RequestStatusType) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequestStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, models.RequestStatusType) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestService_UpdateRequestStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequestStatus'
type MockRequestService_UpdateRequestStatus_Call struct {
	*mock.Call
}

// UpdateRequestStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - status models.RequestStatusType
func (_e *MockRequestService_Expecter) UpdateRequestStatus(ctx interface{}, id interface{}, status interface{}) *MockRequestService_UpdateRequestStatus_Call {
	return &MockRequestService_UpdateRequestStatus_Call{Call: _e.mock.On("UpdateRequestStatus", ctx, id, status)}
}

func (_c *MockRequestService_UpdateRequestStatus_Call) Run(run func(ctx context.Context, id uint, status models.RequestStatusType)) *MockRequestService_UpdateRequestStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(models.RequestStatusType))
	})
	return _c
}

func (_c *MockRequestService_UpdateRequestStatus_Call) Return(_a0 error) *MockRequestService_UpdateRequestStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestService_UpdateRequestStatus_Call) RunAndReturn(run func(context.Context, uint, models.RequestStatusType) error) *MockRequestService_UpdateRequestStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestService creates a new instance of MockRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestService {
	mock := &MockRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
