// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockRoutableAPI is an autogenerated mock type for the RoutableAPI type
type MockRoutableAPI struct {
	mock.Mock
}

type MockRoutableAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoutableAPI) EXPECT() *MockRoutableAPI_Expecter {
	return &MockRoutableAPI_Expecter{mock: &_m.Mock}
}

// Can provides a mock function with given fields: w, r
func (_m *MockRoutableAPI) Can(w http.ResponseWriter, r *http.Request) bool {
	ret := _m.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for Can")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) bool); ok {
		r0 = rf(w, r)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockRoutableAPI_Can_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Can'
type MockRoutableAPI_Can_Call struct {
	*mock.Call
}

// Can is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRoutableAPI_Expecter) Can(w interface{}, r interface{}) *MockRoutableAPI_Can_Call {
	return &MockRoutableAPI_Can_Call{Call: _e.mock.On("Can", w, r)}
}

func (_c *MockRoutableAPI_Can_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRoutableAPI_Can_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockRoutableAPI_Can_Call) Return(_a0 bool) *MockRoutableAPI_Can_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoutableAPI_Can_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request) bool) *MockRoutableAPI_Can_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function with given fields: w, r
func (_m *MockRoutableAPI) Handle(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockRoutableAPI_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockRoutableAPI_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockRoutableAPI_Expecter) Handle(w interface{}, r interface{}) *MockRoutableAPI_Handle_Call {
	return &MockRoutableAPI_Handle_Call{Call: _e.mock.On("Handle", w, r)}
}

func (_c *MockRoutableAPI_Handle_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockRoutableAPI_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockRoutableAPI_Handle_Call) Return() *MockRoutableAPI_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRoutableAPI_Handle_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockRoutableAPI_Handle_Call {
	_c.Run(run)
	return _c
}

// NewMockRoutableAPI creates a new instance of MockRoutableAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoutableAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoutableAPI {
	mock := &MockRoutableAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
