// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockService
func (_mock *MockService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockService_Expecter) Config() *MockService_Config_Call {
	return &MockService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockService_Config_Call) Run(run func()) *MockService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Config_Call) Return(manager config.Manager) *MockService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockService_Config_Call) RunAndReturn(run func() config.Manager) *MockService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockService
func (_mock *MockService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockService_Expecter) Context() *MockService_Context_Call {
	return &MockService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockService_Context_Call) Run(run func()) *MockService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Context_Call) Return(context core.Context) *MockService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockService_Context_Call) RunAndReturn(run func() core.Context) *MockService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockService
func (_mock *MockService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockService_Expecter) DB() *MockService_DB_Call {
	return &MockService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockService_DB_Call) Run(run func()) *MockService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_DB_Call) Return(dB *gorm.DB) *MockService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockService
func (_mock *MockService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockService_Expecter) ID() *MockService_ID_Call {
	return &MockService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockService_ID_Call) Run(run func()) *MockService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_ID_Call) Return(s string) *MockService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockService_ID_Call) RunAndReturn(run func() string) *MockService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockService
func (_mock *MockService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockService_Expecter) Logger() *MockService_Logger_Call {
	return &MockService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockService_Logger_Call) Run(run func()) *MockService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Logger_Call) Return(logger *core.Logger) *MockService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockService
func (_mock *MockService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockService_Expecter) SetConfig(cfg any) *MockService_SetConfig_Call {
	return &MockService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_SetConfig_Call) Return() *MockService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockService
func (_mock *MockService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockService_Expecter) SetContext(ctx any) *MockService_SetContext_Call {
	return &MockService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockService_SetContext_Call) Run(run func(ctx core.Context)) *MockService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_SetContext_Call) Return() *MockService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockService
func (_mock *MockService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockService_Expecter) SetDB(db any) *MockService_SetDB_Call {
	return &MockService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockService_SetDB_Call) Run(run func(db *gorm.DB)) *MockService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_SetDB_Call) Return() *MockService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockService
func (_mock *MockService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockService_Expecter) SetLogger(logger any) *MockService_SetLogger_Call {
	return &MockService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_SetLogger_Call) Return() *MockService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockService_SetLogger_Call {
	_c.Run(run)
	return _c
}
