// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"time"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/portal/db/models"
	"gorm.io/gorm"
)

// NewMockStorageService creates a new instance of MockStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageService {
	mock := &MockStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageService is an autogenerated mock type for the StorageService type
type MockStorageService struct {
	mock.Mock
}

type MockStorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageService) EXPECT() *MockStorageService_Expecter {
	return &MockStorageService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockStorageService
func (_mock *MockStorageService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockStorageService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockStorageService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockStorageService_Expecter) Config() *MockStorageService_Config_Call {
	return &MockStorageService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockStorageService_Config_Call) Run(run func()) *MockStorageService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageService_Config_Call) Return(manager config.Manager) *MockStorageService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockStorageService_Config_Call) RunAndReturn(run func() config.Manager) *MockStorageService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockStorageService
func (_mock *MockStorageService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockStorageService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockStorageService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockStorageService_Expecter) Context() *MockStorageService_Context_Call {
	return &MockStorageService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockStorageService_Context_Call) Run(run func()) *MockStorageService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageService_Context_Call) Return(context core.Context) *MockStorageService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockStorageService_Context_Call) RunAndReturn(run func() core.Context) *MockStorageService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockStorageService
func (_mock *MockStorageService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockStorageService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockStorageService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockStorageService_Expecter) DB() *MockStorageService_DB_Call {
	return &MockStorageService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockStorageService_DB_Call) Run(run func()) *MockStorageService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageService_DB_Call) Return(dB *gorm.DB) *MockStorageService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockStorageService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockStorageService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type MockStorageService
func (_mock *MockStorageService) DeleteObject(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash) error {
	ret := _mock.Called(ctx, protocol, objectHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, core.StorageHash) error); ok {
		r0 = returnFunc(ctx, protocol, objectHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageService_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockStorageService_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - objectHash core.StorageHash
func (_e *MockStorageService_Expecter) DeleteObject(ctx any, protocol any, objectHash any) *MockStorageService_DeleteObject_Call {
	return &MockStorageService_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, protocol, objectHash)}
}

func (_c *MockStorageService_DeleteObject_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash)) *MockStorageService_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 core.StorageHash
		if args[2] != nil {
			arg2 = args[2].(core.StorageHash)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_DeleteObject_Call) Return(err error) *MockStorageService_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageService_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash) error) *MockStorageService_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObjectProof provides a mock function for the type MockStorageService
func (_mock *MockStorageService) DeleteObjectProof(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash) error {
	ret := _mock.Called(ctx, protocol, objectHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjectProof")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, core.StorageHash) error); ok {
		r0 = returnFunc(ctx, protocol, objectHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageService_DeleteObjectProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjectProof'
type MockStorageService_DeleteObjectProof_Call struct {
	*mock.Call
}

// DeleteObjectProof is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - objectHash core.StorageHash
func (_e *MockStorageService_Expecter) DeleteObjectProof(ctx any, protocol any, objectHash any) *MockStorageService_DeleteObjectProof_Call {
	return &MockStorageService_DeleteObjectProof_Call{Call: _e.mock.On("DeleteObjectProof", ctx, protocol, objectHash)}
}

func (_c *MockStorageService_DeleteObjectProof_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash)) *MockStorageService_DeleteObjectProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 core.StorageHash
		if args[2] != nil {
			arg2 = args[2].(core.StorageHash)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_DeleteObjectProof_Call) Return(err error) *MockStorageService_DeleteObjectProof_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageService_DeleteObjectProof_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash) error) *MockStorageService_DeleteObjectProof_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadObject provides a mock function for the type MockStorageService
func (_mock *MockStorageService) DownloadObject(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash, start int64) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, protocol, objectHash, start)

	if len(ret) == 0 {
		panic("no return value specified for DownloadObject")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, core.StorageHash, int64) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, protocol, objectHash, start)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, core.StorageHash, int64) io.ReadCloser); ok {
		r0 = returnFunc(ctx, protocol, objectHash, start)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.StorageProtocol, core.StorageHash, int64) error); ok {
		r1 = returnFunc(ctx, protocol, objectHash, start)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_DownloadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadObject'
type MockStorageService_DownloadObject_Call struct {
	*mock.Call
}

// DownloadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - objectHash core.StorageHash
//   - start int64
func (_e *MockStorageService_Expecter) DownloadObject(ctx any, protocol any, objectHash any, start any) *MockStorageService_DownloadObject_Call {
	return &MockStorageService_DownloadObject_Call{Call: _e.mock.On("DownloadObject", ctx, protocol, objectHash, start)}
}

func (_c *MockStorageService_DownloadObject_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash, start int64)) *MockStorageService_DownloadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 core.StorageHash
		if args[2] != nil {
			arg2 = args[2].(core.StorageHash)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorageService_DownloadObject_Call) Return(readCloser io.ReadCloser, err error) *MockStorageService_DownloadObject_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockStorageService_DownloadObject_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash, start int64) (io.ReadCloser, error)) *MockStorageService_DownloadObject_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadObjectProof provides a mock function for the type MockStorageService
func (_mock *MockStorageService) DownloadObjectProof(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, protocol, objectHash)

	if len(ret) == 0 {
		panic("no return value specified for DownloadObjectProof")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, core.StorageHash) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, protocol, objectHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, core.StorageHash) io.ReadCloser); ok {
		r0 = returnFunc(ctx, protocol, objectHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.StorageProtocol, core.StorageHash) error); ok {
		r1 = returnFunc(ctx, protocol, objectHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_DownloadObjectProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadObjectProof'
type MockStorageService_DownloadObjectProof_Call struct {
	*mock.Call
}

// DownloadObjectProof is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - objectHash core.StorageHash
func (_e *MockStorageService_Expecter) DownloadObjectProof(ctx any, protocol any, objectHash any) *MockStorageService_DownloadObjectProof_Call {
	return &MockStorageService_DownloadObjectProof_Call{Call: _e.mock.On("DownloadObjectProof", ctx, protocol, objectHash)}
}

func (_c *MockStorageService_DownloadObjectProof_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash)) *MockStorageService_DownloadObjectProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 core.StorageHash
		if args[2] != nil {
			arg2 = args[2].(core.StorageHash)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_DownloadObjectProof_Call) Return(readCloser io.ReadCloser, err error) *MockStorageService_DownloadObjectProof_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockStorageService_DownloadObjectProof_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash) (io.ReadCloser, error)) *MockStorageService_DownloadObjectProof_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadObjectWithOptions provides a mock function for the type MockStorageService
func (_mock *MockStorageService) DownloadObjectWithOptions(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash, opts ...core.StorageOptionFunc) (io.ReadCloser, error) {
	// core.StorageOptionFunc
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, protocol, objectHash)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DownloadObjectWithOptions")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, core.StorageHash, ...core.StorageOptionFunc) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, protocol, objectHash, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, core.StorageHash, ...core.StorageOptionFunc) io.ReadCloser); ok {
		r0 = returnFunc(ctx, protocol, objectHash, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.StorageProtocol, core.StorageHash, ...core.StorageOptionFunc) error); ok {
		r1 = returnFunc(ctx, protocol, objectHash, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_DownloadObjectWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadObjectWithOptions'
type MockStorageService_DownloadObjectWithOptions_Call struct {
	*mock.Call
}

// DownloadObjectWithOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - objectHash core.StorageHash
//   - opts ...core.StorageOptionFunc
func (_e *MockStorageService_Expecter) DownloadObjectWithOptions(ctx any, protocol any, objectHash any, opts ...any) *MockStorageService_DownloadObjectWithOptions_Call {
	return &MockStorageService_DownloadObjectWithOptions_Call{Call: _e.mock.On("DownloadObjectWithOptions",
		append([]any{ctx, protocol, objectHash}, opts...)...)}
}

func (_c *MockStorageService_DownloadObjectWithOptions_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash, opts ...core.StorageOptionFunc)) *MockStorageService_DownloadObjectWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 core.StorageHash
		if args[2] != nil {
			arg2 = args[2].(core.StorageHash)
		}
		var arg3 []core.StorageOptionFunc
		variadicArgs := make([]core.StorageOptionFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(core.StorageOptionFunc)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockStorageService_DownloadObjectWithOptions_Call) Return(readCloser io.ReadCloser, err error) *MockStorageService_DownloadObjectWithOptions_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockStorageService_DownloadObjectWithOptions_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, objectHash core.StorageHash, opts ...core.StorageOptionFunc) (io.ReadCloser, error)) *MockStorageService_DownloadObjectWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemporaryUploadDir provides a mock function for the type MockStorageService
func (_mock *MockStorageService) GetTemporaryUploadDir(protocol core.StorageProtocol) string {
	ret := _mock.Called(protocol)

	if len(ret) == 0 {
		panic("no return value specified for GetTemporaryUploadDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(core.StorageProtocol) string); ok {
		r0 = returnFunc(protocol)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStorageService_GetTemporaryUploadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemporaryUploadDir'
type MockStorageService_GetTemporaryUploadDir_Call struct {
	*mock.Call
}

// GetTemporaryUploadDir is a helper method to define mock.On call
//   - protocol core.StorageProtocol
func (_e *MockStorageService_Expecter) GetTemporaryUploadDir(protocol any) *MockStorageService_GetTemporaryUploadDir_Call {
	return &MockStorageService_GetTemporaryUploadDir_Call{Call: _e.mock.On("GetTemporaryUploadDir", protocol)}
}

func (_c *MockStorageService_GetTemporaryUploadDir_Call) Run(run func(protocol core.StorageProtocol)) *MockStorageService_GetTemporaryUploadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.StorageProtocol
		if args[0] != nil {
			arg0 = args[0].(core.StorageProtocol)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageService_GetTemporaryUploadDir_Call) Return(s string) *MockStorageService_GetTemporaryUploadDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStorageService_GetTemporaryUploadDir_Call) RunAndReturn(run func(protocol core.StorageProtocol) string) *MockStorageService_GetTemporaryUploadDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemporaryUploadPath provides a mock function for the type MockStorageService
func (_mock *MockStorageService) GetTemporaryUploadPath(protocol core.StorageProtocol, uploadId string) string {
	ret := _mock.Called(protocol, uploadId)

	if len(ret) == 0 {
		panic("no return value specified for GetTemporaryUploadPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(core.StorageProtocol, string) string); ok {
		r0 = returnFunc(protocol, uploadId)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStorageService_GetTemporaryUploadPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemporaryUploadPath'
type MockStorageService_GetTemporaryUploadPath_Call struct {
	*mock.Call
}

// GetTemporaryUploadPath is a helper method to define mock.On call
//   - protocol core.StorageProtocol
//   - uploadId string
func (_e *MockStorageService_Expecter) GetTemporaryUploadPath(protocol any, uploadId any) *MockStorageService_GetTemporaryUploadPath_Call {
	return &MockStorageService_GetTemporaryUploadPath_Call{Call: _e.mock.On("GetTemporaryUploadPath", protocol, uploadId)}
}

func (_c *MockStorageService_GetTemporaryUploadPath_Call) Run(run func(protocol core.StorageProtocol, uploadId string)) *MockStorageService_GetTemporaryUploadPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.StorageProtocol
		if args[0] != nil {
			arg0 = args[0].(core.StorageProtocol)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageService_GetTemporaryUploadPath_Call) Return(s string) *MockStorageService_GetTemporaryUploadPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStorageService_GetTemporaryUploadPath_Call) RunAndReturn(run func(protocol core.StorageProtocol, uploadId string) string) *MockStorageService_GetTemporaryUploadPath_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockStorageService
func (_mock *MockStorageService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStorageService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockStorageService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockStorageService_Expecter) ID() *MockStorageService_ID_Call {
	return &MockStorageService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockStorageService_ID_Call) Run(run func()) *MockStorageService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageService_ID_Call) Return(s string) *MockStorageService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStorageService_ID_Call) RunAndReturn(run func() string) *MockStorageService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockStorageService
func (_mock *MockStorageService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockStorageService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockStorageService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockStorageService_Expecter) Logger() *MockStorageService_Logger_Call {
	return &MockStorageService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockStorageService_Logger_Call) Run(run func()) *MockStorageService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageService_Logger_Call) Return(logger *core.Logger) *MockStorageService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockStorageService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockStorageService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// S3Client provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3Client(ctx context.Context) (*s3.Client, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for S3Client")
	}

	var r0 *s3.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*s3.Client, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *s3.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_S3Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3Client'
type MockStorageService_S3Client_Call struct {
	*mock.Call
}

// S3Client is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageService_Expecter) S3Client(ctx any) *MockStorageService_S3Client_Call {
	return &MockStorageService_S3Client_Call{Call: _e.mock.On("S3Client", ctx)}
}

func (_c *MockStorageService_S3Client_Call) Run(run func(ctx context.Context)) *MockStorageService_S3Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageService_S3Client_Call) Return(client *s3.Client, err error) *MockStorageService_S3Client_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockStorageService_S3Client_Call) RunAndReturn(run func(ctx context.Context) (*s3.Client, error)) *MockStorageService_S3Client_Call {
	_c.Call.Return(run)
	return _c
}

// S3Delete provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3Delete(ctx context.Context, bucket string, key string) error {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for S3Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageService_S3Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3Delete'
type MockStorageService_S3Delete_Call struct {
	*mock.Call
}

// S3Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockStorageService_Expecter) S3Delete(ctx any, bucket any, key any) *MockStorageService_S3Delete_Call {
	return &MockStorageService_S3Delete_Call{Call: _e.mock.On("S3Delete", ctx, bucket, key)}
}

func (_c *MockStorageService_S3Delete_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockStorageService_S3Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_S3Delete_Call) Return(err error) *MockStorageService_S3Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageService_S3Delete_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) error) *MockStorageService_S3Delete_Call {
	_c.Call.Return(run)
	return _c
}

// S3DeleteTemporaryUpload provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3DeleteTemporaryUpload(ctx context.Context, protocol core.StorageProtocol, uploadId string) error {
	ret := _mock.Called(ctx, protocol, uploadId)

	if len(ret) == 0 {
		panic("no return value specified for S3DeleteTemporaryUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, string) error); ok {
		r0 = returnFunc(ctx, protocol, uploadId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageService_S3DeleteTemporaryUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3DeleteTemporaryUpload'
type MockStorageService_S3DeleteTemporaryUpload_Call struct {
	*mock.Call
}

// S3DeleteTemporaryUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - uploadId string
func (_e *MockStorageService_Expecter) S3DeleteTemporaryUpload(ctx any, protocol any, uploadId any) *MockStorageService_S3DeleteTemporaryUpload_Call {
	return &MockStorageService_S3DeleteTemporaryUpload_Call{Call: _e.mock.On("S3DeleteTemporaryUpload", ctx, protocol, uploadId)}
}

func (_c *MockStorageService_S3DeleteTemporaryUpload_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, uploadId string)) *MockStorageService_S3DeleteTemporaryUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_S3DeleteTemporaryUpload_Call) Return(err error) *MockStorageService_S3DeleteTemporaryUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageService_S3DeleteTemporaryUpload_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, uploadId string) error) *MockStorageService_S3DeleteTemporaryUpload_Call {
	_c.Call.Return(run)
	return _c
}

// S3Download provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3Download(ctx context.Context, bucket string, key string) (io.ReadSeekCloser, error) {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for S3Download")
	}

	var r0 io.ReadSeekCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (io.ReadSeekCloser, error)); ok {
		return returnFunc(ctx, bucket, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) io.ReadSeekCloser); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeekCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_S3Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3Download'
type MockStorageService_S3Download_Call struct {
	*mock.Call
}

// S3Download is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockStorageService_Expecter) S3Download(ctx any, bucket any, key any) *MockStorageService_S3Download_Call {
	return &MockStorageService_S3Download_Call{Call: _e.mock.On("S3Download", ctx, bucket, key)}
}

func (_c *MockStorageService_S3Download_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockStorageService_S3Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_S3Download_Call) Return(readSeekCloser io.ReadSeekCloser, err error) *MockStorageService_S3Download_Call {
	_c.Call.Return(readSeekCloser, err)
	return _c
}

func (_c *MockStorageService_S3Download_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) (io.ReadSeekCloser, error)) *MockStorageService_S3Download_Call {
	_c.Call.Return(run)
	return _c
}

// S3Exists provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3Exists(ctx context.Context, bucket string, key string) (bool, error) {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for S3Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, bucket, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_S3Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3Exists'
type MockStorageService_S3Exists_Call struct {
	*mock.Call
}

// S3Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockStorageService_Expecter) S3Exists(ctx any, bucket any, key any) *MockStorageService_S3Exists_Call {
	return &MockStorageService_S3Exists_Call{Call: _e.mock.On("S3Exists", ctx, bucket, key)}
}

func (_c *MockStorageService_S3Exists_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockStorageService_S3Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_S3Exists_Call) Return(b bool, err error) *MockStorageService_S3Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorageService_S3Exists_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) (bool, error)) *MockStorageService_S3Exists_Call {
	_c.Call.Return(run)
	return _c
}

// S3GetTemporaryUpload provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3GetTemporaryUpload(ctx context.Context, protocol core.StorageProtocol, uploadId string) (io.ReadSeekCloser, error) {
	ret := _mock.Called(ctx, protocol, uploadId)

	if len(ret) == 0 {
		panic("no return value specified for S3GetTemporaryUpload")
	}

	var r0 io.ReadSeekCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, string) (io.ReadSeekCloser, error)); ok {
		return returnFunc(ctx, protocol, uploadId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, string) io.ReadSeekCloser); ok {
		r0 = returnFunc(ctx, protocol, uploadId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeekCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.StorageProtocol, string) error); ok {
		r1 = returnFunc(ctx, protocol, uploadId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_S3GetTemporaryUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3GetTemporaryUpload'
type MockStorageService_S3GetTemporaryUpload_Call struct {
	*mock.Call
}

// S3GetTemporaryUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - uploadId string
func (_e *MockStorageService_Expecter) S3GetTemporaryUpload(ctx any, protocol any, uploadId any) *MockStorageService_S3GetTemporaryUpload_Call {
	return &MockStorageService_S3GetTemporaryUpload_Call{Call: _e.mock.On("S3GetTemporaryUpload", ctx, protocol, uploadId)}
}

func (_c *MockStorageService_S3GetTemporaryUpload_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, uploadId string)) *MockStorageService_S3GetTemporaryUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_S3GetTemporaryUpload_Call) Return(readSeekCloser io.ReadSeekCloser, err error) *MockStorageService_S3GetTemporaryUpload_Call {
	_c.Call.Return(readSeekCloser, err)
	return _c
}

func (_c *MockStorageService_S3GetTemporaryUpload_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, uploadId string) (io.ReadSeekCloser, error)) *MockStorageService_S3GetTemporaryUpload_Call {
	_c.Call.Return(run)
	return _c
}

// S3MultipartUpload provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3MultipartUpload(ctx context.Context, data io.ReadCloser, bucket string, key string, size uint64) error {
	ret := _mock.Called(ctx, data, bucket, key, size)

	if len(ret) == 0 {
		panic("no return value specified for S3MultipartUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadCloser, string, string, uint64) error); ok {
		r0 = returnFunc(ctx, data, bucket, key, size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageService_S3MultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3MultipartUpload'
type MockStorageService_S3MultipartUpload_Call struct {
	*mock.Call
}

// S3MultipartUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - data io.ReadCloser
//   - bucket string
//   - key string
//   - size uint64
func (_e *MockStorageService_Expecter) S3MultipartUpload(ctx any, data any, bucket any, key any, size any) *MockStorageService_S3MultipartUpload_Call {
	return &MockStorageService_S3MultipartUpload_Call{Call: _e.mock.On("S3MultipartUpload", ctx, data, bucket, key, size)}
}

func (_c *MockStorageService_S3MultipartUpload_Call) Run(run func(ctx context.Context, data io.ReadCloser, bucket string, key string, size uint64)) *MockStorageService_S3MultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.ReadCloser
		if args[1] != nil {
			arg1 = args[1].(io.ReadCloser)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorageService_S3MultipartUpload_Call) Return(err error) *MockStorageService_S3MultipartUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageService_S3MultipartUpload_Call) RunAndReturn(run func(ctx context.Context, data io.ReadCloser, bucket string, key string, size uint64) error) *MockStorageService_S3MultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// S3TemporaryUpload provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3TemporaryUpload(ctx context.Context, data io.ReadCloser, size uint64, protocol core.StorageProtocol, opts ...func(*core.S3TempUploadOptions)) (string, error) {
	// func(*core.S3TempUploadOptions)
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, data, size, protocol)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for S3TemporaryUpload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadCloser, uint64, core.StorageProtocol, ...func(*core.S3TempUploadOptions)) (string, error)); ok {
		return returnFunc(ctx, data, size, protocol, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadCloser, uint64, core.StorageProtocol, ...func(*core.S3TempUploadOptions)) string); ok {
		r0 = returnFunc(ctx, data, size, protocol, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.ReadCloser, uint64, core.StorageProtocol, ...func(*core.S3TempUploadOptions)) error); ok {
		r1 = returnFunc(ctx, data, size, protocol, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_S3TemporaryUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3TemporaryUpload'
type MockStorageService_S3TemporaryUpload_Call struct {
	*mock.Call
}

// S3TemporaryUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - data io.ReadCloser
//   - size uint64
//   - protocol core.StorageProtocol
//   - opts ...func(*core.S3TempUploadOptions)
func (_e *MockStorageService_Expecter) S3TemporaryUpload(ctx any, data any, size any, protocol any, opts ...any) *MockStorageService_S3TemporaryUpload_Call {
	return &MockStorageService_S3TemporaryUpload_Call{Call: _e.mock.On("S3TemporaryUpload",
		append([]any{ctx, data, size, protocol}, opts...)...)}
}

func (_c *MockStorageService_S3TemporaryUpload_Call) Run(run func(ctx context.Context, data io.ReadCloser, size uint64, protocol core.StorageProtocol, opts ...func(*core.S3TempUploadOptions))) *MockStorageService_S3TemporaryUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.ReadCloser
		if args[1] != nil {
			arg1 = args[1].(io.ReadCloser)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 core.StorageProtocol
		if args[3] != nil {
			arg3 = args[3].(core.StorageProtocol)
		}
		var arg4 []func(*core.S3TempUploadOptions)
		variadicArgs := make([]func(*core.S3TempUploadOptions), len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(func(*core.S3TempUploadOptions))
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockStorageService_S3TemporaryUpload_Call) Return(s string, err error) *MockStorageService_S3TemporaryUpload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStorageService_S3TemporaryUpload_Call) RunAndReturn(run func(ctx context.Context, data io.ReadCloser, size uint64, protocol core.StorageProtocol, opts ...func(*core.S3TempUploadOptions)) (string, error)) *MockStorageService_S3TemporaryUpload_Call {
	_c.Call.Return(run)
	return _c
}

// S3TemporaryUploadExists provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3TemporaryUploadExists(ctx context.Context, protocol core.StorageProtocol, uploadId string) (bool, error) {
	ret := _mock.Called(ctx, protocol, uploadId)

	if len(ret) == 0 {
		panic("no return value specified for S3TemporaryUploadExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, string) (bool, error)); ok {
		return returnFunc(ctx, protocol, uploadId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, string) bool); ok {
		r0 = returnFunc(ctx, protocol, uploadId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.StorageProtocol, string) error); ok {
		r1 = returnFunc(ctx, protocol, uploadId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_S3TemporaryUploadExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3TemporaryUploadExists'
type MockStorageService_S3TemporaryUploadExists_Call struct {
	*mock.Call
}

// S3TemporaryUploadExists is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - uploadId string
func (_e *MockStorageService_Expecter) S3TemporaryUploadExists(ctx any, protocol any, uploadId any) *MockStorageService_S3TemporaryUploadExists_Call {
	return &MockStorageService_S3TemporaryUploadExists_Call{Call: _e.mock.On("S3TemporaryUploadExists", ctx, protocol, uploadId)}
}

func (_c *MockStorageService_S3TemporaryUploadExists_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, uploadId string)) *MockStorageService_S3TemporaryUploadExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_S3TemporaryUploadExists_Call) Return(b bool, err error) *MockStorageService_S3TemporaryUploadExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorageService_S3TemporaryUploadExists_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, uploadId string) (bool, error)) *MockStorageService_S3TemporaryUploadExists_Call {
	_c.Call.Return(run)
	return _c
}

// S3Upload provides a mock function for the type MockStorageService
func (_mock *MockStorageService) S3Upload(ctx context.Context, bucket string, key string, data io.Reader) error {
	ret := _mock.Called(ctx, bucket, key, data)

	if len(ret) == 0 {
		panic("no return value specified for S3Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) error); ok {
		r0 = returnFunc(ctx, bucket, key, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageService_S3Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3Upload'
type MockStorageService_S3Upload_Call struct {
	*mock.Call
}

// S3Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - data io.Reader
func (_e *MockStorageService_Expecter) S3Upload(ctx any, bucket any, key any, data any) *MockStorageService_S3Upload_Call {
	return &MockStorageService_S3Upload_Call{Call: _e.mock.On("S3Upload", ctx, bucket, key, data)}
}

func (_c *MockStorageService_S3Upload_Call) Run(run func(ctx context.Context, bucket string, key string, data io.Reader)) *MockStorageService_S3Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorageService_S3Upload_Call) Return(err error) *MockStorageService_S3Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageService_S3Upload_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string, data io.Reader) error) *MockStorageService_S3Upload_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockStorageService
func (_mock *MockStorageService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockStorageService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockStorageService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockStorageService_Expecter) SetConfig(cfg any) *MockStorageService_SetConfig_Call {
	return &MockStorageService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockStorageService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockStorageService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageService_SetConfig_Call) Return() *MockStorageService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorageService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockStorageService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockStorageService
func (_mock *MockStorageService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockStorageService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockStorageService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockStorageService_Expecter) SetContext(ctx any) *MockStorageService_SetContext_Call {
	return &MockStorageService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockStorageService_SetContext_Call) Run(run func(ctx core.Context)) *MockStorageService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageService_SetContext_Call) Return() *MockStorageService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorageService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockStorageService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockStorageService
func (_mock *MockStorageService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockStorageService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockStorageService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockStorageService_Expecter) SetDB(db any) *MockStorageService_SetDB_Call {
	return &MockStorageService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockStorageService_SetDB_Call) Run(run func(db *gorm.DB)) *MockStorageService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageService_SetDB_Call) Return() *MockStorageService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorageService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockStorageService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockStorageService
func (_mock *MockStorageService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockStorageService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockStorageService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockStorageService_Expecter) SetLogger(logger any) *MockStorageService_SetLogger_Call {
	return &MockStorageService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockStorageService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockStorageService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageService_SetLogger_Call) Return() *MockStorageService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorageService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockStorageService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// UploadObject provides a mock function for the type MockStorageService
func (_mock *MockStorageService) UploadObject(ctx context.Context, request core.StorageUploadRequest) (*models.Upload, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UploadObject")
	}

	var r0 *models.Upload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageUploadRequest) (*models.Upload, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageUploadRequest) *models.Upload); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Upload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.StorageUploadRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageService_UploadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadObject'
type MockStorageService_UploadObject_Call struct {
	*mock.Call
}

// UploadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - request core.StorageUploadRequest
func (_e *MockStorageService_Expecter) UploadObject(ctx any, request any) *MockStorageService_UploadObject_Call {
	return &MockStorageService_UploadObject_Call{Call: _e.mock.On("UploadObject", ctx, request)}
}

func (_c *MockStorageService_UploadObject_Call) Run(run func(ctx context.Context, request core.StorageUploadRequest)) *MockStorageService_UploadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageUploadRequest
		if args[1] != nil {
			arg1 = args[1].(core.StorageUploadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageService_UploadObject_Call) Return(upload *models.Upload, err error) *MockStorageService_UploadObject_Call {
	_c.Call.Return(upload, err)
	return _c
}

func (_c *MockStorageService_UploadObject_Call) RunAndReturn(run func(ctx context.Context, request core.StorageUploadRequest) (*models.Upload, error)) *MockStorageService_UploadObject_Call {
	_c.Call.Return(run)
	return _c
}

// UploadObjectProof provides a mock function for the type MockStorageService
func (_mock *MockStorageService) UploadObjectProof(ctx context.Context, protocol core.StorageProtocol, data io.ReadSeeker, proof core.StorageHash, size uint64) error {
	ret := _mock.Called(ctx, protocol, data, proof, size)

	if len(ret) == 0 {
		panic("no return value specified for UploadObjectProof")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, io.ReadSeeker, core.StorageHash, uint64) error); ok {
		r0 = returnFunc(ctx, protocol, data, proof, size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageService_UploadObjectProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadObjectProof'
type MockStorageService_UploadObjectProof_Call struct {
	*mock.Call
}

// UploadObjectProof is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - data io.ReadSeeker
//   - proof core.StorageHash
//   - size uint64
func (_e *MockStorageService_Expecter) UploadObjectProof(ctx any, protocol any, data any, proof any, size any) *MockStorageService_UploadObjectProof_Call {
	return &MockStorageService_UploadObjectProof_Call{Call: _e.mock.On("UploadObjectProof", ctx, protocol, data, proof, size)}
}

func (_c *MockStorageService_UploadObjectProof_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, data io.ReadSeeker, proof core.StorageHash, size uint64)) *MockStorageService_UploadObjectProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 io.ReadSeeker
		if args[2] != nil {
			arg2 = args[2].(io.ReadSeeker)
		}
		var arg3 core.StorageHash
		if args[3] != nil {
			arg3 = args[3].(core.StorageHash)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorageService_UploadObjectProof_Call) Return(err error) *MockStorageService_UploadObjectProof_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageService_UploadObjectProof_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, data io.ReadSeeker, proof core.StorageHash, size uint64) error) *MockStorageService_UploadObjectProof_Call {
	_c.Call.Return(run)
	return _c
}

// UploadStatus provides a mock function for the type MockStorageService
func (_mock *MockStorageService) UploadStatus(ctx context.Context, protocol core.StorageProtocol, objectName string) (core.StorageUploadStatus, *time.Time, error) {
	ret := _mock.Called(ctx, protocol, objectName)

	if len(ret) == 0 {
		panic("no return value specified for UploadStatus")
	}

	var r0 core.StorageUploadStatus
	var r1 *time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, string) (core.StorageUploadStatus, *time.Time, error)); ok {
		return returnFunc(ctx, protocol, objectName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.StorageProtocol, string) core.StorageUploadStatus); ok {
		r0 = returnFunc(ctx, protocol, objectName)
	} else {
		r0 = ret.Get(0).(core.StorageUploadStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.StorageProtocol, string) *time.Time); ok {
		r1 = returnFunc(ctx, protocol, objectName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, core.StorageProtocol, string) error); ok {
		r2 = returnFunc(ctx, protocol, objectName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorageService_UploadStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadStatus'
type MockStorageService_UploadStatus_Call struct {
	*mock.Call
}

// UploadStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - protocol core.StorageProtocol
//   - objectName string
func (_e *MockStorageService_Expecter) UploadStatus(ctx any, protocol any, objectName any) *MockStorageService_UploadStatus_Call {
	return &MockStorageService_UploadStatus_Call{Call: _e.mock.On("UploadStatus", ctx, protocol, objectName)}
}

func (_c *MockStorageService_UploadStatus_Call) Run(run func(ctx context.Context, protocol core.StorageProtocol, objectName string)) *MockStorageService_UploadStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.StorageProtocol
		if args[1] != nil {
			arg1 = args[1].(core.StorageProtocol)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageService_UploadStatus_Call) Return(storageUploadStatus core.StorageUploadStatus, time1 *time.Time, err error) *MockStorageService_UploadStatus_Call {
	_c.Call.Return(storageUploadStatus, time1, err)
	return _c
}

func (_c *MockStorageService_UploadStatus_Call) RunAndReturn(run func(ctx context.Context, protocol core.StorageProtocol, objectName string) (core.StorageUploadStatus, *time.Time, error)) *MockStorageService_UploadStatus_Call {
	_c.Call.Return(run)
	return _c
}
