// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	multihash "github.com/multiformats/go-multihash"
	mock "github.com/stretchr/testify/mock"
)

// MockStorageHash is an autogenerated mock type for the StorageHash type
type MockStorageHash struct {
	mock.Mock
}

type MockStorageHash_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageHash) EXPECT() *MockStorageHash_Expecter {
	return &MockStorageHash_Expecter{mock: &_m.Mock}
}

// CIDType provides a mock function with no fields
func (_m *MockStorageHash) CIDType() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CIDType")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockStorageHash_CIDType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CIDType'
type MockStorageHash_CIDType_Call struct {
	*mock.Call
}

// CIDType is a helper method to define mock.On call
func (_e *MockStorageHash_Expecter) CIDType() *MockStorageHash_CIDType_Call {
	return &MockStorageHash_CIDType_Call{Call: _e.mock.On("CIDType")}
}

func (_c *MockStorageHash_CIDType_Call) Run(run func()) *MockStorageHash_CIDType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageHash_CIDType_Call) Return(_a0 uint64) *MockStorageHash_CIDType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageHash_CIDType_Call) RunAndReturn(run func() uint64) *MockStorageHash_CIDType_Call {
	_c.Call.Return(run)
	return _c
}

// Multihash provides a mock function with no fields
func (_m *MockStorageHash) Multihash() multihash.Multihash {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Multihash")
	}

	var r0 multihash.Multihash
	if rf, ok := ret.Get(0).(func() multihash.Multihash); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(multihash.Multihash)
		}
	}

	return r0
}

// MockStorageHash_Multihash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Multihash'
type MockStorageHash_Multihash_Call struct {
	*mock.Call
}

// Multihash is a helper method to define mock.On call
func (_e *MockStorageHash_Expecter) Multihash() *MockStorageHash_Multihash_Call {
	return &MockStorageHash_Multihash_Call{Call: _e.mock.On("Multihash")}
}

func (_c *MockStorageHash_Multihash_Call) Run(run func()) *MockStorageHash_Multihash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageHash_Multihash_Call) Return(_a0 multihash.Multihash) *MockStorageHash_Multihash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageHash_Multihash_Call) RunAndReturn(run func() multihash.Multihash) *MockStorageHash_Multihash_Call {
	_c.Call.Return(run)
	return _c
}

// Proof provides a mock function with no fields
func (_m *MockStorageHash) Proof() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Proof")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// MockStorageHash_Proof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Proof'
type MockStorageHash_Proof_Call struct {
	*mock.Call
}

// Proof is a helper method to define mock.On call
func (_e *MockStorageHash_Expecter) Proof() *MockStorageHash_Proof_Call {
	return &MockStorageHash_Proof_Call{Call: _e.mock.On("Proof")}
}

func (_c *MockStorageHash_Proof_Call) Run(run func()) *MockStorageHash_Proof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageHash_Proof_Call) Return(_a0 []byte) *MockStorageHash_Proof_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageHash_Proof_Call) RunAndReturn(run func() []byte) *MockStorageHash_Proof_Call {
	_c.Call.Return(run)
	return _c
}

// ProofExists provides a mock function with no fields
func (_m *MockStorageHash) ProofExists() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProofExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockStorageHash_ProofExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProofExists'
type MockStorageHash_ProofExists_Call struct {
	*mock.Call
}

// ProofExists is a helper method to define mock.On call
func (_e *MockStorageHash_Expecter) ProofExists() *MockStorageHash_ProofExists_Call {
	return &MockStorageHash_ProofExists_Call{Call: _e.mock.On("ProofExists")}
}

func (_c *MockStorageHash_ProofExists_Call) Run(run func()) *MockStorageHash_ProofExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageHash_ProofExists_Call) Return(_a0 bool) *MockStorageHash_ProofExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageHash_ProofExists_Call) RunAndReturn(run func() bool) *MockStorageHash_ProofExists_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockStorageHash) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStorageHash_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockStorageHash_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockStorageHash_Expecter) String() *MockStorageHash_String_Call {
	return &MockStorageHash_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockStorageHash_String_Call) Run(run func()) *MockStorageHash_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageHash_String_Call) Return(_a0 string) *MockStorageHash_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageHash_String_Call) RunAndReturn(run func() string) *MockStorageHash_String_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with no fields
func (_m *MockStorageHash) Type() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockStorageHash_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockStorageHash_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockStorageHash_Expecter) Type() *MockStorageHash_Type_Call {
	return &MockStorageHash_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockStorageHash_Type_Call) Run(run func()) *MockStorageHash_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageHash_Type_Call) Return(_a0 uint64) *MockStorageHash_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorageHash_Type_Call) RunAndReturn(run func() uint64) *MockStorageHash_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageHash creates a new instance of MockStorageHash. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageHash(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageHash {
	mock := &MockStorageHash{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
