// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockTestingProtocolStorageStatsProvider creates a new instance of MockTestingProtocolStorageStatsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestingProtocolStorageStatsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestingProtocolStorageStatsProvider {
	mock := &MockTestingProtocolStorageStatsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestingProtocolStorageStatsProvider is an autogenerated mock type for the TestingProtocolStorageStatsProvider type
type MockTestingProtocolStorageStatsProvider struct {
	mock.Mock
}

type MockTestingProtocolStorageStatsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestingProtocolStorageStatsProvider) EXPECT() *MockTestingProtocolStorageStatsProvider_Expecter {
	return &MockTestingProtocolStorageStatsProvider_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockTestingProtocolStorageStatsProvider_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) Config() *MockTestingProtocolStorageStatsProvider_Config_Call {
	return &MockTestingProtocolStorageStatsProvider_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockTestingProtocolStorageStatsProvider_Config_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Config_Call) Return(manager config.Manager) *MockTestingProtocolStorageStatsProvider_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Config_Call) RunAndReturn(run func() config.Manager) *MockTestingProtocolStorageStatsProvider_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockTestingProtocolStorageStatsProvider_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) Context() *MockTestingProtocolStorageStatsProvider_Context_Call {
	return &MockTestingProtocolStorageStatsProvider_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockTestingProtocolStorageStatsProvider_Context_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Context_Call) Return(context core.Context) *MockTestingProtocolStorageStatsProvider_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Context_Call) RunAndReturn(run func() core.Context) *MockTestingProtocolStorageStatsProvider_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockTestingProtocolStorageStatsProvider_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) DB() *MockTestingProtocolStorageStatsProvider_DB_Call {
	return &MockTestingProtocolStorageStatsProvider_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockTestingProtocolStorageStatsProvider_DB_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_DB_Call) Return(dB *gorm.DB) *MockTestingProtocolStorageStatsProvider_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_DB_Call) RunAndReturn(run func() *gorm.DB) *MockTestingProtocolStorageStatsProvider_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) DisplayName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockTestingProtocolStorageStatsProvider_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) DisplayName() *MockTestingProtocolStorageStatsProvider_DisplayName_Call {
	return &MockTestingProtocolStorageStatsProvider_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *MockTestingProtocolStorageStatsProvider_DisplayName_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_DisplayName_Call) Return(s string) *MockTestingProtocolStorageStatsProvider_DisplayName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_DisplayName_Call) RunAndReturn(run func() string) *MockTestingProtocolStorageStatsProvider_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) GetConfig() config.ProtocolConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.ProtocolConfig
	if returnFunc, ok := ret.Get(0).(func() config.ProtocolConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ProtocolConfig)
		}
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockTestingProtocolStorageStatsProvider_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) GetConfig() *MockTestingProtocolStorageStatsProvider_GetConfig_Call {
	return &MockTestingProtocolStorageStatsProvider_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockTestingProtocolStorageStatsProvider_GetConfig_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_GetConfig_Call) Return(protocolConfig config.ProtocolConfig) *MockTestingProtocolStorageStatsProvider_GetConfig_Call {
	_c.Call.Return(protocolConfig)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_GetConfig_Call) RunAndReturn(run func() config.ProtocolConfig) *MockTestingProtocolStorageStatsProvider_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTestingProtocolStorageStatsProvider_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) ID() *MockTestingProtocolStorageStatsProvider_ID_Call {
	return &MockTestingProtocolStorageStatsProvider_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTestingProtocolStorageStatsProvider_ID_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_ID_Call) Return(s string) *MockTestingProtocolStorageStatsProvider_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_ID_Call) RunAndReturn(run func() string) *MockTestingProtocolStorageStatsProvider_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockTestingProtocolStorageStatsProvider_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) Logger() *MockTestingProtocolStorageStatsProvider_Logger_Call {
	return &MockTestingProtocolStorageStatsProvider_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockTestingProtocolStorageStatsProvider_Logger_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Logger_Call) Return(logger *core.Logger) *MockTestingProtocolStorageStatsProvider_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Logger_Call) RunAndReturn(run func() *core.Logger) *MockTestingProtocolStorageStatsProvider_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTestingProtocolStorageStatsProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) Name() *MockTestingProtocolStorageStatsProvider_Name_Call {
	return &MockTestingProtocolStorageStatsProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTestingProtocolStorageStatsProvider_Name_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Name_Call) Return(s string) *MockTestingProtocolStorageStatsProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Name_Call) RunAndReturn(run func() string) *MockTestingProtocolStorageStatsProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) Operations() []core.Operation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 []core.Operation
	if returnFunc, ok := ret.Get(0).(func() []core.Operation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Operation)
		}
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type MockTestingProtocolStorageStatsProvider_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) Operations() *MockTestingProtocolStorageStatsProvider_Operations_Call {
	return &MockTestingProtocolStorageStatsProvider_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *MockTestingProtocolStorageStatsProvider_Operations_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Operations_Call) Return(operations []core.Operation) *MockTestingProtocolStorageStatsProvider_Operations_Call {
	_c.Call.Return(operations)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Operations_Call) RunAndReturn(run func() []core.Operation) *MockTestingProtocolStorageStatsProvider_Operations_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockTestingProtocolStorageStatsProvider_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockTestingProtocolStorageStatsProvider_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) SetConfig(cfg interface{}) *MockTestingProtocolStorageStatsProvider_SetConfig_Call {
	return &MockTestingProtocolStorageStatsProvider_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockTestingProtocolStorageStatsProvider_SetConfig_Call) Run(run func(cfg config.Manager)) *MockTestingProtocolStorageStatsProvider_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_SetConfig_Call) Return() *MockTestingProtocolStorageStatsProvider_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockTestingProtocolStorageStatsProvider_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockTestingProtocolStorageStatsProvider_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockTestingProtocolStorageStatsProvider_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) SetContext(ctx interface{}) *MockTestingProtocolStorageStatsProvider_SetContext_Call {
	return &MockTestingProtocolStorageStatsProvider_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockTestingProtocolStorageStatsProvider_SetContext_Call) Run(run func(ctx core.Context)) *MockTestingProtocolStorageStatsProvider_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_SetContext_Call) Return() *MockTestingProtocolStorageStatsProvider_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockTestingProtocolStorageStatsProvider_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockTestingProtocolStorageStatsProvider_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockTestingProtocolStorageStatsProvider_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) SetDB(db interface{}) *MockTestingProtocolStorageStatsProvider_SetDB_Call {
	return &MockTestingProtocolStorageStatsProvider_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockTestingProtocolStorageStatsProvider_SetDB_Call) Run(run func(db *gorm.DB)) *MockTestingProtocolStorageStatsProvider_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_SetDB_Call) Return() *MockTestingProtocolStorageStatsProvider_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockTestingProtocolStorageStatsProvider_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockTestingProtocolStorageStatsProvider_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockTestingProtocolStorageStatsProvider_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) SetLogger(logger interface{}) *MockTestingProtocolStorageStatsProvider_SetLogger_Call {
	return &MockTestingProtocolStorageStatsProvider_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockTestingProtocolStorageStatsProvider_SetLogger_Call) Run(run func(logger *core.Logger)) *MockTestingProtocolStorageStatsProvider_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_SetLogger_Call) Return() *MockTestingProtocolStorageStatsProvider_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockTestingProtocolStorageStatsProvider_SetLogger_Call {
	_c.Run(run)
	return _c
}

// StorageStats provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) StorageStats(ctx context.Context) (*core.ProtocolStorageStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StorageStats")
	}

	var r0 *core.ProtocolStorageStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*core.ProtocolStorageStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *core.ProtocolStorageStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ProtocolStorageStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestingProtocolStorageStatsProvider_StorageStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageStats'
type MockTestingProtocolStorageStatsProvider_StorageStats_Call struct {
	*mock.Call
}

// StorageStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) StorageStats(ctx interface{}) *MockTestingProtocolStorageStatsProvider_StorageStats_Call {
	return &MockTestingProtocolStorageStatsProvider_StorageStats_Call{Call: _e.mock.On("StorageStats", ctx)}
}

func (_c *MockTestingProtocolStorageStatsProvider_StorageStats_Call) Run(run func(ctx context.Context)) *MockTestingProtocolStorageStatsProvider_StorageStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_StorageStats_Call) Return(protocolStorageStats *core.ProtocolStorageStats, err error) *MockTestingProtocolStorageStatsProvider_StorageStats_Call {
	_c.Call.Return(protocolStorageStats, err)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_StorageStats_Call) RunAndReturn(run func(ctx context.Context) (*core.ProtocolStorageStats, error)) *MockTestingProtocolStorageStatsProvider_StorageStats_Call {
	_c.Call.Return(run)
	return _c
}

// Workflows provides a mock function for the type MockTestingProtocolStorageStatsProvider
func (_mock *MockTestingProtocolStorageStatsProvider) Workflows() []core.WorkflowDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workflows")
	}

	var r0 []core.WorkflowDefinition
	if returnFunc, ok := ret.Get(0).(func() []core.WorkflowDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.WorkflowDefinition)
		}
	}
	return r0
}

// MockTestingProtocolStorageStatsProvider_Workflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workflows'
type MockTestingProtocolStorageStatsProvider_Workflows_Call struct {
	*mock.Call
}

// Workflows is a helper method to define mock.On call
func (_e *MockTestingProtocolStorageStatsProvider_Expecter) Workflows() *MockTestingProtocolStorageStatsProvider_Workflows_Call {
	return &MockTestingProtocolStorageStatsProvider_Workflows_Call{Call: _e.mock.On("Workflows")}
}

func (_c *MockTestingProtocolStorageStatsProvider_Workflows_Call) Run(run func()) *MockTestingProtocolStorageStatsProvider_Workflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Workflows_Call) Return(workflowDefinitions []core.WorkflowDefinition) *MockTestingProtocolStorageStatsProvider_Workflows_Call {
	_c.Call.Return(workflowDefinitions)
	return _c
}

func (_c *MockTestingProtocolStorageStatsProvider_Workflows_Call) RunAndReturn(run func() []core.WorkflowDefinition) *MockTestingProtocolStorageStatsProvider_Workflows_Call {
	_c.Call.Return(run)
	return _c
}
