// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockTestingProtocolDAGProvider creates a new instance of MockTestingProtocolDAGProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestingProtocolDAGProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestingProtocolDAGProvider {
	mock := &MockTestingProtocolDAGProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestingProtocolDAGProvider is an autogenerated mock type for the TestingProtocolDAGProvider type
type MockTestingProtocolDAGProvider struct {
	mock.Mock
}

type MockTestingProtocolDAGProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestingProtocolDAGProvider) EXPECT() *MockTestingProtocolDAGProvider_Expecter {
	return &MockTestingProtocolDAGProvider_Expecter{mock: &_m.Mock}
}

// BlockChildren provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) BlockChildren(ctx context.Context, c cid.Cid, max *int) ([]cid.Cid, error) {
	ret := _mock.Called(ctx, c, max)

	if len(ret) == 0 {
		panic("no return value specified for BlockChildren")
	}

	var r0 []cid.Cid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, *int) ([]cid.Cid, error)); ok {
		return returnFunc(ctx, c, max)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, *int) []cid.Cid); ok {
		r0 = returnFunc(ctx, c, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, *int) error); ok {
		r1 = returnFunc(ctx, c, max)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestingProtocolDAGProvider_BlockChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockChildren'
type MockTestingProtocolDAGProvider_BlockChildren_Call struct {
	*mock.Call
}

// BlockChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
//   - max *int
func (_e *MockTestingProtocolDAGProvider_Expecter) BlockChildren(ctx any, c any, max any) *MockTestingProtocolDAGProvider_BlockChildren_Call {
	return &MockTestingProtocolDAGProvider_BlockChildren_Call{Call: _e.mock.On("BlockChildren", ctx, c, max)}
}

func (_c *MockTestingProtocolDAGProvider_BlockChildren_Call) Run(run func(ctx context.Context, c cid.Cid, max *int)) *MockTestingProtocolDAGProvider_BlockChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_BlockChildren_Call) Return(cids []cid.Cid, err error) *MockTestingProtocolDAGProvider_BlockChildren_Call {
	_c.Call.Return(cids, err)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_BlockChildren_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid, max *int) ([]cid.Cid, error)) *MockTestingProtocolDAGProvider_BlockChildren_Call {
	_c.Call.Return(run)
	return _c
}

// BlockSize provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) BlockSize(ctx context.Context, c cid.Cid) (uint64, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for BlockSize")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (uint64, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) uint64); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestingProtocolDAGProvider_BlockSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockSize'
type MockTestingProtocolDAGProvider_BlockSize_Call struct {
	*mock.Call
}

// BlockSize is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockTestingProtocolDAGProvider_Expecter) BlockSize(ctx any, c any) *MockTestingProtocolDAGProvider_BlockSize_Call {
	return &MockTestingProtocolDAGProvider_BlockSize_Call{Call: _e.mock.On("BlockSize", ctx, c)}
}

func (_c *MockTestingProtocolDAGProvider_BlockSize_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockTestingProtocolDAGProvider_BlockSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_BlockSize_Call) Return(v uint64, err error) *MockTestingProtocolDAGProvider_BlockSize_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_BlockSize_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) (uint64, error)) *MockTestingProtocolDAGProvider_BlockSize_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockTestingProtocolDAGProvider_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockTestingProtocolDAGProvider_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) Config() *MockTestingProtocolDAGProvider_Config_Call {
	return &MockTestingProtocolDAGProvider_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockTestingProtocolDAGProvider_Config_Call) Run(run func()) *MockTestingProtocolDAGProvider_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Config_Call) Return(manager config.Manager) *MockTestingProtocolDAGProvider_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Config_Call) RunAndReturn(run func() config.Manager) *MockTestingProtocolDAGProvider_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockTestingProtocolDAGProvider_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockTestingProtocolDAGProvider_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) Context() *MockTestingProtocolDAGProvider_Context_Call {
	return &MockTestingProtocolDAGProvider_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockTestingProtocolDAGProvider_Context_Call) Run(run func()) *MockTestingProtocolDAGProvider_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Context_Call) Return(context1 core.Context) *MockTestingProtocolDAGProvider_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Context_Call) RunAndReturn(run func() core.Context) *MockTestingProtocolDAGProvider_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockTestingProtocolDAGProvider_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockTestingProtocolDAGProvider_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) DB() *MockTestingProtocolDAGProvider_DB_Call {
	return &MockTestingProtocolDAGProvider_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockTestingProtocolDAGProvider_DB_Call) Run(run func()) *MockTestingProtocolDAGProvider_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_DB_Call) Return(dB *gorm.DB) *MockTestingProtocolDAGProvider_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_DB_Call) RunAndReturn(run func() *gorm.DB) *MockTestingProtocolDAGProvider_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) DisplayName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTestingProtocolDAGProvider_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockTestingProtocolDAGProvider_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) DisplayName() *MockTestingProtocolDAGProvider_DisplayName_Call {
	return &MockTestingProtocolDAGProvider_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *MockTestingProtocolDAGProvider_DisplayName_Call) Run(run func()) *MockTestingProtocolDAGProvider_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_DisplayName_Call) Return(s string) *MockTestingProtocolDAGProvider_DisplayName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_DisplayName_Call) RunAndReturn(run func() string) *MockTestingProtocolDAGProvider_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) GetConfig() config.ProtocolConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.ProtocolConfig
	if returnFunc, ok := ret.Get(0).(func() config.ProtocolConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ProtocolConfig)
		}
	}
	return r0
}

// MockTestingProtocolDAGProvider_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockTestingProtocolDAGProvider_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) GetConfig() *MockTestingProtocolDAGProvider_GetConfig_Call {
	return &MockTestingProtocolDAGProvider_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockTestingProtocolDAGProvider_GetConfig_Call) Run(run func()) *MockTestingProtocolDAGProvider_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_GetConfig_Call) Return(protocolConfig config.ProtocolConfig) *MockTestingProtocolDAGProvider_GetConfig_Call {
	_c.Call.Return(protocolConfig)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_GetConfig_Call) RunAndReturn(run func() config.ProtocolConfig) *MockTestingProtocolDAGProvider_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTestingProtocolDAGProvider_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTestingProtocolDAGProvider_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) ID() *MockTestingProtocolDAGProvider_ID_Call {
	return &MockTestingProtocolDAGProvider_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTestingProtocolDAGProvider_ID_Call) Run(run func()) *MockTestingProtocolDAGProvider_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_ID_Call) Return(s string) *MockTestingProtocolDAGProvider_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_ID_Call) RunAndReturn(run func() string) *MockTestingProtocolDAGProvider_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockTestingProtocolDAGProvider_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockTestingProtocolDAGProvider_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) Logger() *MockTestingProtocolDAGProvider_Logger_Call {
	return &MockTestingProtocolDAGProvider_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockTestingProtocolDAGProvider_Logger_Call) Run(run func()) *MockTestingProtocolDAGProvider_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Logger_Call) Return(logger *core.Logger) *MockTestingProtocolDAGProvider_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Logger_Call) RunAndReturn(run func() *core.Logger) *MockTestingProtocolDAGProvider_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTestingProtocolDAGProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTestingProtocolDAGProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) Name() *MockTestingProtocolDAGProvider_Name_Call {
	return &MockTestingProtocolDAGProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTestingProtocolDAGProvider_Name_Call) Run(run func()) *MockTestingProtocolDAGProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Name_Call) Return(s string) *MockTestingProtocolDAGProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Name_Call) RunAndReturn(run func() string) *MockTestingProtocolDAGProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) Operations() []core.Operation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 []core.Operation
	if returnFunc, ok := ret.Get(0).(func() []core.Operation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Operation)
		}
	}
	return r0
}

// MockTestingProtocolDAGProvider_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type MockTestingProtocolDAGProvider_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) Operations() *MockTestingProtocolDAGProvider_Operations_Call {
	return &MockTestingProtocolDAGProvider_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *MockTestingProtocolDAGProvider_Operations_Call) Run(run func()) *MockTestingProtocolDAGProvider_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Operations_Call) Return(operations []core.Operation) *MockTestingProtocolDAGProvider_Operations_Call {
	_c.Call.Return(operations)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Operations_Call) RunAndReturn(run func() []core.Operation) *MockTestingProtocolDAGProvider_Operations_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveDAG provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) ResolveDAG(ctx context.Context, rootCID cid.Cid) ([]core.DAGBlockNode, error) {
	ret := _mock.Called(ctx, rootCID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDAG")
	}

	var r0 []core.DAGBlockNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) ([]core.DAGBlockNode, error)); ok {
		return returnFunc(ctx, rootCID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) []core.DAGBlockNode); ok {
		r0 = returnFunc(ctx, rootCID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.DAGBlockNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, rootCID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestingProtocolDAGProvider_ResolveDAG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDAG'
type MockTestingProtocolDAGProvider_ResolveDAG_Call struct {
	*mock.Call
}

// ResolveDAG is a helper method to define mock.On call
//   - ctx context.Context
//   - rootCID cid.Cid
func (_e *MockTestingProtocolDAGProvider_Expecter) ResolveDAG(ctx any, rootCID any) *MockTestingProtocolDAGProvider_ResolveDAG_Call {
	return &MockTestingProtocolDAGProvider_ResolveDAG_Call{Call: _e.mock.On("ResolveDAG", ctx, rootCID)}
}

func (_c *MockTestingProtocolDAGProvider_ResolveDAG_Call) Run(run func(ctx context.Context, rootCID cid.Cid)) *MockTestingProtocolDAGProvider_ResolveDAG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_ResolveDAG_Call) Return(dAGBlockNodes []core.DAGBlockNode, err error) *MockTestingProtocolDAGProvider_ResolveDAG_Call {
	_c.Call.Return(dAGBlockNodes, err)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_ResolveDAG_Call) RunAndReturn(run func(ctx context.Context, rootCID cid.Cid) ([]core.DAGBlockNode, error)) *MockTestingProtocolDAGProvider_ResolveDAG_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockTestingProtocolDAGProvider_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockTestingProtocolDAGProvider_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockTestingProtocolDAGProvider_Expecter) SetConfig(cfg any) *MockTestingProtocolDAGProvider_SetConfig_Call {
	return &MockTestingProtocolDAGProvider_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockTestingProtocolDAGProvider_SetConfig_Call) Run(run func(cfg config.Manager)) *MockTestingProtocolDAGProvider_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_SetConfig_Call) Return() *MockTestingProtocolDAGProvider_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingProtocolDAGProvider_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockTestingProtocolDAGProvider_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockTestingProtocolDAGProvider_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockTestingProtocolDAGProvider_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockTestingProtocolDAGProvider_Expecter) SetContext(ctx any) *MockTestingProtocolDAGProvider_SetContext_Call {
	return &MockTestingProtocolDAGProvider_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockTestingProtocolDAGProvider_SetContext_Call) Run(run func(ctx core.Context)) *MockTestingProtocolDAGProvider_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_SetContext_Call) Return() *MockTestingProtocolDAGProvider_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingProtocolDAGProvider_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockTestingProtocolDAGProvider_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockTestingProtocolDAGProvider_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockTestingProtocolDAGProvider_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockTestingProtocolDAGProvider_Expecter) SetDB(db any) *MockTestingProtocolDAGProvider_SetDB_Call {
	return &MockTestingProtocolDAGProvider_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockTestingProtocolDAGProvider_SetDB_Call) Run(run func(db *gorm.DB)) *MockTestingProtocolDAGProvider_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_SetDB_Call) Return() *MockTestingProtocolDAGProvider_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingProtocolDAGProvider_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockTestingProtocolDAGProvider_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockTestingProtocolDAGProvider_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockTestingProtocolDAGProvider_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockTestingProtocolDAGProvider_Expecter) SetLogger(logger any) *MockTestingProtocolDAGProvider_SetLogger_Call {
	return &MockTestingProtocolDAGProvider_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockTestingProtocolDAGProvider_SetLogger_Call) Run(run func(logger *core.Logger)) *MockTestingProtocolDAGProvider_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_SetLogger_Call) Return() *MockTestingProtocolDAGProvider_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestingProtocolDAGProvider_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockTestingProtocolDAGProvider_SetLogger_Call {
	_c.Run(run)
	return _c
}

// Workflows provides a mock function for the type MockTestingProtocolDAGProvider
func (_mock *MockTestingProtocolDAGProvider) Workflows() []core.WorkflowDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workflows")
	}

	var r0 []core.WorkflowDefinition
	if returnFunc, ok := ret.Get(0).(func() []core.WorkflowDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.WorkflowDefinition)
		}
	}
	return r0
}

// MockTestingProtocolDAGProvider_Workflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workflows'
type MockTestingProtocolDAGProvider_Workflows_Call struct {
	*mock.Call
}

// Workflows is a helper method to define mock.On call
func (_e *MockTestingProtocolDAGProvider_Expecter) Workflows() *MockTestingProtocolDAGProvider_Workflows_Call {
	return &MockTestingProtocolDAGProvider_Workflows_Call{Call: _e.mock.On("Workflows")}
}

func (_c *MockTestingProtocolDAGProvider_Workflows_Call) Run(run func()) *MockTestingProtocolDAGProvider_Workflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Workflows_Call) Return(workflowDefinitions []core.WorkflowDefinition) *MockTestingProtocolDAGProvider_Workflows_Call {
	_c.Call.Return(workflowDefinitions)
	return _c
}

func (_c *MockTestingProtocolDAGProvider_Workflows_Call) RunAndReturn(run func() []core.WorkflowDefinition) *MockTestingProtocolDAGProvider_Workflows_Call {
	_c.Call.Return(run)
	return _c
}
