// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockTestingProtocolRequestDataHandler creates a new instance of MockTestingProtocolRequestDataHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestingProtocolRequestDataHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestingProtocolRequestDataHandler {
	mock := &MockTestingProtocolRequestDataHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestingProtocolRequestDataHandler is an autogenerated mock type for the TestingProtocolRequestDataHandler type
type MockTestingProtocolRequestDataHandler struct {
	mock.Mock
}

type MockTestingProtocolRequestDataHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestingProtocolRequestDataHandler) EXPECT() *MockTestingProtocolRequestDataHandler_Expecter {
	return &MockTestingProtocolRequestDataHandler_Expecter{mock: &_m.Mock}
}

// CompleteProtocolData provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) CompleteProtocolData(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CompleteProtocolData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteProtocolData'
type MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call struct {
	*mock.Call
}

// CompleteProtocolData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTestingProtocolRequestDataHandler_Expecter) CompleteProtocolData(ctx interface{}, id interface{}) *MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call {
	return &MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call{Call: _e.mock.On("CompleteProtocolData", ctx, id)}
}

func (_c *MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call) Run(run func(ctx context.Context, id uint)) *MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call) Return(err error) *MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockTestingProtocolRequestDataHandler_CompleteProtocolData_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) Config() config.ProtocolConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.ProtocolConfig
	if returnFunc, ok := ret.Get(0).(func() config.ProtocolConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ProtocolConfig)
		}
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockTestingProtocolRequestDataHandler_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockTestingProtocolRequestDataHandler_Expecter) Config() *MockTestingProtocolRequestDataHandler_Config_Call {
	return &MockTestingProtocolRequestDataHandler_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockTestingProtocolRequestDataHandler_Config_Call) Run(run func()) *MockTestingProtocolRequestDataHandler_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_Config_Call) Return(protocolConfig config.ProtocolConfig) *MockTestingProtocolRequestDataHandler_Config_Call {
	_c.Call.Return(protocolConfig)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_Config_Call) RunAndReturn(run func() config.ProtocolConfig) *MockTestingProtocolRequestDataHandler_Config_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProtocolData provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) CreateProtocolData(ctx context.Context, id uint, data any) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateProtocolData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, any) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_CreateProtocolData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProtocolData'
type MockTestingProtocolRequestDataHandler_CreateProtocolData_Call struct {
	*mock.Call
}

// CreateProtocolData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - data any
func (_e *MockTestingProtocolRequestDataHandler_Expecter) CreateProtocolData(ctx interface{}, id interface{}, data interface{}) *MockTestingProtocolRequestDataHandler_CreateProtocolData_Call {
	return &MockTestingProtocolRequestDataHandler_CreateProtocolData_Call{Call: _e.mock.On("CreateProtocolData", ctx, id, data)}
}

func (_c *MockTestingProtocolRequestDataHandler_CreateProtocolData_Call) Run(run func(ctx context.Context, id uint, data any)) *MockTestingProtocolRequestDataHandler_CreateProtocolData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_CreateProtocolData_Call) Return(err error) *MockTestingProtocolRequestDataHandler_CreateProtocolData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_CreateProtocolData_Call) RunAndReturn(run func(ctx context.Context, id uint, data any) error) *MockTestingProtocolRequestDataHandler_CreateProtocolData_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProtocolData provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) DeleteProtocolData(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProtocolData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProtocolData'
type MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call struct {
	*mock.Call
}

// DeleteProtocolData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTestingProtocolRequestDataHandler_Expecter) DeleteProtocolData(ctx interface{}, id interface{}) *MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call {
	return &MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call{Call: _e.mock.On("DeleteProtocolData", ctx, id)}
}

func (_c *MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call) Run(run func(ctx context.Context, id uint)) *MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call) Return(err error) *MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockTestingProtocolRequestDataHandler_DeleteProtocolData_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) DisplayName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockTestingProtocolRequestDataHandler_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *MockTestingProtocolRequestDataHandler_Expecter) DisplayName() *MockTestingProtocolRequestDataHandler_DisplayName_Call {
	return &MockTestingProtocolRequestDataHandler_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *MockTestingProtocolRequestDataHandler_DisplayName_Call) Run(run func()) *MockTestingProtocolRequestDataHandler_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_DisplayName_Call) Return(s string) *MockTestingProtocolRequestDataHandler_DisplayName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_DisplayName_Call) RunAndReturn(run func() string) *MockTestingProtocolRequestDataHandler_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// GetProtocolData provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) GetProtocolData(ctx context.Context, tx *gorm.DB, id uint) (any, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProtocolData")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, uint) (any, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, uint) any); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *gorm.DB, uint) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestingProtocolRequestDataHandler_GetProtocolData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProtocolData'
type MockTestingProtocolRequestDataHandler_GetProtocolData_Call struct {
	*mock.Call
}

// GetProtocolData is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - id uint
func (_e *MockTestingProtocolRequestDataHandler_Expecter) GetProtocolData(ctx interface{}, tx interface{}, id interface{}) *MockTestingProtocolRequestDataHandler_GetProtocolData_Call {
	return &MockTestingProtocolRequestDataHandler_GetProtocolData_Call{Call: _e.mock.On("GetProtocolData", ctx, tx, id)}
}

func (_c *MockTestingProtocolRequestDataHandler_GetProtocolData_Call) Run(run func(ctx context.Context, tx *gorm.DB, id uint)) *MockTestingProtocolRequestDataHandler_GetProtocolData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_GetProtocolData_Call) Return(v any, err error) *MockTestingProtocolRequestDataHandler_GetProtocolData_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_GetProtocolData_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, id uint) (any, error)) *MockTestingProtocolRequestDataHandler_GetProtocolData_Call {
	_c.Call.Return(run)
	return _c
}

// GetProtocolDataModel provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) GetProtocolDataModel() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProtocolDataModel")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProtocolDataModel'
type MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call struct {
	*mock.Call
}

// GetProtocolDataModel is a helper method to define mock.On call
func (_e *MockTestingProtocolRequestDataHandler_Expecter) GetProtocolDataModel() *MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call {
	return &MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call{Call: _e.mock.On("GetProtocolDataModel")}
}

func (_c *MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call) Run(run func()) *MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call) Return(v any) *MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call) RunAndReturn(run func() any) *MockTestingProtocolRequestDataHandler_GetProtocolDataModel_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTestingProtocolRequestDataHandler_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTestingProtocolRequestDataHandler_Expecter) Name() *MockTestingProtocolRequestDataHandler_Name_Call {
	return &MockTestingProtocolRequestDataHandler_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTestingProtocolRequestDataHandler_Name_Call) Run(run func()) *MockTestingProtocolRequestDataHandler_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_Name_Call) Return(s string) *MockTestingProtocolRequestDataHandler_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_Name_Call) RunAndReturn(run func() string) *MockTestingProtocolRequestDataHandler_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) Operations() []core.Operation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 []core.Operation
	if returnFunc, ok := ret.Get(0).(func() []core.Operation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Operation)
		}
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type MockTestingProtocolRequestDataHandler_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *MockTestingProtocolRequestDataHandler_Expecter) Operations() *MockTestingProtocolRequestDataHandler_Operations_Call {
	return &MockTestingProtocolRequestDataHandler_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *MockTestingProtocolRequestDataHandler_Operations_Call) Run(run func()) *MockTestingProtocolRequestDataHandler_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_Operations_Call) Return(operations []core.Operation) *MockTestingProtocolRequestDataHandler_Operations_Call {
	_c.Call.Return(operations)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_Operations_Call) RunAndReturn(run func() []core.Operation) *MockTestingProtocolRequestDataHandler_Operations_Call {
	_c.Call.Return(run)
	return _c
}

// QueryProtocolData provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) QueryProtocolData(ctx context.Context, tx *gorm.DB, query any) *gorm.DB {
	ret := _mock.Called(ctx, tx, query)

	if len(ret) == 0 {
		panic("no return value specified for QueryProtocolData")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, any) *gorm.DB); ok {
		r0 = returnFunc(ctx, tx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_QueryProtocolData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryProtocolData'
type MockTestingProtocolRequestDataHandler_QueryProtocolData_Call struct {
	*mock.Call
}

// QueryProtocolData is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *gorm.DB
//   - query any
func (_e *MockTestingProtocolRequestDataHandler_Expecter) QueryProtocolData(ctx interface{}, tx interface{}, query interface{}) *MockTestingProtocolRequestDataHandler_QueryProtocolData_Call {
	return &MockTestingProtocolRequestDataHandler_QueryProtocolData_Call{Call: _e.mock.On("QueryProtocolData", ctx, tx, query)}
}

func (_c *MockTestingProtocolRequestDataHandler_QueryProtocolData_Call) Run(run func(ctx context.Context, tx *gorm.DB, query any)) *MockTestingProtocolRequestDataHandler_QueryProtocolData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_QueryProtocolData_Call) Return(dB *gorm.DB) *MockTestingProtocolRequestDataHandler_QueryProtocolData_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_QueryProtocolData_Call) RunAndReturn(run func(ctx context.Context, tx *gorm.DB, query any) *gorm.DB) *MockTestingProtocolRequestDataHandler_QueryProtocolData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProtocolData provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) UpdateProtocolData(ctx context.Context, id uint, data any) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProtocolData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, any) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProtocolData'
type MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call struct {
	*mock.Call
}

// UpdateProtocolData is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - data any
func (_e *MockTestingProtocolRequestDataHandler_Expecter) UpdateProtocolData(ctx interface{}, id interface{}, data interface{}) *MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call {
	return &MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call{Call: _e.mock.On("UpdateProtocolData", ctx, id, data)}
}

func (_c *MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call) Run(run func(ctx context.Context, id uint, data any)) *MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call) Return(err error) *MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call) RunAndReturn(run func(ctx context.Context, id uint, data any) error) *MockTestingProtocolRequestDataHandler_UpdateProtocolData_Call {
	_c.Call.Return(run)
	return _c
}

// Workflows provides a mock function for the type MockTestingProtocolRequestDataHandler
func (_mock *MockTestingProtocolRequestDataHandler) Workflows() []core.WorkflowDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workflows")
	}

	var r0 []core.WorkflowDefinition
	if returnFunc, ok := ret.Get(0).(func() []core.WorkflowDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.WorkflowDefinition)
		}
	}
	return r0
}

// MockTestingProtocolRequestDataHandler_Workflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workflows'
type MockTestingProtocolRequestDataHandler_Workflows_Call struct {
	*mock.Call
}

// Workflows is a helper method to define mock.On call
func (_e *MockTestingProtocolRequestDataHandler_Expecter) Workflows() *MockTestingProtocolRequestDataHandler_Workflows_Call {
	return &MockTestingProtocolRequestDataHandler_Workflows_Call{Call: _e.mock.On("Workflows")}
}

func (_c *MockTestingProtocolRequestDataHandler_Workflows_Call) Run(run func()) *MockTestingProtocolRequestDataHandler_Workflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_Workflows_Call) Return(workflowDefinitions []core.WorkflowDefinition) *MockTestingProtocolRequestDataHandler_Workflows_Call {
	_c.Call.Return(workflowDefinitions)
	return _c
}

func (_c *MockTestingProtocolRequestDataHandler_Workflows_Call) RunAndReturn(run func() []core.WorkflowDefinition) *MockTestingProtocolRequestDataHandler_Workflows_Call {
	_c.Call.Return(run)
	return _c
}
