name: Build

on:
    workflow_call:
env:
    BUILD_TAGS: s5

permissions:
    contents: read
    checks: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4
                with:
                    submodules: true
            -   name: Setup Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.22.1
            -   name: Build
                run: |
                    make
    golangci:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: '1.22.1'
                  cache: false
            -   name: Install dependencies
                run: |
                    go mod download
                    go generate ./...
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v4
              with:
                  version: v1.54
