name: Build

on:
    workflow_call:
        inputs:
            build_tags:
                description: 'Build tags'
                type: string
                required: true
            upload_artifact:
                description: 'Upload artifact'
                type: boolean
                required: true
                default: false
env:
    BUILD_TAGS: s5

permissions:
    contents: read
    checks: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4
                with:
                    submodules: true
            -   name: Setup Node.js 20.x
                uses: actions/setup-node@v4
                with:
                    node-version: 20.x
            -   name: Setup Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.22.1
            -   uses: pnpm/action-setup@v3
                name: Install pnpm
                with:
                    run_install: false
            -   name: Build
                run: |
                    make
            - uses: actions/upload-artifact@v3
              if: ${{ inputs.upload_artifact }}
              with:
                  name: build-${{ github.sha }}
                  path: ./
    golangci:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: '1.22.1'
                  cache: false
            -   name: Install dependencies
                run: |
                    go mod download
                    go generate ./...
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v4
              with:
                  version: v1.54
