name: Build

on:
    workflow_call:
env:
    BUILD_TAGS: s5

permissions:
    contents: read
    checks: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4
                with:
                    submodules: true
            -   name: Setup Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.22.1
            -   name: Build
                run: |
                    go install go.lumeweb.com/xportal/cmd/xportal@latest
                    bash build.sh