name: Build/Publish

on:
    workflow_dispatch:
        inputs:
            debug_enabled:
                description: Debug
                type: boolean
                default: false
    push:
        branches:
            - master
            - develop
            - develop-*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.GITEA_SSH_KEY }}
                    known_hosts: ${{ secrets.GITEA_KNOWN_HOST }}
            -   name: Publish
                uses: go-semantic-release/action@v1
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    prerelease: true
            -   name: Setup tmate session
                uses: mxschmitt/action-tmate@v3
                if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && failure() }}
                with:
                    limit-access-to-actor: true
