name: Docker

on:
  push:
    branches:
      - '**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: release
            variant: 'release'
            plugins: 'go.lumeweb.com/portal-plugin-sync,go.lumeweb.com/portal-plugin-s5,go.lumeweb.com/portal-plugin-dashboard'
            dev: 'false'
          - name: release-dev
            variant: 'debug'
            plugins: 'go.lumeweb.com/portal-plugin-sync,go.lumeweb.com/portal-plugin-s5,go.lumeweb.com/portal-plugin-dashboard'
            dev: 'true'
          - name: minimal
            variant: 'release'
            plugins: ''
            dev: 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ github.ref_name }}-${{ matrix.name }}
            ${{ github.ref_name == 'master' && matrix.name == 'release' && 'latest' || '' }}
            ${{ github.ref_name == 'master' && matrix.name == 'release-dev' && 'latest-debug' || '' }}
            ${{ github.ref_name == 'master' && matrix.name == 'minimal' && 'latest-minimal' || '' }}
            ${{ github.ref_name == 'develop' && matrix.name == 'release' && 'next' || '' }}
            ${{ github.ref_name == 'develop' && matrix.name == 'release-dev' && 'next-debug' || '' }}
            ${{ github.ref_name == 'develop' && matrix.name == 'minimal' && 'next-minimal' || '' }}
          labels: |
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.description=${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ${{ matrix.variant == 'debug' && 'Dockerfile.debug' || 'Dockerfile' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PLUGINS=${{ matrix.plugins }}
            DEV=${{ matrix.dev }}